### ISSUE TITLE
Cables is not working with MCMultipart

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#4718] opened 2017-09-25 23:21 UTC
Cables is not working with MCMultipart, when a cable goes thru a hollow cover, it's not connected as it should, and is not transfering energy.

The image is taken in 1.10.2, but issue still present on 1.12+.

#### Steps to reproduce:
1. Install Mekanism with MCMultipart and a mod adding covers like Simple Covers.
2. Place cable and make it go thru a hollow cover.
3. Try to use a machine draining energy.

#### Version (make sure you are on the latest version before reporting):
Forge: 12.18.3.2185
Mekanism: 9.2.4.103

https://www.dropbox.com/s/gdfetlu5pb5ugvy/2017-09-26_01.14.08.png

https://www.dropbox.com/s/uvuxj220vun277c/2017-09-26_01.15.08.png

I've also tried to report this issue before, but it was closed before i could upload evidence.

Also Mekanism is not actually adding any microblocks anymore, should it be like that?

**Comment by thiakil** [comment] 2017-09-26 00:37
1.10 is not supported for this - also your screenshot needs another cable on the side that looks unconnected to show that it is not transferring power - I never had any issues using C&B on cables in 1.10.

Will investigate to reproduce in 1.12 (though a screenshot would help)

**Comment by halvors** [comment] 2017-09-26 23:29
@thiakil What do you mean by 1.10 not supporting this feature, it clearly does as it's implementing the MCMultiPart API?

I forgot to add the link the other image showing this more clearly, here it is: https://www.dropbox.com/s/uvuxj220vun277c/2017-09-26_01.15.08.png

Also why isn't Mekanism adding any multipart blocks like covers etc for the decorative blocks?

Same issue persists on 1.11 and 1.12 as well.

**Comment by thiakil** [comment] 2017-09-27 00:24
What I mean was that *we* are only fixing game crashing bugs for 1.10 (and for the most part 1.11). Even when we do do fixes for 1.10/11 it is a low priority. Just don't use Simple Covers on 1.10

> Also why isn't Mekanism adding any multipart blocks like covers etc for the decorative blocks?

It never has and other mods do it better. One could argue that Mek is a tech mod, not a decorative mod. The coloured plastic blocks are added because it would not make sense to only do plain plastic.

> Same issue persists on 1.11 and 1.12 as well.

I said I would investigate this, but as 1.11 and up uses a completely changed MCMultipart API any fix may not even apply to 1.10. If you can provide a screenshot of this in 1.12 it would help the investigation.

**Comment by halvors** [comment] 2017-09-27 10:06
@thiakil You said Mekanism never has added microblocks? This is wrong as it did in every release when using ForgeMultipart.

**Comment by thiakil** [comment] 2017-09-28 00:53
The thing with the saw? That was FMP's doing.

**Comment by thiakil** [comment] 2017-10-01 07:47
Simple covers does not appear to have a release past 1.10, closing as unsupported

**Closed by thiakil** 2017-10-01 07:47 UTC
