### ISSUE TITLE
Robit inventory dupe

### ISSUE THREAD

**Issue by Trinsec** [aidancbrady/Mekanism#4715] opened 2017-09-25 19:00 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*
I checked, this specific case didn't seem to be mentioned yet.

#### Issue description:
When you open the Robit GUI and click on its inventory icon with an item in hand, that item will get duped.

#### Steps to reproduce:
1. Open the Robit GUI. Don't go anywhere specific yet.
2. From your own inventory, select an item you wanted to dump in the Robit's inventory.
3. With that item selected, click on the Robit's inventory icon.
4. You'll drop that item (which you can pick up again).
5. Quit the GUI, reopen it, go to its inventory normally, and you'll also see the item there. It's duped at this point.

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.12.1-14.22.1.2485-universal
**Mekanism:** 1.12.1-9.4.1.326
**Other relevant version:** Using All The Mods 3 v3.3

**Comment by thommy101** [comment] 2017-10-07 12:34
Cannot reproduce in the latest version.

Steps tried:
- Place creative energy cube
- Place ChargePad in front of it
- Place Robit on top of it
- Right click Robit
- Left click a stack of gold ore (any item will do)
- Left click the chest icon of the Robit
- See stack being dropped
- Quit the GUI
- Pickup the dropped stack
- Open GUI
- Click the chest icon
- No items are inserted into the Robit's inventory

**Comment by Trinsec** [comment] 2017-10-07 19:51
I've tested it some more. At first I thought the upgrade of All The Mods 3 to v4.0 fixed it, but then I tried out something: Enable Drop Pickup.

It is not terribly consistent as before, but I still manage to dupe items relatively easily. Follow the steps above but with pickup turned on. When you pick up the dropped item, supposedly at the same time as the Robit picks it up, it's a dupe. Hope you can pinpoint the source now with this info!

**Comment by thommy101** [comment] 2017-10-08 15:03
Confirmed, if you're quick enough to pick the stack up, you've duplicated it.

**Comment by thommy101** [comment] 2017-10-08 15:17
Fixed in dev, will be available in the next release :)

**Closed** 2017-11-26 18:10 UTC
Labels: bug, confirm, Fixed in dev
