### ISSUE TITLE
[Suggestion] for making Heavy  Water

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#2988] opened 2015-10-11 05:32 UTC
as it currently is only mekanism pumps can make heavy water with a filter upgrade installed. The problem with current with the way mekanism pumps work is you have to have like 100 of those to filter heavy water fast enough to make deuterium fast enough to keep up with the fusion reactor and since they currently consume source water blocks, they create MASSIVE chunk update lag my suggestion is to either:

add to configuration file to toggle on/off water source block consumption ( which will help stop some lag and probly much easier to implement)

or

create a new mekanism machine that is specifically made to filter heavy water by just taking in water that is pumped into pipes from any pump from any mod and just filter the heavy water-- which is probly harder to implement but would work just as well and would allow the use of other pumps from other mods.

**Comment by phantamanta44** [comment] 2015-10-11 14:15
In real life, one part of heavy water will occur in 3600 parts of normal water, so it's expected that you would need a lot of pumps to get any decent output.

**Comment by gp009** [comment] 2015-10-12 03:35
true, but they point i was that when you got over 100 pumps consuming water source blocks, this creates a massive block update lag.  the suggestions was to help with lags and do the job. i could have 100 buildcraft pumps bringing alot of water and not consuming water source blocks causing alot less lag even though buildcraft pumps.  

since only mekanism pumps can make heavy water, having 100 of them will create alot of lag, the suggestions i made are to target the and eliminate as much lag as possible

the first suggestion was add an option in mekanism configuration file to toggle on/off the consumption of source blocks leading to fewer block updates and a lot less lag.  (most likely to happen which is fine)

the second suggestion was to remove pumps ability to filter heavy water and just pump normal water and create a machine that takes the water and filter the heavy water--this allow the use of pumps from other mods to pump water into the machine to make heavy water.

I hope im not confusing anyone here, my suggestions just target the block/chunk update lag mekanism pumps cause

**Comment by speakerrob** [comment] 2015-10-17 23:30
@gp009 I'm tracking what you're saying 100% of the way. I think this needs to be addressed at some point. 

I do love the fact that we now have a reason to use the Mekanism pump vs. other mods' options for this task; however, the lag that it creates is significant in some cases. I've also noticed that whenever the chunk reloads all of my water source blocks disappear and need to be replaced.

So, like you, I believe that they should not actually use up the water block itself, since it is an infinite resource. Essentially, from a game design perspective, this only introduces lag without adding any positive dynamic to the game play. Instead, remove that aspect and control production rates through machine upgrades. Please don't mistake me, I'm in no way advocating that it's current implementation is bad. In fact, I rather love Aidan's work, I'm a huge fan and have a lot of respect for his work ethic and attention to detail.

*Just a few more of my thoughts on revising fuel production for the fusion reactor...*

Often it is mistakenly thought that there is but a singular method for deuterium production - water filtering. While in a sense this isn't entirely incorrect, there are in fact a wide range of methods with their own pros and cons. Of these, two methods in particular stand out with regards to Aidan's mod. They are based on two criteria, (1) they would be cool or fun to implement (2) the materials or machines needed in-game are already present in the mod. These two methods are:

1. **The Girdler-Sulphide (G-S) process.** This is probably one of the most refined methods for large-scale production, although not widely used anymore. It was originally used for the CANDU reactor's supply of deut. It involves two stages:
 * *Primary Stage:* Using two large distilling columns (**solar evaporation plants**), one hot and one cold, a feed loop of hydrgoen sulfide gas (H2S) acts as a transport carrier, moving deut from the hot column to the cold one. With an input for water and H2S and an output for deut. H2S gas is actually made from Iron (II) sulfide or an aluminum variant, but this ultimately involves mixing solids and gases to make other gases. So, to make it easier in game with the existing content, I devised the following reaction: 2 H2O + 2 SO2 = 3 O2 + 2 H2S. Since **sulfur dioxide gas** is already implemented, simply pump both it and some water into the **chemical infuser** to make your hydrogen sulfide gas, with a little oxygen to spare. This stage is very energy hungry requiring >10 Mg/kg D2O steam. In-game this would be equivalent to something like 1,000,000 buckets of steam for one bucket of deut steam (ouch). 
![G-S Process](https://upload.wikimedia.org/wikipedia/commons/thumb/4/45/Girdler.svg/514px-Girdler.svg.png)

 * *Final Stage:* Dueterium enrichment from the primary stage is limited to 20% so you must further enrich it for reactor grade stuff (99.7% purity), but this can be handled in one of two ways for gameplay purposes, (1) ignore this fact or (2) pass it into a third solar evaporator to be distilled to its final form. 

2. Deuterium production via separation of isotopes with laser excitation (SILEX). While this method is hi-sci and still in the realm of being impractical for real-world applications, it is perfect for video game use! Probably the simplest method by far, you shoot a laser at something and turn the chemical bonds to jelly. It's a known as a predissociation state, a precise energy level where the force between atoms can change from attractive to repulsive, despite the supplied energy being less than required to break the chemical bond of the molecule. Some configurations of this have yielded deuterium separation factors of over 11,000 times greater than the G-S process above. With a **condensentrator** water could be converted into **water vapor** and energized by a laser in a single-block reaction vessel. Too bad we don't have any lasers in Mekanism that we might arrange into super lasers to accomplish this task....oh wait!

![Lasers What](https://40.media.tumblr.com/3612e3c8b2dbdfd7c84a77d9db2f6a4e/tumblr_nwdu81kcUb1roc2jqo2_1280.png)

**Comment by Mementh** [comment] 2015-10-23 13:00
water is not consumed normally.. this is possable a server setting from your admins? 
I have 6 of them running and they can Fule a normal reactor quite well at 2 injection.

**Comment by XFactHD** [comment] 2015-10-23 23:10
@Mementh the water source blocks are consumed so quickly that they don't have any chance to regenerate. The cause of this is that the Mekanism pump doesn't only have an area of effect on finite fluids but, unlike other mods pumps, also on infinite fluids like water.

**Comment by Mementh** [comment] 2015-10-24 12:29
I have only had once i had to worry about that with a server crash :/ maybe have a reseviour and a flood machine to fix when it does happen for you?

**Comment by nigraforce** [comment] 2015-10-25 11:56
Some people play with finite water, so it is kinda necessary for us to make a setup where we get our water from somewhere(personally, I use Minechem to produce H2O molecules from potatoes) and then we have to use a fluidic plenisher to fill a small pond with water so that an electric pump could suck it up. This is kind of awkward. Moreover, when this mod (http://www.minecraftforum.net/forums/mapping-and-modding/minecraft-mods/wip-mods/2158282-realistic-fluids-overhaul-finite-water-and-stuff) comes out, it will be quite problematic to fill a water block to a full capacity for it to be sucked up by an electric pump.
Check this out:
![2015-10-25_16 53 16](https://cloud.githubusercontent.com/assets/9677869/10715442/12de9dc6-7b39-11e5-8c9c-22e701a01052.png)
I have to use 3 fluidic plenishers to fill the pond fast enough so that the pump is comparable in speed to a usual pump-over-the-endless-pool setup. And that is just one pump!

**Comment by Zaflis** [comment] 2015-12-24 01:42
If you make a bigger water pool and make it flow down by the walls, there seems to be less chance of them being gone by chunk reloading. Also don't place pumps right next to eachother, leave at least 1 block of space between them. I usually go with about 25 pumps for heavy water, and it can infinitely sustain a reactor with 16 injection rate. Bigger problem is how many solar neutron activators you need for that many pumps...

But yeah i'd vote yes for config option on not removing water source blocks. If you want a real world example, water pumping don't really cause Einsteinian time dilation where everything moves slower :)

**Comment by Sj212** [comment] 2016-01-11 19:17
A couple of solutions I can think of would be to add a config option so the pump doesn't consume water sources, or some sort of filtering machine where you input water and it outputs heavy water.

**Comment by chaos234** [comment] 2016-01-16 22:20
I also apollogise that a machine fur deuterium production will be awsome. I don't know how it should work but if it's so hard to get this heavy water for deuterium in real so simply set it's filter value to 3600:1 (3600mB watter = 1mB heavy water) - sounds horrible I know but now we can use all pumps from each mods so water shouldn't be the problem.

@speakerrob - Is your setup you descriped to get deuterium useable for Resonant Rise 3.2.7.2-RC with mekanism (incl. generators and tools) 8.1.7.252 possible or is there another mod needed? Because setting up arround hunderts of pumps will be a server killer, but those are not enough for use, because we are using FOUR fusion reactors ... yes FOUR of them in productivly way and for our design in the base. So if you need such many pumps for only one FR then I don't wan't to know how many I need for FOUR FR ^^.

Oh at last it will be glad to see some screens how you seted up this because the image above doesn't tell me the needed machines/structures.

**Comment by speakerrob** [comment] 2016-01-20 09:08
@chaos234 Your process sounds interesting and full of steps (good thing). It would be fun to try it out. For me emulating the real-world science is a lot of fun, and mekanism has been my favorite tech mod for years now.

**Comment by chaos234** [comment] 2016-01-20 13:31
@speakerrob Thanks for your replay. I also introduced the mod author over PM because there are some points I need to know.

First one is the place, where the Recipes are defined because I implementing it directly in the main files and not as additional plugin because modpacks have enough jar files to load.

Actually is the GSP useable but without the process due to missing recipes.
Another question on this point is why all those fluids/gases not shown on NEI incl. there recipes so it's hard to deal with all thouse fluids/gases which are produced as byproduct or needed for other steps.

It will take a while longer as thought but that doesn't matter because I can look through the images to make the GSP looking differently from the SEP so it's possible that it won't either need copper ... I am thinkin over a recipe which includes Osmiumblock (already included) and as an enriched ingot (well, because osmium is in real a byproduct by getting copper this recpie will not be "real world like" but should be ok).

If I finished the main steps I'll ake some screens and post them here hopefully to find the BBCode to include images directly like in your post.

See you :)

**Comment by chaos234** [comment] 2016-01-21 00:25
Ok, it is show time :)

Well, I haved finished most stuff of what you suggested. Blocks are included with different crafting recipes (images following later, after school); one new ingot, different color (it is a blue/green color, you will see it also later); gases and fluids included also hopefully all neccessery recipes and ... oh ... and a rly nice easter egg :D 

Ok, it's not rly an easter egg but it must be solved so I hope to get the help for this problem (@aidancbrady), because the new structur is equivalent to the SolarEvoporationPlant but it doesn't form like it. Also if I am placing my new valve it turns into a Block of Bronze (which you then can mine o0) ... sames goes to the controller which turns into Osmium Block - I am a little confused and also out of knowledge what's going wrong there.

Last thing is that I added the Recipe for Refined Osmium Ingot (colored in a nice red color ;) ).
It is created in the Metallurgic Infuser with diamond and osmium ingod but for what ever reason it can be also created from a Bronze Block, it can be created with all different Bronze Ingots and tin dust in another Metallurgic Infuser and I don't know why.

If those parts are changed then I can check if the recipes are working (pumping fluid in/out) but actually there are no images for the new fluids (missing), same for the new gases.

At the end I need a little help to get it working but it should be well done at the moment.

To see what I changed but actually not PR'ed du to the errors here is the link to the forked version (8.1.8): https://github.com/chaos234/Mekanism/tree/WaterToHeavyWater/src/main

**Comment by speakerrob** [comment] 2016-01-21 07:20
@chaos234 very impressed, I'll be following your progress. It's neat to see an idea come to life!

**Comment by Mementh** [comment] 2016-01-21 07:48
I would suggest leaving the old in as legacy just in case.. also you don't want to break power supplies people have in current worlds

I don't know how to play with your version so i cna only add suggestions :)  but awesome

If this goes through i would also suggest a change to the pump so that it has a switch for drain/remove souce blocks so it can replace the BC pump for things..  It works very good for other things

**Comment by chaos234** [comment] 2016-01-21 13:07
@speakerrob Thanks for your feedback. I hope that it will finished soon.

@Mementh No I don't want that. This is just a simple addition because of those electric pumps and there current problems with lags ;). It won't breake any of current setups with them ;).

So you have at last two systems to make Heavy Water and yes, with those pumps it will be easier to get Heavy Water and I prefere them but a secondary way actually should be fine.

**Comment by Mementh** [comment] 2016-01-21 13:49
@chaos234 i presume the new system will produce but how much would it produce? I would presume it should have some variable to go up to the max i presume 12 fuel for the reactor? Why not have it make the deuterium directly instead of the seperator being needed 
does the seperator use the energy savings of a energy upgrade for heavy water when installed?

**Comment by chaos234** [comment] 2016-01-21 14:02
@Mementh Well, at this point there are no such variables because at first it must work with the current settings.

The purpose for not making deuterium directly is because of the crossover to the real world where you must do this step to get the little amount of deuterium out like @speakerrob has it described in the 4th post in this ticket and that is what I am programming now.

The hole problem was to create a machine which can hold up to four fluids so here it is - The Girdler Sulfid Processor Plant (short GSP).

Antoher problem was/is to convert gases into fluids because to enrich water with deuterium atoms you need liquid H2S which is actually there as sulfur dioxid gase and must be converted ... well, I don't like to use the Chemical Washer because it is normaly not designd for such things but it is the only way to get H2S by dumping oxgen directly and after that sending it to the rotary condensentrator (deconsentrating) to get H2S as liquid.
Because of using the original designed machines it should work with all supported upgrades and if not feel free to tell it me (but I'll test it before you :P ^^).

Many steps I know and it will need and also get config values to set the produced amount balanced.
But at first it must be build able and this is actually not fixed and I don't know why. Hopefully that this can be fixed as soon as possible. Any solutions are welcome :)

**Comment by chaos234** [comment] 2016-01-25 11:48
Small update:

I fixed the problem why I am getting my own Refined Osmium Ingot if I put a Bronze Block into the crafting field ... used the false IDs from the array in the code.

Will continue after school ;).

**Comment by chaos234** [comment] 2016-01-27 17:38
Next update on it:

Here is a setup for getting the Enriched Dihydrogensulfid Gas:

1. Put sulfur in the Chemical Oxidizer to aquire Sulfur Dioxide

PIC1:

![2016-01-27_17 49 26](https://cloud.githubusercontent.com/assets/340106/12621475/05c3e92a-c521-11e5-886a-0823603a9e55.png)

2. Push the Sulfur Dioxide and Water into the Chemical Washer to aquire Enriched Dihydrogensulfid (simulates 2 H2O + 2 SO2 = 3 O2 + 2 H2S like supposed in Post No. 4 - but without getting Oxygen)

PIC2:

![2016-01-27_17 49 42](https://cloud.githubusercontent.com/assets/340106/12621497/197a923e-c521-11e5-9012-2308843cc028.png)

3. Now pump this new gas in the Rotary Condensentrator (Condensentrating) to switch the gas into fluid (language issue was fixed after screen was made)

PIC3:

![2016-01-27_18 03 23](https://cloud.githubusercontent.com/assets/340106/12621543/5842c388-c521-11e5-95b5-bb7c898b9b9d.png)

4. Put this Fluid in a Tank to store it or better put it directly in the new GSP (actually not working).

PIC4:

![2016-01-27_18 33 15](https://cloud.githubusercontent.com/assets/340106/12622192/7b3c72f0-c524-11e5-96c2-720e0f8ab1cb.png)

Last things todo are renaming Dihydrogensulfid to Enriched Dihydrogensulfid and to get the GSP working but actually it causes rendering issus and I don't know how to solve them. Will be glad if @aidancbrady or @unpairedbracket can help me with that, then it should all working fine after a testrun.

I testing this system with 106 Mods, incl. all referenced mods from Mekanism so X-Compatibality is given ;).

**Comment by sinspawn1024** [comment] 2016-01-30 23:03
@speakerrob Late to the game. I just saw your alternative to the deuterium production process and I absolutely love it! It might be interesting to have both SILEX and GS methods available in game, but tweaked from reality in their production volume. When you first build the fusion reactor, you'd need to build a large laser array both to start the reactor AND to create deuterium to for it. However, the reaction vessel block could have a limited output, so only support a reactor with an injection rate of, say, 2-4. After that point, it could be that the reactor would have to switch to producing steam instead of RF directly, and some of that steam would be used in the SEPs to make deuterium on a large scale. Of course, if this were the case, there would have to be some kind of turbine in the mod to make power from the steam that isn't used for deuterium production.

**Comment by chaos234** [comment] 2016-01-30 23:29
@sinspawn1024 - How would you get deuterium only from steam? SPEs are made for liquids only I think because there is no option with gas input, this means that you must first transform steam into liquid steam over the Rotairy Condensentrator which isn't real world like (ok, you can't do all real world like in a mod) also steam wouldn't have enough of deuterium atomes any more so the outpout in a new programmed SEP will be very low I think.

Correct me if my intension is false but I think that this way is not a good one.

**Comment by sinspawn1024** [comment] 2016-01-31 08:08
@chaos234 Sorry, I didn't explain myself well. I was looking at the image and description @speakerrob posted, which shows a mock-up of how the real Girdler-Sulphide process (GS) works, and had some ideas.

Essentially, this is one idea to add some progression to the fusion reactor. The first level reactor would be the same: same size, taking in deuterium and tritium and directly outputting RF. Tritium production would be the same, using SEPs and SNAs. Deuterium production would change to mirror the SILEX process, by pumping water vapor into a new block, then hitting that block with an amplified laser beam. However, both the SNAs and the deuterium block would be slow, and have trouble sustaining a reactor with an injection rate over, say, 6.

The second level reactor would be one block larger in all directions and no longer directly produce RF, only convert water to steam. The inside of the reactor would be lined with "breeding blanket" blocks, and lithium would be pumped directly into the reactor, converted to tritium, and burned. Deuterium for the reactor would be produced by using some of the steam in hot part the GS process; the rest of the steam would drive a turbine. Basically, the cold stage is mimicked by pumping water AND hydrogen sulfide into an SEP, which would produce deuterium sulfide. The hot stage is mimicked by pumping the deuterium sulfide AND steam into a second SEP, which would output deuterium. Here's a rough sketch of my half baked idea:
![mekanism-gs](https://cloud.githubusercontent.com/assets/16978417/12700769/0ad76138-c7ad-11e5-9d8e-12057d4bfcb8.jpg)

I hope that is more clear. I honestly get super excited about the Minecraft mods that deal with nuclear technology, since I'm almost done with a mechanical engineering degree with a focus in nuclear.

**Comment by chaos234** [comment] 2016-01-31 13:41
@sinspawn1024 

This looks better as your first post and now I can flollow your Idea. But from where do you get the H2S? I think that you have read my postings above yours which shows how to get it - well this is only programmed in my version and actually not send as PR because my GSPs aren't working and I can't figur out why - then your Idea is possible but needs two different new Versions for the SEP so that they accept liquid/gas and putting out D2S as liquid/gas (?) which then is pumped into another SEP of the same type or a special one which can only hold steam, D2S and putting out D.

My problem with this way is only the chemical way because of the GS and what @speakerrob thought about aquiering it seems to be a litte not real world like so is there a way that you can show me the chemical reactions as formula like in @speakerrob 's post?

Don't missunderstand me because nuclear reactions are also funny (simply look on the IC2 NR which can explode ;) ) but only if the reactor can explode by handling him false (or that maching which does this nuclear reaction - but one must be explodable).

Ok, hope that you can follow me because my englisch isn't all time the best - simpl school englisch - however ... it's in fact also a good Idea but I am missing this "real world feeling" ;).

**Comment by chaos234** [comment] 2016-02-01 11:47
Here is the suggested flow from how to get enriched water (III) to get it with a "high" amount of deuterium to extract it:

![gsp-process](https://cloud.githubusercontent.com/assets/340106/12716555/c0cbe8da-c8e1-11e5-9c45-a48bdfdea7d8.png)

I hope that I made it correctly in my computer science lesson but I think it's ok.
If there any questions about that, feel free to ask ;).

**Comment by chaos234** [comment] 2016-02-01 17:33
Ok, I decided to change the production for deuterium because I can't get my ovn "SEPs" working and it seems that actually nobody can help me.

My idea now is to pump water vapor and dihydrogensulfid in the Chemical Infuser to get deuterium but not many. I'll think about mor then one state for this step but at the beginning it will only be 1000 water vapor and 1000 enriched dihydrogensulfid to get 10 deuterium (without any upgrades). There for you'll get 1:1 output from sulfur to dihydrogensulfid.

Let me know if this is ok because I must not create a new one and also I can use all other machines to make it more complex with higer output ;).

**Comment by chaos234** [comment] 2016-02-05 20:05
Good News:

I have finished the new process to have another way to aquire Deuterium over some steps including Tier1 to Tier 3 Production (poor, mid, high).

For detailed information look at first on the image below, this should explaine all your questions. Otherwise feel free to ask :).

Hoping that the values are good enough and also well balanced but at this moment I'll sent the pull request hoping that it will be accepted.

T1 to T3 - Deuterium Production:
![newdeuteriumprocessing](https://cloud.githubusercontent.com/assets/340106/12857748/33f2a1d8-cc4c-11e5-9142-8826d95412b5.png)

**Comment by Mementh** [comment] 2016-02-06 09:32
the goal is to reduce server lag/usage caused by water block updates.

imho that looks like your adding machines/complexity to a system that i am not sure needs it or does not reduce usage. 
( some of this questions the complexity some of it is how the science works )

1. to get sulfur the best way i know is pulling from the 5x system of making .. cobble crushed to gravel pulverised ( or purified to flint) to flint then crushed to gunpowder then enriched with hydrogen cloride sulfer ... would that process reduce server usage vs the current system?

2. does this make more chemical sense vs current setup? 

3. if the primary issue is to reduce server lag.. why not have a additional upgrade for the pump that does not "pump" and destroy water source blocks and just acts like the liquid transfer node from extra utilities?

**Comment by chaos234** [comment] 2016-02-06 14:58
@Mementh 

1. Why should I use x5 to get sulfur? This is waste of ressource because you get sulfur (from what ever ore) with luck much faster. Now think about mod packs which mostly have Tinker's Construct installed. Make with this a fast and with full luck provided hammer, put it in an autonomus activator, place arround some vacuum hopper and with one block space between place block placer which are placing ores like redstone, lapis, all kinds of sulfur, end so on ... the result is that mekanism can't win against this methode aquiering sulfu which reduces machine usage.

2. It makes chemical sense but not like the real GSP process from the 4th post because I don't use a (new) SEP. But the main reaction is still alife, only splitted.

At first, you have to make Sulfur Dioxid. Now you need this and some water to get H2S like in the following formular: 2 H2O + 2 SO2 = 3 O2 + 2 H2S

Well done over the chemical washer so why not using him all the time? This splits the hole reaction I know but how it's made is the same.

Ok, you can now choose to put the rult in a new chemical washer to get enriched water with poor amount of deuterium through the electrolytic separator but wait, you can get even more deuterium if you want. How? Simply enrich th above result up to two times with the chemical infuser to get the highest output for deuterium (1:1 because oxygen will be produced normaly).

That's it to get deuterium from another way. And don't even copy the abouve setup because you can also use one machine for each step but then be patient with all those upgrades for it our you will be get in trouble ;).

3. This is a good question and also a good Idea too. But then there is allways the pumping speed left and this means that I must also includ speed and energy upgrade and I don't know if @aidancbrady  would like this, otherwise he had already included speed and energy upgrade to the pump.

Finally it is not realy like the GSP but chemicly it is ok how it works. It was only splitted not more not less and since the pumps are pumping not many heavy water. So why not doing this process a little bit harder so that you can choos between pumps/heavy water and the new way? It's not the best and can be optimized but actually I have no Idea how to do this. Ideas are welcome :).

**Comment by Mementh** [comment] 2016-02-06 22:10
the reactor is something you want running 24/7 it does not stop running/consuming fuel.. this is why people have the pumps and such.. 
relying on luck to make the process can cause loss of power/having to restart ... just not efficient imho esp when pumps currently do this with just power and a filter.
so using the sulfur making process discribed is imho more reliable to making a reactor 24/7



i get the infuser and I honestly like this idea as a roleplay mechanic to a great degree like making the tritium..

chemically this matches the Girdler sulfide process .. it does not heat things up like the process? or is that covered by the washer?

Why not do a bit more hand waving like the tritium does and use the solar neutron activator on hydrogen sulfide and have that make it? it woudl add the heat 




The system is shown as a closed loop i think for the sulfide? so it should not need constant sulfur? maybe a crystalizer to break it down after it is electrolized to duterium and sulfur?  

!!! Use a Pressurised reaction chamber to do this.. it feels more chemically/normal to use this


use oxidiser on sulfur.. then sulfure to chemical wash to make liquid sulfur water .. into pressure chamber with hydrogen instead of the infuser to make gassious heavy water and sulfur ( closed loop and "heat" applied

see pic.. i feel a simple approach is better ..  if you want to add in more h2 you could before the PRC ? 

http://imgur.com/qiQqUuE

http://i.imgur.com/qiQqUuE.png

**Comment by chaos234** [comment] 2016-02-06 22:51
@Mementh - Nice to read you improvment but can you also write the steps done at each machine in your pictor like in my one? then simply upload it in you next comment here.

If you can do this, it will be glad to see and it should be possible to programm/script and test it.
But it sounds good.

Also you are right with your intension that the heat is not covered/used but with the SNA it will be included.

How ever, it is not a closed system because if you don't supply sulfur instantly you won't get H2S which is required for all following steps which means no sulfur = no deuterium ;).

**Comment by Mementh** [comment] 2016-02-07 21:12
@chaos234 
http://imgur.com/73xKiOU

http://i.imgur.com/73xKiOU.png

sulfur is "made" in the PRC as a byproduct.. it could have a loss of some.. or 100% self contained once full IE you can have a stack in the oxidiser and that will be all you need.

**Comment by chaos234** [comment] 2016-02-08 03:38
@Mementh - Nice Idea. It's fast and uses things wich are already included in the game. But to not end up in a loop I think that if you input one stack of sulfur that you'll be only get back arround the half or three quarter of it. Otherwise you only need one stack or arround 120 sulfur to compleatly loop it without loses and this isn't that what I or other player want.

Hope that this will be ok for you ;).

**Comment by Mementh** [comment] 2016-02-09 07:04
hmmm i don't like that still.. eating up the sulfur is a issue..

the question is why eat up? is it to make a more complex system? or to make it a resource that will eventually need replenishment?  
if so then i would say the reactor needs to change how it makes power.

IE most people want a sustainable reactor that can go 24/7.. people will build solar worlds in RF tools to do it.

so if thats the case.. i would suggest the reactor start to behave like ADV generators do and not consume resources unless filling a energy need.. then a resource eating system like this would be ok and resonable.


few ideas

without sulfur it produces 10% of the needed heavy water. this will be minimum needed to sustain the reactor. ( washer makes "unsulfur water" ) ( would suggest re-using the filter upgrade to make it do this special washing with and without sulfur )

a full speed setup can keep a reactor at level 2 without issues.. let the player see the power issues and deal with sulfur? 

A idea is to have it need enriched sulfur in the enriching chamber.. or have it outputted as a gas and need crystalising to use it again?



knowing why you want it to eat sulfur would help in understanding more.

**Comment by chaos234** [comment] 2016-02-10 23:21
No, there will not be a 24/7 infinite cycle. If you don't provide enough sulfur you can't use it.
If this doesn't apply with you suggestion/meaning then I can't do anything for your.

This means that I don't change the current system, if the new one should be run infinite.
Because a reactor is not a solar panel it must be filld with ressources which must be at first aquired and processed and if you don't have the needed materials you can't use it like buying some food without money ... not possible in real ;).

**Comment by Mementh** [comment] 2016-02-11 09:40
but this is minecraft.. which has mining lazers that pull out of bedrock/void :)

the problem is what happens when the resources run out? then its a complicated process to keep feeding it.. 
consider people will make a turbine and big reactor and a mining lazer JUST to make yellorium and then its infinite fueled constant running. 

They bypassed the constant mining to fuel it easily.


This leads me to presume people don't want a system that requires constant maintinance/fueling of a rare or semi rare or any resource if they can avoid it.




if your system is wanting to change how you fuel the reactor to be a non constant system fueled essentially by sulfur.. thats ok.. 

But players wont do it.. they wont use the blocks or methods you put in over the water pumps... they will not see the benifit of setting up some automation to make the heavy water with it. 

The users would not even try setting up a reactor based on going out and mining things even with a digital miner. They would wait till they figure out a easy way to bypass the need for sulfur with the same way you do it for a 5x system. 

Thus brining us back to a earlier question.... would doing the new way cause LESS update or server lag then the water does now?

Which is one of the main complaints the author of this thread @gp009 had. ( the # of pumps needed i think he was counting wrong since its about 1 pump per fuel level and max fuel is 12. as i have tested )



The current reactor setup is decent as it is other then its block updating for water so if thats not the fix or the goal.... 



Then my suggestion is what your thinking of become a new reactor that behaves better IE makes power on demand and does not just consume resources 24/7 like the current one IE tritium and duterium come in and only are consumed to refill a buffer that the reactor makes.. it can have a max output thats more then the reactor now if you wanted.


Roleplay wise.. this is LOVELY! and awesome... but we have already suspended matching real world for the reactor and i don't feel changing at this time would be welcome by users or reduce server lag from updating blocks or offer a better power system then currently available.

**Comment by XFactHD** [comment] 2016-02-11 11:22
The max injection rate is 98 AFAIK.

**Comment by Mementh** [comment] 2016-02-11 11:52
giggles i did not know @XFactHD i know 1 million rf/tick is 12ish so thats awesome

i set it to 98 and its making 9m rf a tick.. which is alot! 
but still my point is there.. :) the reactor we have is setup to run 24/7 and a demand of a non easily renewable resource for it is silly.

if it was on use power that would be a acceptable trade off to a degree.

**Comment by gp009** [comment] 2016-02-11 22:51
the max injection rate is actually 99  which is the point of having  several hundred pumps for both heavy water and making bring then to lithium then to gas lithium and then tritium.

**Comment by XFactHD** [comment] 2016-02-12 07:32
It was changed to be 2, 4, 6 and so on, meaning that there is no injection rate of 99.

**Comment by aidancbrady** [comment] 2016-03-06 08:19
Closing until further notice- as discussed on the PR, I am in full favor of someone making this a separate Mekanism module.

**Closed** 2016-03-06 08:19 UTC
Labels: enhancement
