### ISSUE TITLE
1.10.2 miner crash

### ISSUE THREAD

**Issue by macqo004** [aidancbrady/Mekanism#4663] opened 2017-08-31 19:15 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

when you place a miner with blacklist after about minute it crashes with this message:
[crash-2017-08-31_21.06.27-server.txt](https://github.com/aidancbrady/Mekanism/files/1268241/crash-2017-08-31_21.06.27-server.txt)

#### Steps to reproduce:
1.place miner in world

#### Version (make sure you are on the latest version before reporting):
**Forge:**  forge-1.10.2-12.18.3.2316
**Mekanism:** Mekanism-1.10.2-9.2.3.97
**Other relevant version:** using ender chest if it is important

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

java.lang.NullPointerException: Ticking block entity
	at mekanism.common.util.MinerUtils.getDrops(MinerUtils.java:35)
	at mekanism.common.tile.TileEntityDigitalMiner.onUpdate(TileEntityDigitalMiner.java:267)
	at mekanism.common.tile.prefab.TileEntityBasicBlock.func_73660_a(TileEntityBasicBlock.java:78)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Unknown Source)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-08-31 19:28
Duplicate of #4637

Is fixed and will be available in the next release.

**Closed by thommy101** 2017-08-31 19:28 UTC
