### ISSUE TITLE
[1.11.2]IC2 cable compatability

### ISSUE THREAD

**Issue by meitangdehulu** [aidancbrady/Mekanism#4571] opened 2017-07-27 16:12 UTC
Hi,
MEK's cable cannot connect with IC's machine, and IC's cable cannot connect to MEK's machine.

Forge:13.20.1.2386
Mekanism:9.3.3.312
Other relevant version:industrialcraft-2-2.7.81-ex111

Thanks for the effort.

**Comment by thommy101** [comment] 2017-07-27 16:25
Duplicate of #4370

**Closed by thommy101** 2017-07-27 16:25 UTC
