### ISSUE TITLE
MekanismGenerators crash on Server

### ISSUE THREAD

**Issue by D3nnis3n** [aidancbrady/Mekanism#4844] opened 2017-12-02 22:01 UTC
#### Issue description:
Crash when starting the Server.

#### Steps to reproduce:
1. Start the Server
2. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** 2556
**Mekanism:** 9.4.2.327 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://gist.github.com/D3nnis3n/8bb1d3b89222e0f9d90e78036ea23ecb

**Comment by thommy101** [comment] 2017-12-02 22:11
Thanks for reporting, but please use the search functionality of github as this is reported multiple times.

Closing as duplicate of #4827

**Closed by thommy101** 2017-12-02 22:11 UTC
