### ISSUE TITLE
Digital Miner disappearing

### ISSUE THREAD

**Issue by Alfatossa** [aidancbrady/Mekanism#4226] opened 2017-02-21 01:27 UTC
Hi it happened twice on my server that when i leave the location of my Digital Miner (the nether in this one) it just disappear once i left it even if i have placed a chunk loader im using the latest version of mekanism please help me

**Comment by Protheus** [comment] 2017-03-01 11:23
Did you use the chunckloader upgrade or a seperate chunckloader ? I had the same issue. I added the chunckloader upgrade and it did not disappear anymore

**Comment by BrianEdmonds** [comment] 2017-03-28 15:53
I've also had this happen to me on 300. Hasn't recurred since I added the anchor upgrade, but the original disappearance is definitely a bug.

**Comment by thommy101** [comment] 2017-03-31 18:39
Duplicate of #3718

**Closed** 2017-04-12 14:24 UTC

**Comment by ghohenzollern** [comment] 2018-07-10 03:47
Hello! We're experiencing the same bug. Two things to add which may help lead to a solution:

1. We were able to reproduce the bug while running Mekanism ONLY, eliminating the possibility that it's a cross-mod bug.
2. We got it on video. https://youtu.be/BEy24f7ChxI

Let me know if I need to open a new issue, since this one has been closed.
