### ISSUE TITLE
[1.12.2] Poof! Mekanism Generators crash...

### ISSUE THREAD

**Issue by Migmag789** [aidancbrady/Mekanism#4866] opened 2017-12-15 20:26 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
MekanismGenerators crash at 5/7 or a thing like that

#### Steps to reproduce:
1. Use a big fat amount of mods
2. Use latest version of mods
3. Wait and see

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2566
**Mekanism: 9.4.2.327
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
[crash-2017-12-15_16.39.58-client.txt](https://github.com/aidancbrady/Mekanism/files/1563897/crash-2017-12-15_16.39.58-client.txt)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-12-15 21:19
Please use the search functionality. Duplicate of #4827

**Closed by thommy101** 2017-12-15 21:19 UTC
