### ISSUE TITLE
Cannot get bdew's Advanced Generators gas turbine generator to output into Mekanism universal basic cable (MC1.10.2)

### ISSUE THREAD

**Issue by ab9rf** [aidancbrady/Mekanism#3693] opened 2016-08-25 13:57 UTC
Cable binds to the Advanced Generators flux generator module, but generator does not output RF. Generator generates power, but it never goes anywhere.

Using generators-0.9.20.10, bdlib-1.12.2.8-mc1.10.2, Mekanism-1.10.2-9.1.1.29

Update: the generator will push power into a Mekanism energy cube, just not into a Mekanism universal cable.

Cross-ref: bdew/generators#114

**Comment by bdew** [comment] 2016-08-25 21:48
The problem is that the cables don't implement any of the RF interfaces (and it's not easily fixable on mek side, because they are multipards) so the generator can't detect them or output to them.

The easiest solution would be to use Tesla emitter instead of RF, but that's currently also broken due to #3696. But once that is fixed, using tesla should work seamlessly.

You can right click the face of the generator where the cable connects with a wrench to force it to output mode, but i don't think the cables can actually pull power. So for now the only way to make it work is to use a power cube as a buffer i think.

**Comment by aidancbrady** [comment] 2016-08-25 21:55
Should be fixed in development, thanks

**Closed by aidancbrady** 2016-08-25 21:55 UTC
