### ISSUE TITLE
Mekanism will not recharge EnderIO items (1.10.2)

### ISSUE THREAD

**Issue by Nuinethir** [aidancbrady/Mekanism#4143] opened 2017-01-14 23:06 UTC
I have come across a problem where Mekanism (what I use for my power systems) will not charge EnderIO items (such as their Electromagnet). I have tried direct insertion into Energy Cubes as well as standing on the Charging Pad. I have to use either their Capacitor Bank or the Wireless Charger.

Conversely, Mekanism items/blocks can be charged on EnderIO charging methods.

I thought this was strange and opened a ticket with them, though they said the problem was on your side (though Mekanism will charge any items from any mods so far except EnderIO). They said it had something to do with the Tesla API. I then installed the Tesla mod with no effect.

**Link to the issue on their Git:** https://github.com/SleepyTrousers/EnderIO/issues/3992
**Forge:** 1.10.2-forge1.10.2-12.18.3.2202
**Installed Mods:** http://pastebin.com/wZrYQXAx

**Comment by ThatGamerBlue** [comment] 2017-01-15 07:14
Duplicate of #4116

**Comment by Nuinethir** [comment] 2017-01-15 09:14
I will follow the other ticket. Thanks for the link. :+1:

**Closed** 2017-03-31 13:43 UTC
