### ISSUE TITLE
Missing Textures in JEI - Various items

### ISSUE THREAD

**Issue by jbjmed** [aidancbrady/Mekanism#5215] opened 2018-12-07 01:38 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Flamethrower, Free runner, energy cubes all missing item texture in JEI. Only thing that shows up is the power bar for the items. 

#### Steps to reproduce:
1.Installed in various instances
2.Issue persists regardless of instance
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.5.2795
**Mekanism:** 9.4.13.349
**Other relevant version:**

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by pupnewfster** [comment] 2018-12-07 16:41
Duplicate of #5205

**Closed** 2018-12-09 03:40 UTC
