### ISSUE TITLE
Large multi-block structures freezes up client on loading world

### ISSUE THREAD

**Issue by gp009** [aidancbrady/Mekanism#2609] opened 2015-04-30 00:56 UTC
using:

Forge version 1352
Mekanism 8.1.0

I had problems like this for quite sometime but i had to first narrow down what can be causing this lock-up

This seems to be only occurring when using any multi-block structures like dynamic tanks, fusion reactors, and induction matrices.  

currently i have 1 fusion reactor 2 dynamis tanks ( both 5x5x10 ) and 1 induction matrix ( 9x4x12 all ultimate components )

any suggestions on how to resolve this please?   thanks

**Comment by XFactHD** [comment] 2015-04-30 06:14
I have the same problem, I have 6 solar evaporation plants in the desert and they are chunkloaded. Because I don't want to waste time, I fly in the direction where they are built with a fluxed jet-plate (simply jetpacks, the speed is enormous when sprinting). As soon as they come into render distance, the game becomes slower and doesn't answer anymore. Then I have to force close the game. On world reload, I have to be quick and turn around to avoid getting stuck. If I fly backwards in the direction of the towers, the game doesn't get stuck.

**Comment by tossaponk** [comment] 2015-04-30 14:23
I can also confirms this, I'm running 4 solar evaporation plants. They're very far from my home so I built teleporters to get there, and upon arrival, the game randomly freezes.

**Comment by XFactHD** [comment] 2015-04-30 14:52
Are they chunkloaded? If yes, by a chickenchunks chunkloader?

Those use some hacks to overwrite the forge chunkloading mechanics and seem to have big problems sometimes. My solar evaporation plants are also loaded by one of those. I will try it with another chunkloader and then I will come back with my results.

**Comment by tossaponk** [comment] 2015-04-30 15:25
Yes, they're chunkloaded by using RailCraft World Anchor which is used CoFH chunkloading API if I'm not mistaken.

**Comment by XFactHD** [comment] 2015-04-30 23:11
This means that the chunkloaders are no issue in your case. Also, chickenchunks doesn't have anything to do with the CoFH chunkloading api. With the railcraft chunkloaders using this you might be right.
The problem seems to be rendering, in my case the game freezes as soon as the solar evaporation plants come into render distance (about 10 chunks on my settings).

**Comment by gp009** [comment] 2015-05-01 00:52
I been trying that trick you mentioned in your first post about walking/flying backwards toward the structures,  though i lag immensely atleast I didnt lock-up anymore.  hopefully there will be a fix for the issue with these structures.

**Comment by enterprise12nx** [comment] 2015-05-01 20:13
Confirmed, made this issue here:
https://github.com/aidancbrady/Mekanism/issues/2426#issuecomment-95298238
https://github.com/aidancbrady/Mekanism/issues/2397#issuecomment-87294815
this really needs to be fixed!

**Comment by jonpw** [comment] 2015-05-02 04:03
I almost commented on #2426 as going near towers for me meant a random choice of 1) lockup 2) cofhlib error as in 2426 or 3) a fastcraft error. I finally updated mekanism to 228/229 from 216 (I had held off due to logistical pipes/ticking block enitty errors) and the problem went away completely. Not sure why, as the changelogs didn't seem to show much relevant.
Upgrading enderio, cofh*, fastcraft etc all had no effect.

**Comment by draeath** [comment] 2015-05-05 21:01
hmm seems build 229 requires forge 1395. FTB Infinity (where we're adding Mekanism to, among other things) uses 1352. While I'm willing to make small changes to the base pack, I'm not willing to do something so potentially disruptive as to upgrade forge.

I don't suppose there's any way to get this fixed on a version that's compatible with Forge 1352? Sadface.

**Comment by XFactHD** [comment] 2015-05-08 12:26
Isn't build 228 compatible with forge 1352 and lower or am I a complete idiot?

**Comment by HanatakeYurii** [comment] 2015-05-08 12:29
You're right, it's compatible

**Comment by aidancbrady** [comment] 2015-05-09 22:48
Should be fixed.

**Closed by aidancbrady** 2015-05-09 22:48 UTC
