### ISSUE TITLE
Industrial Turbine steam input and production display issues

### ISSUE THREAD

**Issue by Clariat** [aidancbrady/Mekanism#4481] opened 2017-06-19 03:30 UTC
On the UI for the turbine, it always displays 0 production, and 0 flow rate. 

Now, the turbine is actually producing power, but does not tell me how much.  

mekanism-1.7.10-9.1.1-clienthax.jar

This occurs every time I create the turbine.  Breaking and reforming has no effect.  Restarting server has no effect.

Running the 1.7.10 Pack

**Comment by thommy101** [comment] 2017-06-19 08:28
1.7.10 isn't supported any more. Also, use search as this has been reported previously.
See #3301

**Comment by Clariat** [comment] 2017-06-19 20:34
Ah.  I thought it might not be supported much anymore.  I was hoping someone had a work around or solution for it though.  

In #3301, the issue is displaying fractions of the rates and breaking and reforming the structure fixed it.  That is not the case here as the bug produces every single time to display 0 on both production and flow rate, and breaking and reforming does not change.  The rest of 3301 is detailing rates and interactions of various pipes with which I am currently not having issues.  I figured the issue was different enough (perhaps?) to merit a different post.  I can always just join that chain if you think I would have better luck there.  Or I could just close it and move on if you think it might be a lost cause :).

**Comment by thommy101** [comment] 2017-06-19 20:45
The issue is merged with one about always displaying 0 as values. #4427
It's on the radar, but I'm 99% sure it won't be back ported to 1.7.10

**Comment by Clariat** [comment] 2017-06-19 22:26
Thank you for your prompt responses :)

**Closed** 2017-06-20 18:56 UTC
