### ISSUE TITLE
Reactor Logic adapter allows setting injection rates outside normal bounds

### ISSUE THREAD

**Issue by DerMax93** [aidancbrady/Mekanism#4286] opened 2017-03-31 23:41 UTC
You can set the Injection-rate of the Fusion reactor to non-standard values.
I can set it to 3 or 100 (or probably some other weird values).
You should maybe apply the same checks you use when inputting via GUI (I'm no java expert, but I assume it should be possible).

Mekanism Version is 9.2.1
OpenComputers is 1.6.1.6 (shouldn't matter if I understood correctly how the interface between the mod is implemented)

**Comment by thommy101** [comment] 2017-04-01 08:20
Duplicate of #4030 
Works as intended

**Closed** 2017-04-03 18:27 UTC
