### ISSUE TITLE
Thermal Evaporation Plant Issue

### ISSUE THREAD

**Issue by Amzeroth** [aidancbrady/Mekanism#4541] opened 2017-07-18 15:54 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I am having an issue with the Thermal evaporation plant in the mod. Since the game updates every block that is part of the plant when it (the game) starts up, it is causing a huge, and i mean huge, lag spike. Since i put 2 next to each other in the ore processing facility that i was building, and my game crashed (Because i was adding some levels to the TEP) when i was right beside them, now everytime i try to enter the world i was in, the game lags so hard that it crashes without letting me move an inch. Is there a way i can solve this or deactivate the TEP temporarily so i can move all that stuff to other chunk? I'm worried because the only thing left to try is to take out the whole mod from the game and that would destroy at least an 80% percent of the things i have built already. 

#### Steps to reproduce:
1. Setup two thermal evaporation plants, with a height of 14 blocks
2. Destroy the thermal evaporation controller and add extra levels (5 in my case)
3. Place the thermal evaporation controllers again 

#### Version (make sure you are on the latest version before reporting):
**Forge:** 
**Mekanism:** 
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-07-18 18:42
Duplicate of #4425

**Comment by Amzeroth** [comment] 2017-07-18 22:56
Is this aplicable to the latest version? And if so, how do i apply this fixes to my game? Sorry

**Comment by thiakil** [comment] 2017-07-19 01:50
It is as yet unsolved, there is a pull request that might alleviate it, but it is yet to be integrated.

**Closed** 2017-07-21 17:12 UTC
Labels: bug, duplicate
