### ISSUE TITLE
1.10.2 version cant use eu from ic2 machine

### ISSUE THREAD

**Issue by PorPit** [aidancbrady/Mekanism#4519] opened 2017-07-09 14:22 UTC
problem: cant use eu from ic2 machine

ic2: industrialcraft-2-2.6.245-ex110
Mekanism: Mekanism-1.10.2-9.2.2.301
**Forge:12.18.3.2316

**Comment by thommy101** [comment] 2017-07-10 12:12
Duplicate of #4370

**Closed** 2017-07-11 17:30 UTC
