### ISSUE TITLE
Breaking AE2 recipes.

### ISSUE THREAD

**Issue by Aulton** [aidancbrady/Mekanism#2324] opened 2015-03-23 14:23 UTC
90% of the recipes are broken upon adding any build of Mekanism to a custom modpack. I removed Mekanism and all the recipes come back, working 100%. Not sure what Mek has to do with Ae2, but it's interfering with something.

**Comment by laz2727** [comment] 2015-03-23 14:25
Known.

2015-03-23 20:23 GMT+06:00 Aulton <notifications@github.com>:

**Comment by halvors** [comment] 2015-03-23 14:39
This is really annoying, hoping for a fix soon :)

**Comment by unpairedbracket** [comment] 2015-03-23 14:56
I'm sure I've heard reports that disabling AE2's Mekanism integration is a workaround for this, try that in the interim?

**Comment by Aulton** [comment] 2015-03-23 15:21
It did, and it also fixed and issue with the mekanism recipes not working as well. I'm not sure what mod integration having it on adds, but we may be missing out on that. Anyone know what they might be?

**Comment by halvors** [comment] 2015-03-23 16:01
Hmm. Doesn't work for me :(

**Comment by mst3in** [comment] 2015-03-23 17:57
The problem is how AE2's build process works.  They are working up a way to get mek's new API integrated into that build process.  The problem isn't as simple as it sounds.

https://github.com/AppliedEnergistics/Applied-Energistics-2/issues/1061

**Comment by aidancbrady** [comment] 2015-03-23 23:43
Closing - this is being looked into by AE2

**Closed by aidancbrady** 2015-03-23 23:43 UTC
