### ISSUE TITLE
Crash 1.10

### ISSUE THREAD

**Issue by Wasthereonce** [aidancbrady/Mekanism#3503] opened 2016-07-20 00:43 UTC
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  LoadingPlugin (Quark-beta-46.jar)
  FMLPlugin (InventoryTweaks-1.61-58.jar)
Contact their authors BEFORE contacting forge

// Ouch. That hurt :(

Time: 7/19/16 5:40 PM
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: mcmultipart/block/BlockMultipartContainer
	at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:562)
	at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:216)
	at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: mcmultipart/block/BlockMultipartContainer
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:344)
	at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:485)
	at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:235)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:213)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
	at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
	at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
	at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
	at com.google.common.eventbus.EventBus.post(EventBus.java:275)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
	at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:531)
	... 10 more
Caused by: java.lang.ClassNotFoundException: mcmultipart.block.BlockMultipartContainer
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	... 34 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
	... 36 more

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.10.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 170747160 bytes (162 MB) / 392060928 bytes (373 MB) up to 4281597952 bytes (4083 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.32 Powered by Forge 12.18.1.2011 35 mods loaded, 35 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UC	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UC	FML{8.0.99.99} [Forge Mod Loader] (forge-1.10.2-12.18.1.2011.jar) 
	UC	Forge{12.18.1.2011} [Minecraft Forge] (forge-1.10.2-12.18.1.2011.jar) 
	UC	Baubles{1.2.1.0} [Baubles] (Baubles-1.9.4-1.2.1.0.jar) 
	UC	BiomesOPlenty{4.1.0.2049} [Biomes O' Plenty] (BiomesOPlenty-1.9.4-4.1.0.2049-universal.jar) 
	UC	ExtraUtils2{1.0} [ExtraUtils2] (extrautils2-1.10.2-alpha-1.0.1.jar) 
	UC	JEI{3.7.7.233} [Just Enough Items] (jei_1.10.2-3.7.7.233.jar) 
	UC	BloodMagic{1.9.4-2.0.3-51} [Blood Magic: Alchemical Wizardry] (BloodMagic-1.9.4-2.0.3-51.jar) 
	UC	Botania{r1.8-312} [Botania] (Botania-unofficial.r1.8-312.jar) 
	UC	Chameleon{1.9.4-2.1.6} [Chameleon] (Chameleon-1.9.4-2.1.6.jar) 
	UC	chisel{MC1.9.4-0.0.6.33} [Chisel] (Chisel-MC1.9.4-0.0.6.33.jar) 
	UC	chiselsandbits{11.5} [Chisels & Bits] (chiselsandbits-11.5.jar) 
	UC	endercore{1.10.2-0.4.1.41-beta} [EnderCore] (EnderCore-1.10.2-0.4.1.41-beta.jar) 
	UC	Waila{1.7.0} [Waila] (Waila-1.7.0-B3_1.9.4.jar) 
	UC	EnderIO{1.10.2-3.0.1.73_beta} [Ender IO] (EnderIO-1.10.2-3.0.1.73_beta.jar) 
	UC	EnderZoo{1.10-1.2.3.43} [Ender Zoo] (EnderZoo-1.10-1.2.3.43.jar) 
	UC	inventorytweaks{1.61-58-a1fd884} [Inventory Tweaks] (InventoryTweaks-1.61-58.jar) 
	UC	IronChest{7.0.7.795} [Iron Chest] (ironchest-1.10.2-7.0.7.795.jar) 
	UC	journeymap{1.10.2-5.2.4} [JourneyMap] (journeymap-1.10.2-5.2.4-unlimited.jar) 
	UC	mantle{1.10-0.10.3.jenkins156} [Mantle] (Mantle-1.10-0.10.3.jar) 
	UE	Mekanism{9.1.0} [Mekanism] (Mekanism-1.10.2-9.1.0.283.jar) 
	UE	MekanismGenerators{9.1.0} [MekanismGenerators] (MekanismGenerators-1.10.2-9.1.0.283.jar) 
	UC	Quark{beta-46} [Quark] (Quark-beta-46.jar) 
	UC	randomthings{3.7.4} [Random Things] (RandomThings-MC1.10-3.7.4.jar) 
	UC	reborncore{2.5.5.52} [RebornCore] (RebornCore-1.9.4-2.5.5.52-universal.jar) 
	UC	reborncore-mcmultipart{2.5.5.52} [reborncore-MCMultiPart] (RebornCore-1.9.4-2.5.5.52-universal.jar) 
	UC	xreliquary{1.10.2-1.3.2.423} [Reliquary] (Reliquary-1.10.2-1.3.2.423.jar) 
	UC	reptilemod{3.5.2} [Reptile Mod] (reptilemod-1.10.2-3.5.2-56.jar) 
	UC	rftools{5.06} [RFTools] (rftools-1.10-5.06.jar) 
	UC	rftoolsdim{4.30beta46} [RFTools Dimensions] (rftoolsdim-1.10-4.30beta46.jar) 
	UC	Roguelike{1.5.4} [Roguelike Dungeons] (RoguelikeDungeons-1.10.2-1.5.4.jar) 
	UC	StorageDrawers{1.9.4-3.2.1} [Storage Drawers] (StorageDrawers-1.9.4-3.2.1.jar) 
	UC	supercraftingframe{1.2.0.85} [Super Crafting Frame] (supercraftingframe-1.10.2-1.2.0.85.jar) 
	UC	tconstruct{1.10-2.3.3a.jenkins271} [Tinkers' Construct] (TConstruct-1.10-2.3.3a.jar) 
	UC	techreborn{1.3.4.11} [TechReborn] (TechReborn-1.10.2-1.3.4.11-universal.jar) 
	Loaded coremods (and transformers): 
LoadingPlugin (RandomThings-MC1.10-3.7.4.jar)
  lumien.randomthings.asm.ClassTransformer
EnderCorePlugin (EnderCore-1.10.2-0.4.1.41-beta.jar)
  com.enderio.core.common.transform.EnderCoreTransformer
LoadingPlugin (Quark-beta-46.jar)
  vazkii.quark.base.asm.ClassTransformer
FMLPlugin (InventoryTweaks-1.61-58.jar)
  invtweaks.forge.asm.ContainerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.5.13416 Compatibility Profile Context 15.300.1025.0' Renderer: 'AMD Radeon HD 7600 Series'
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- chiselsandbitsIntegration (Enabled/Not Forced)
		- WailaIntegration (Enabled/Not Forced)

**Comment by aidancbrady** [comment] 2016-07-20 00:52
Fixed in build 286 :)

**Closed by aidancbrady** 2016-07-20 00:52 UTC

**Comment by Wasthereonce** [comment] 2016-07-20 01:42
ok, nice job man. Love this mod

**Comment by KshAbo** [comment] 2017-04-24 11:06
My game crashes when I play mekanism.Here is the crash report:
2017-04-24 16:29:27,429 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
2017-04-24 16:29:27,434 WARN Unable to instantiate org.fusesource.jansi.WindowsAnsiOutputStream
[16:29:27] [main/INFO] [LaunchWrapper]: Loading tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:29:27] [main/INFO] [LaunchWrapper]: Using primary tweak class name net.minecraftforge.fml.common.launcher.FMLTweaker
[16:29:27] [main/INFO] [LaunchWrapper]: Calling tweak class net.minecraftforge.fml.common.launcher.FMLTweaker
[16:29:27] [main/INFO] [FML]: Forge Mod Loader version 12.18.3.2281 for Minecraft 1.10.2 loading
[16:29:27] [main/INFO] [FML]: Java is Java HotSpot(TM) 64-Bit Server VM, version 1.8.0_111, running on Windows 10:amd64:10.0, installed at C:\Program Files\Java\jre1.8.0_111
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName0(Native Method)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at java.lang.Class.forName(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:29:27] [main/INFO] [STDERR]: [net.minecraftforge.fml.relauncher.FMLLaunchHandler:setupHome:106]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 23 more
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[16:29:27] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 25 more
[16:29:27] [main/ERROR] [FML]: An error occurred trying to configure the minecraft home at C:\Users\Meeoiba\AppData\Roaming\.minecraft for Forge Mod Loader
java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:1.8.0_111]
	at java.lang.ClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.security.SecureClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.net.URLClassLoader.defineClass(Unknown Source) ~[?:1.8.0_111]
	at java.net.URLClassLoader.access$100(Unknown Source) ~[?:1.8.0_111]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_111]
	at java.net.URLClassLoader$1.run(Unknown Source) ~[?:1.8.0_111]
	at java.security.AccessController.doPrivileged(Native Method) ~[?:1.8.0_111]
	at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_111]
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.Class.forName0(Native Method) ~[?:1.8.0_111]
	at java.lang.Class.forName(Unknown Source) ~[?:1.8.0_111]
	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564) ~[forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425) ~[forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255) ~[forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102) [forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79) [forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41) [forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138) [forge-1.10.2-12.18.3.2281.jar:?]
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115) [launchwrapper-1.12.jar:?]
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28) [launchwrapper-1.12.jar:?]
Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 23 more
Caused by: java.lang.NullPointerException
	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182) ~[launchwrapper-1.12.jar:?]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_111]
	... 23 more
Exception in thread "main" [16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: java.lang.NoClassDefFoundError: cpw/mods/fml/relauncher/IFMLLoadingPlugin
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass1(Native Method)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.defineClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.SecureClassLoader.defineClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.defineClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.access$100(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader$1.run(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.security.AccessController.doPrivileged(Native Method)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.net.URLClassLoader.findClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:117)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName0(Native Method)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.Class.forName(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.loadCoreMod(CoreModManager.java:564)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.discoverCoreMods(CoreModManager.java:425)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.CoreModManager.handleLaunch(CoreModManager.java:255)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupHome(FMLLaunchHandler.java:102)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.setupClient(FMLLaunchHandler.java:79)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.relauncher.FMLLaunchHandler.configureForClientLaunch(FMLLaunchHandler.java:41)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraftforge.fml.common.launcher.FMLTweaker.injectIntoClassLoader(FMLTweaker.java:138)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.launch(Launch.java:115)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: Caused by: java.lang.ClassNotFoundException: cpw.mods.fml.relauncher.IFMLLoadingPlugin
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:191)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	at java.lang.ClassLoader.loadClass(Unknown Source)
[16:29:28] [main/INFO] [STDERR]: [java.lang.ThreadGroup:uncaughtException:-1]: 	... 23 more
[16:29:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: Caused by: java.lang.NullPointerException
[16:29:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	at net.minecraft.launchwrapper.LaunchClassLoader.findClass(LaunchClassLoader.java:182)
[16:29:28] [main/INFO] [STDERR]: [java.lang.Throwable:printStackTrace:-1]: 	... 25 more




Pls Help.
