### ISSUE TITLE
[1.12.2] Constant Console Spam mekanism.common.tile.TileEntityQuantumEntangloporter<snip>removal without registration

### ISSUE THREAD

**Issue by Morpheus1101** [aidancbrady/Mekanism#4974] opened 2018-03-15 08:50 UTC
The below lines and ones identical but another machine are continually spammed on the server console, this relates to #4874  & #4955 All machines listed when it spams the message quite frequently, exist in the locations specified & majority of the entire base is powered from an Entangloporter

Forge v*.2.2625
IC2 v2.8.54-112
Mekanism v9.4.3.330

[19:28:21] [ic2-poolthread-1/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityQuantumEntangloporter@76110a89 (dim 0: 2601/84/-1074) removal without registration

[19:28:21] [ic2-poolthread-1/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityQuantumEntangloporter@54e0f1e (dim 0: 2625/77/-1054) removal without registration

**Comment by thiakil** [comment] 2018-03-16 01:40
@sfPlayer1 can you offer any help with this? As far as we can tell, we only register and de-register once

https://github.com/aidancbrady/Mekanism/blob/master/src/main/java/mekanism/common/tile/prefab/TileEntityElectricBlock.java#L59

**Comment by sfPlayer1** [comment] 2018-03-16 05:10
The check is unsafe, IC2 doesn't process additions/removals immediately to work around various TE lifecycle issues. This should work without trickery on your side.

**Comment by Morpheus1101** [comment] 2018-03-17 09:03
i've noticed this occuring in server startup as well, not sure if it has any bearing on anything:

[18:55:42] [Server thread/INFO] [FML/]: The mod mekanism has attempted to allocate a chunkloading ticket beyond it's currently allocated maximum: 200

**Comment by thiakil** [comment] 2018-03-17 10:28
hmm, how many mek blocks with Anchor upgrades do you have in that world?

**Comment by Morpheus1101** [comment] 2018-03-17 10:31
I couldnt even start to guess .. i know 1 base is practically completely powered by it, a handful of quarries and who knows how many other ppl r using them

**Comment by thiakil** [comment] 2018-03-17 10:33
Seems like someone is spamming the upgrades (the miner/teleporter/entangloporter doesnt chunkload unless it has that updgrade)

Currently it uses generic per-mod tickets rather than per-user-profile tickets, so you'd have to increase the number in the forge config.

**Comment by Morpheus1101** [comment] 2018-03-17 10:36
Quite a lot of entangloporter's are being used

**Comment by Morpheus1101** [comment] 2018-03-19 09:46
Any further information on this at all?

**Comment by Tollainmear** [comment] 2018-03-19 11:05
emmm has the same problem as that.
as far as I know, this problem might cause by chunk unload on server, I have installed mek  with IC2 on a personal server with my friend, and the spam message was appeared while chunk, which contains mek blocks, was unloaded.
something seems like should be registed to removed while chunk unloading and registed to be active while chunk loading?
I'm not sure, is that the rule(or problem) of IC2? 😅

**Comment by Morpheus1101** [comment] 2018-03-19 11:33
IC2 has been made aware of the issue

**Comment by Tollainmear** [comment] 2018-03-19 12:15
whooops, hope fix that soon XD

**Comment by sfPlayer1** [comment] 2018-03-19 19:05
The immediate cause is most likely the linked Mekanism code, nothing in IC2. It's quite likely that the previous registration still hangs in IC2's queue if chunks get reloaded, so getTile doesn't reflect the addition yet. Coupling the ENet (de-)registrations to the TE lifecycle (onLoad, onChunkUnload, invalidate) should be all that's needed.

**Comment by Morpheus1101** [comment] 2018-03-20 09:34
Guess i'll just wait for an update at some point :D

**Comment by thiakil** [comment] 2018-03-24 07:38
try this build http://maven.thiakil.com/mekanism/Mekanism/1.12.2-9.4.4.0ab57d0/

**Comment by Morpheus1101** [comment] 2018-03-24 09:18
Still getting the spam using this version

**Comment by thiakil** [comment] 2018-04-15 05:28
@sfPlayer1 the linked build in my post above only calls the register/deregister on lifecycle events (no special checks) yet Morpheus appears to still be getting the problem

And the issue was closed on your tracker with absolutely no useful comment.

**Comment by Morpheus1101** [comment] 2018-04-15 08:34
I have a local copy of the server, so i can run a new instance with newer logs quite easily and happy to provide them.

**Comment by TomTheHero** [comment] 2018-04-15 18:30
I got this issue aswell, and upo nstarting my server this spams the console: 
15.04 14:29:22 [Server] Server thread/WARN [ic2.EnergyNet]: Tile mekanism.generators.common.tile.TileEntitySolarGenerator@4ab0cf9f (dim 2: 35/255/34) was unloaded in grid update (ADDITION)

**Comment by Morpheus1101** [comment] 2018-04-21 21:15
Here is the log with the logging debug from thiakill's mekanism file

https://gist.github.com/Morpheus1101/127d2c2242ba99954cc346d7894d82b6

Basically you see a lot of this occuring:

`[07:08:58] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@75406943 (dim 0: -899/69/1238) removal without registration
[07:08:58] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@69918b59 (dim 0: -899/69/1239) removal without registration
[07:08:58] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@1649820e (dim 0: -899/69/1237) removal without registration
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[07:09:42] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[07:09:42] [ic2-poolthread-3/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@24df7bac (dim 0: -899/69/1238) removal without registration
[07:09:42] [ic2-poolthread-3/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@6387ce2b (dim 0: -899/69/1239) removal without registration
[07:09:42] [ic2-poolthread-3/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@652b22a2 (dim 0: -899/69/1237) removal without registration`

**Comment by sfPlayer1** [comment] 2018-04-22 05:32
It's odd that it logs invalidate() invocations. MC calls invalidate only when a block was removed/replaced, not for chunk unloads.

The logging from Mekanism unfortunately doesn't contain the position, so I can't correlate it properly with other messages. Please add it, using the same format as IC2 to make ctrl+f work.

For IC2 the config setting debug/logEnetApiAccesses appears to be disabled. It logs right at the API edge, making issues easier to dissect.

**Comment by thiakil** [comment] 2018-04-22 06:06
Yeah I realised that after I saw the log myself, I've since sent Morpheus a build that will include the instance identity code the same way ic2 displays it

**Comment by Morpheus1101** [comment] 2018-04-22 07:00
With the new code form thiakill and the config change in IC2, re-ran the server and the full outout log is @ https://gist.github.com/Morpheus1101/127d2c2242ba99954cc346d7894d82b6 (updated with current information)

Brief snippet is:

> [16:50:41] [ic2-poolthread-4/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@66215f22 (dim 0: -899/69/1238) removal without registration
[16:50:41] [ic2-poolthread-4/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@60da08b3 (dim 0: -899/69/1239) removal without registration
[16:50:41] [ic2-poolthread-4/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@69e1010e (dim 0: -899/69/1237) removal without registration
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onChunkUnload
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate
[16:51:26] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister
[16:51:26] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@16dea7df (dim 0: -899/69/1238) removal without registration
[16:51:26] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@10a43b55 (dim 0: -899/69/1239) removal without registration
[16:51:26] [ic2-poolthread-2/WARN] [ic2.EnergyNet]: Tile mekanism.common.tile.TileEntityFactory@4dbeaae1 (dim 0: -899/69/1237) removal without registration

**Comment by Morpheus1101** [comment] 2018-04-22 07:11
-899/69/1237 is a Basic Enriching Factory
 -899/69/1239 is a Basic Smelting Factory
-899/69/1238 is a Basic Infusing factory

All of the machines are powered using DraconicEvolution as seen below by connecting a DE Wyvern Wierless Energy Crystal directly to the machines without using any osrt of Conduits, pipes or anything else.

![2018-04-22_17 09 38](https://user-images.githubusercontent.com/10524952/39092385-f8b1c95c-464f-11e8-832d-8fd0d4ee13b3.png)

**Comment by thiakil** [comment] 2018-04-22 07:32
Something is definitely weird about your setup
```
[17:16:31] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad @2ae554e
[17:16:31] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register @2ae554e
[17:16:31] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate @2ae554e
```

`invalidate` shouldnt be called less than 1 second after onLoad...

**Comment by sfPlayer1** [comment] 2018-04-22 10:52
Please also upload the matching debug.log (or fml-server-latest.log for old Forge), IC2 logs the API accesses with too low severity to show up in the regular log.

Assuming Mekanism does ENet unregistrations from invalidate, we may be able to obtain a stack trace by turning debug/logEnetApiAccessTraces on. Very curious what the cause is there..

**Comment by thiakil** [comment] 2018-04-22 10:54
We're currently trying to work that out. Seems related to coremods unfortunately

```
[17:59:00] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.deregister @24b7ac97
[17:59:00] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.onLoad @40bcc7bb
[17:59:00] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.register @40bcc7bb
[17:59:00] [Server thread/INFO] [Mekanism]: TileEntityElectricBlock.invalidate @40bcc7bb
java.lang.Exception: null
        at mekanism.common.tile.prefab.TileEntityElectricBlock.func_145843_s(TileEntityElectricBlock.java:169) [TileEntityElectricBlock.class:?]
        at net.minecraft.world.chunk.Chunk.func_177426_a(Chunk.java:830) [axw.class:?]
        at net.minecraft.world.World.func_72939_s(World.java:1888) [amu.class:?]
        at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:765) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]
```

**Comment by Morpheus1101** [comment] 2018-04-22 10:57
So far im about half way through the list of coremods to determine which is the cause

**Comment by sfPlayer1** [comment] 2018-04-22 10:59
Not necessarily/unlikely, the loop processing addedTileEntityList is probably doing this. The obvious question is why TEs with conflicting positions are in that list.

Deobf stack trace:

```
java.lang.Exception: null
        at mekanism.common.tile.prefab.TileEntityElectricBlock.invalidate(TileEntityElectricBlock.java:169) [TileEntityElectricBlock.class:?]
        at net.minecraft.world.chunk.Chunk.addTileEntity(Chunk.java:830) [axw.class:?]
        at net.minecraft.world.World.updateEntities(World.java:1888) [amu.class:?]
        at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
        at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:765) [MinecraftServer.class:?]
        at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
        at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_171]<input>
```

**Comment by sfPlayer1** [comment] 2018-04-22 11:03
It may be the best approach to inject a list wrapper (abstract list/collection delegating to what was there before) in addedTileEntityList that logs whenever it encounters a TE with one of the interesting positions.

**Comment by thiakil** [comment] 2018-04-22 11:08
Removing all the coremods appeared to alleviate the problem, that's why we think that ;)

**Comment by Morpheus1101** [comment] 2018-04-22 12:14
This is the list of Coremods total:

> WARNING: coremods are present:
  CTMCorePlugin (CTM-MC1.12-0.2.3.12.jar)
  EnderCorePlugin (EnderCore-1.12.2-0.5.20.jar)
  LibLoader (# LibLoader.jar)
  OpenModsCorePlugin (OpenModsLib-1.12.2-0.11.5.jar)
  AstralCore (astralsorcery-1.12.2-1.8.5.jar)
  LoadingPlugin (Quark-r1.4-123.jar)
  Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  CoreMod (TickProfiler-1.12-0.0.4.jar)
  LoadingPlugin (ResourceLoader-MC1.12.1-1.5.3.jar)
  LoadingPlugin (RandomThings-MC1.12.2-4.1.5.jar)
  CoreMod (Aroma1997Core-1.12.2-2.0.0.0.b148.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)
  IvToolkit (IvToolkit-1.3.3-1.12.jar)
  IELoadingPlugin (ImmersiveEngineering-0.12-80-core.jar)
  SecretRoomsMod-Core (secretroomsmod-1.12.2-5.6.2.jar)

This is whats left so far untested:

> WARNING:
 coremods are present:
   Do not report to Forge! Remove FoamFixAPI (or replace with FoamFixAPI-Lawful) and try again. (foamfix-0.9.7-1.12.2-anarchy.jar)
  Plugin (NotEnoughIDs-1.5.4.2.jar)
  HammerCoreCore (HammerCore-1.12.2-1.9.9.1.jar)
  MalisisCorePlugin (malisiscore-1.12.2-6.4.0.jar)
  ShetiPhian-ASM (shetiphiancore-1.12.0-3.5.6.jar)
  FMLPlugin (elulib-0.1.12.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.64-dev.jar)
  ForgelinPlugin (Forgelin-1.6.0.jar)
  TransformerLoader (OpenComputers-MC1.12.2-1.7.2.67.jar)

**Comment by Morpheus1101** [comment] 2018-04-22 13:37
NotEnoughIDS is only mod left and the spam continued and being what the mod does i cant see it being responsible

**Comment by Morpheus1101** [comment] 2018-04-23 04:13
Traced it down with help from thiakill to be CompactMachines thats the cause, whilst the spam still occurs when the world 1st initially loads, subsequent spam does not occur

**Comment by thiakil** [comment] 2018-04-23 06:39
In at least one case it appears to be a ghostloading issue caused by Draconic

```
at mekanism.common.tile.prefab.TileEntityElectricBlock.readFromNBT(TileEntityElectricBlock.java:182) [TileEntityElectricBlock.class:?]
at mekanism.common.tile.prefab.TileEntityMachine.readFromNBT(TileEntityMachine.java:158) [TileEntityMachine.class:?]
at mekanism.common.tile.TileEntityFactory.readFromNBT(TileEntityFactory.java:787) [TileEntityFactory.class:?]
at net.minecraft.tileentity.TileEntity.create(TileEntity.java:120) [avj.class:?]
at net.minecraft.world.chunk.storage.AnvilChunkLoader.loadEntities(AnvilChunkLoader.java:494) [aye.class:?]
at net.minecraftforge.common.chunkio.ChunkIOProvider.syncCallback(ChunkIOProvider.java:97) [ChunkIOProvider.class:?]
at net.minecraftforge.common.chunkio.ChunkIOExecutor.syncChunkLoad(ChunkIOExecutor.java:94) [ChunkIOExecutor.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:118) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.loadChunk(ChunkProviderServer.java:89) [on.class:?]
at net.minecraft.world.gen.ChunkProviderServer.provideChunk(ChunkProviderServer.java:135) [on.class:?]
at net.minecraft.world.World.getChunkFromChunkCoords(World.java:309) [amu.class:?]
at net.minecraft.world.World.getChunkFromBlockCoords(World.java:304) [amu.class:?]
at net.minecraft.world.World.getTileEntity(World.java:2396) [amu.class:?]
at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalBase.balanceLinkedDevices(TileCrystalBase.java:120) [TileCrystalBase.class:?]
at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalBase.update(TileCrystalBase.java:93) [TileCrystalBase.class:?]
at com.brandon3055.draconicevolution.blocks.energynet.tileentity.TileCrystalDirectIO.update(TileCrystalDirectIO.java:42) [TileCrystalDirectIO.class:?]
at net.minecraft.world.World.updateEntities(World.java:1832) [amu.class:?]
at net.minecraft.world.WorldServer.updateEntities(WorldServer.java:613) [oo.class:?]
at net.minecraft.server.MinecraftServer.updateTimeLightAndEntities(MinecraftServer.java:765) [MinecraftServer.class:?]
at net.minecraft.server.dedicated.DedicatedServer.updateTimeLightAndEntities(DedicatedServer.java:396) [nz.class:?]
at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:666) [MinecraftServer.class:?]
at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:524) [MinecraftServer.class:?]
```

**Comment by TomTheHero** [comment] 2018-04-23 19:37
I don't have Compactmachines or Draconic and i get the error o nboth the initial world load and whenever an area with those problematic machines is loaded

**Comment by sfPlayer1** [comment] 2018-04-23 19:48
TileEntity.invalidate() should never get invoked unless the block was actually mined up (very unusual deliberate corner cases aside). invalidate is not the direct opposite of validate, the pair is really validate vs (invalidate XOR onChunkUnload).

**Comment by thiakil** [comment] 2018-04-24 07:41
I think I've worked it out, and is potentially a Forge caused bug.

Forge sets `net.minecraft.world.World#processingLoadedTiles` to true *before* ticking TEs starts, so if a chunk is loaded by a ticking TE, the TEs that get added to the world by the chunk/chunkProvider go into the `addedTileEntityList` list and then processed further down. 

During that processing it gets sent back to the Chunk's `addTileEntity` which sees that there is already a TE there, and so `invalidate`s it (as there seems to be no instance check).

It does then  `validate()` it though. So I guess we could do the IC2 message there instead of onLoad.

All the stacktraces Morpheus have shown me that Mek's calls to IC2 eNet registration are balanced out with de-registration however, so I'm stumped as to why IC2 is complaining (I'm sure I remember seeing code that handled a pending reg being cancelled).

**Comment by thiakil** [comment] 2018-04-24 10:40
@TomTheHero Any mod can trigger the edge case.

To all with this problem: It would appear we have solved the underlying issue, and it will be in the next release. When that is I cannot say. In the meantime, you will need to use a chunkloader on the affected positions.

**Comment by TomTheHero** [comment] 2018-04-25 13:09
It would be great if mekanism changelogs were available

**Closed** 2018-04-26 04:26 UTC
Labels: Fixed in dev

**Comment by Morpheus1101** [comment] 2018-04-26 04:43
Thanks to all for workin on this and after a long effort an debugging, knocked this one off the bug list, much appreciated
