### ISSUE TITLE
Rendering Issue with 5x ore processing setup

### ISSUE THREAD

**Issue by miksbricks** [aidancbrady/Mekanism#4066] opened 2016-12-16 02:01 UTC
Having rendering issues with all types of pipes - at least elite and ultimate. 
![render1](https://cloud.githubusercontent.com/assets/24597748/21248063/72934720-c2f1-11e6-9b6c-8980271dab06.JPG)
![render2](https://cloud.githubusercontent.com/assets/24597748/21248062/7291f62c-c2f1-11e6-8f3f-038b388ecad4.JPG)

Should render ultimate mechanical pipes but it doesn't. Water is flowing through pipes into evaporation unit the pipes are just not rendering.
![render3](https://cloud.githubusercontent.com/assets/24597748/21248060/728f7456-c2f1-11e6-87bc-3ac64b8dfcc3.JPG)
![render4](https://cloud.githubusercontent.com/assets/24597748/21248061/729099bc-c2f1-11e6-8a06-a5dd91ba2e3f.JPG)

Running the Hermitpack 1.5.1 release which has Mekanism 9.2.1, Mekanism tools 9.2.1 and Mekanism Generators 9.2.1

**Comment by jburrows82** [comment] 2016-12-16 19:12
Are you using Optifine?

**Comment by thommy101** [comment] 2016-12-16 20:28
You're not the only one. I've just made my 5* ore processing and also all my pressurised pipes are not displaying. It's not only Mekanism, but also some ender io conduits not showing. 
Everything works as supposed. 
Using a custom build version from the current (16 December) 1.10 branch, without optifine. 

Mod list and Screenshot will follow soon.

**Comment by thommy101** [comment] 2016-12-24 18:07
@miksbricks, do you have a client and server log of this when it happens?

Posting the logs of mine (and screenshots):
Clientlog, serverlog, modlist
https://gist.github.com/thommy101/995fa39fbf44eb8d46d8a3eb141087cc

Screenshots
http://imgur.com/a/RsDsT

Keep in mind, my logs also contains stuff of EnderIO, as it also has a render issue ( SleepyTrousers/EnderIO#3910 )

**Comment by HenryLoenwind** [comment] 2016-12-24 20:43
If that is the same as the one reported earlier, the rendering problem is caused by the TileEntities on the client-side not having any data.I have no idea what stops them from being synced.

**Comment by thommy101** [comment] 2016-12-24 20:53
Looking at my log, I've found a bug in Mekanism regarding tile entities at line 219 (IllegalStateException) . Maybe it prevents any other tile entity to send it's data to the client.
I'll take a look if it can be reproduced easily and solve it if possible.

**Comment by thommy101** [comment] 2016-12-27 18:25
Did some digging, somehow the facing of a machine (in my instance a resistive heater) changes from north to down. The clientfacing (I assume this is used for rendering) stays the correct value. Mekanism tries to get the left and right of the current facing to get the input and output. This fails when given an facing of up or down, causing an IllegalStateException to be thrown.

Modifying it so that in case of mismatch it uses client render solves the issue, but it's not a nice and clean solution. Best solution is to find out where the wrong facing is coming from and fix that.

I'll let you all know if I find a cause of it.

**Comment by miksbricks** [comment] 2017-01-13 19:40
Sorry - No I am not using Optifine. I don't have logs that far back.

**Comment by thommy101** [comment] 2017-03-24 15:53
This should be fixed when #4184 is redone and merged.

**Closed** 2017-03-29 17:28 UTC
