### ISSUE TITLE
EnergyNetwork malfunction

### ISSUE THREAD

**Issue by halvors** [aidancbrady/Mekanism#2474] opened 2015-04-05 12:43 UTC
I'm expriencing that some EnergyNetworks seems to be malfunctioning.

They just drain all the energy available and if you see the video it seems that the "Needed" value is negative even when there is no devices connected to it.

Here is the video: https://www.youtube.com/watch?v=gAEXbMn076c

**Comment by OldEnt** [comment] 2015-04-05 14:46
Have exactly the same issue when extracting power from Thermal Expansion energy cells. Replacing (ultimate) cables helps temporarily. Funnily, the bug later reappears in the same spot. 

Power _appears_ to be drained independely from target machine demand until source is depleted.

This reminds me of faulty TE power conduits issue...

Forge 10.13.2.1291
[quote]
 1.7.10_AM2-1.4.0.008.jar
AnimationAPI-1.7.10-1.2.4.jar
appliedenergistics2-rv1-stable-1.jar
backpack-2.0.1-1.7.x.jar
BetterTitleScreen-1.7.10-1.1.jar
BiblioCraft[v1.10.2][MC1.7.10].jar
BigReactors-0.4.2A2.jar
BiomesOPlenty-1.7.10-2.1.0.1174-universal.jar
buildcraft-6.4.7.jar
Carpenter's Blocks v3.3.5 - MC 1.7.10.jar
Chisel-1.7.10-1.5.7.jar
CodeChickenCore-1.7.10-1.0.4.29-universal.jar
CoFHCore-[1.7.10]3.0.0RC7-211.jar
CraftHeraldry 1.1.3.jar
CustomMobSpawner 3.3.0.zip
DragonMounts-r41-1.7.10.jar
DrZharks MoCreatures Mod v6.3.1.zip
Emotes 1.0.1.jar
EnderIO-1.7.10-2.2.8.367.jar
EnderStorage-1.7.10-1.4.5.27-universal.jar
ExtraCells-1.7.10-2.1.37b62.jar
extrautilities-1.2.3.jar
forestry_1.7.10-3.4.0.7.jar
Galacticraft-Planets-1.7-3.0.11.306.jar
GalacticraftCore-1.7-3.0.11.306.jar
Hats-4.0.1.jar
HatStand-4.0.0.jar
iChunUtil-4.2.1.jar
InventoryTweaks-1.58-147.jar
ironchest-1.7.10-6.0.62.742-universal.jar
Jabba-1.2.1a_1.7.10.jar
liteloader-1.7.10.jar
Mantle-1.7.10-0.3.2.jar
Mekanism-1.7.10-8.1.0.215.jar
MekanismGenerators-1.7.10-8.1.0.215.jar
MekanismTools-1.7.10-8.1.0.215.jar
MicdoodleCore-1.7-3.0.11.306.jar
MineFactoryReloaded-[1.7.10]2.8.0RC8-86.jar
ModularPowersuits-0.11.0.178.jar
Morph-Beta-0.9.1.jar
MrCrayfishFurnitureModv3.4.7(1.7.10).jar
mystcraft-1.7.10-0.11.2.01.jar
natura-1.7.10-2.2.0.1.jar
NetherOres-[1.7.10]2.3.0RC4-4.jar
NotEnoughCodecs-1.7.10-0.3-snapshot-13.jar
NotEnoughItems-1.7.10-1.0.4.83-universal.jar
Numina-0.4.0.100.jar
OpenBlocks-1.7.10-1.3.jar
OpenModsLib-1.7.10-0.6.jar
OptiFine_1.7.10_HD_B5.jar
Pam's HarvestCraft 1.7.10g.jar
Pam's WeeeFlowers 1.7.2b.zip
ProjectRed-1.7.10-4.5.15.75-Base.jar
Railcraft_1.7.10-9.5.0.0.jar
RedstoneArsenal-[1.7.10]1.1.0RC7-65.jar
Reliquary-1.2.jar
slick-util.jar
TConstruct-1.7.10-1.8.3b.jar
Thaumcraft-1.7.10-4.2.3.5.jar
ThaumicTinkerer-2.5-1.7.10-163.jar
ThermalExpansion-[1.7.10]4.0.0RC7-141.jar
ThermalFoundation-[1.7.10]1.0.0RC7-62.jar
ThermalSmeltery-1.7.10-1.1.2.jar
 TMechworks-1.7.10-0.2.14.100.jar
twilightforest-1.7.10-2.3.5.jar
Waila-1.5.10_1.7.10.jar
Wawla-1.1.1_1.7.10.jar
weaponmod-1.14.2.jar
[1.7.10]ArmorStatusHUD-client-1.28.jar
[1.7.10]CrystalWing-universal-1.7.10.r02.jar
[1.7.10]DamageIndicatorsMod-3.2.3.jar
[1.7.10]StatusEffectHUD-client-1.27.jar
[1.7.10]Treecapitator-universal-2.0.4.jar
[1.7.10]WorldStateCheckpoints-client-1.7.10.r03.jar

/1.7.10/[1.7.10]bspkrsCore-universal-6.16.jar
/1.7.10/Baubles-1.7.10-1.0.1.10.jar
/1.7.10/CodeChickenLib-1.7.10-1.1.1.110-universal.jar
/1.7.10/ForgeMultipart-1.7.10-1.1.1.320-universal.jar
/1.7.10/LibSandstone-1.0.0.jar
/1.7.10/MrTJPCore-1.7.10-1.0.5.11-universal.jar
[/quote]

**Comment by Maxiebyte** [comment] 2015-04-05 15:06
@OldEnt GitHub doesn't use BBCode.
Try
\`\`\`
(Insert things to quote here)
\`\`\`
That will result in
```
(Insert things to quote here)
```

**Comment by OldEnt** [comment] 2015-04-05 15:07
Probably related to build #202 no. 21 issue? http://ci.indiewikis.com:8080/job/Mekanism/changes

As stated above I got 215 build.

https://github.com/aidancbrady/Mekanism/commit/07d0c2bfc17e1e0dfc74d513c2563a3379cacb7b

**Comment by aidancbrady** [comment] 2015-04-10 12:29
May be fixed with the new network overhaul.  Those with dev server access, mind doing testing on this issue?

**Comment by themechman** [comment] 2015-04-10 14:44
Just updated mods and unfortunately, I must confirm that the cables are draining power and not transferring it.

**Comment by halvors** [comment] 2015-04-10 21:21
@aidancbrady It's still bugged. More than before. Now cables with nothing connected to them is draining my energy cube even when i make a new network.

**Comment by unpairedbracket** [comment] 2015-04-10 22:14
What are they saying if you network reader them?

**Comment by halvors** [comment] 2015-04-10 22:24
Basically that there is energy buffered. But when the energy cube empties there is no buffer anymore, (0 J)

**Comment by halvors** [comment] 2015-04-10 22:25
Seems to be random, when i place it somewhere it seems to work. But old networks are still bugged. Is there possible that there is invisible bugged ghost networks that the new places ones is "connected" to?

**Comment by unpairedbracket** [comment] 2015-04-10 22:37
I'll try something, let me know if the next build fixes this.

**Comment by halvors** [comment] 2015-04-10 23:38
@unpairedbracket  It's not negative when using the network reader. Obviously since you added a check for that. But not sure if this solves the drain issue, need to do some more testing :)

But good job so far, thanks :)

**Comment by halvors** [comment] 2015-04-11 12:04
@unpairedbracket Instead of buffer being negative it's now being 0 J no matter how much energy it drains from my storage.

**Comment by unpairedbracket** [comment] 2015-04-11 12:20
That's... Odd. I can't reproduce in testing - what kinds of storage are you using here? Pure Mekanism, or is there IC2 or RF mixed in there too?

**Comment by NitroxydeX** [comment] 2015-04-11 12:54
Check into this thread. Can reproduce this problem. This is really strange and only happens to cables that got placed BEFORE the rewrite of the Code. And what is also strange: Without anything connected to it it "dumps" the energy. 

![2015-04-11_14 48 09](https://cloud.githubusercontent.com/assets/9305576/7101435/96e8a898-e05a-11e4-96fd-0bd1bdf04ff5.png)

**Comment by unpairedbracket** [comment] 2015-04-11 13:17
It's saying:
```
Transmitters: 12
Acceptors: 13
```
Is this accurate; are there 13 non-cable things connected to the network? If so what are they?

**Comment by NitroxydeX** [comment] 2015-04-11 13:20
Nothing! Thats the Thing that is strange. :D

**Comment by unpairedbracket** [comment] 2015-04-11 13:24
Hmm, so it's an issue with the acceptor system. Do you happen to have any other mods installed that ship the Mekanism API (Likely candidates EnderIO and Galacticraft)? If so, can you remove the "mekanism" folders from their jars, and let me know what happens?

**Comment by NitroxydeX** [comment] 2015-04-11 13:31
Mh, yeah we have EnderIO. I dont know which other mods ships the Mekanism API. Have to check all 164 :D

**Comment by unpairedbracket** [comment] 2015-04-11 13:34
If you send the world files to me (link on Dropbox or Drive or something), and give me the coordinates of an affected network I'll take a look at it?

**Comment by NitroxydeX** [comment] 2015-04-11 13:34
you would need the whole modpack and the map is about 2gigabytes?! :D

**Comment by unpairedbracket** [comment] 2015-04-11 13:39
Ok, that might not work. I was looking to test with only Mekanism installed, to work out whether it's an interaction or not. If you have enough disk space to back up the world, you could try doing that yourself - back up the world, then load it up with only Mekanism and try the network reader again? If not there's not much else I can suggest to help.

**Comment by NitroxydeX** [comment] 2015-04-11 13:47
EnderIO is the only mod that ships the Mekanism API in our Modpack. Removed the folder. Nothing changed.

**Comment by unpairedbracket** [comment] 2015-04-11 13:52
Well, I'm out of ideas on this issue then. @halvors, are you experiencing the same behaviour, or is the issue you're having different in any way?

**Comment by NitroxydeX** [comment] 2015-04-11 13:52
Will perform a backup, delete all mods except Mekanism and Biomes O'Plenty (for the biomes) and take a look at it.

**Comment by halvors** [comment] 2015-04-11 13:57
@unpairedbracket Think it's the same issue. Seems also that "pre" Mekanism 8, cables are the ones causing trouble, and maybe new cables placed where the pre Mekanism 8 used to be too.

I'm only using energy cubes and induction matrixes in the setup i'm using, i have not enderio installed.

**Comment by NitroxydeX** [comment] 2015-04-11 13:59
@halvors @unpairedbracket can't be some v8 related stuff. We had no problems with 8.0.3 (except of client crashes) cables.

**Comment by NitroxydeX** [comment] 2015-04-11 14:11
No Problems only with Mekanism. That is really strange! Nothing is connected with all mods to the Mekanism-Network but some invisible things seems to dump all the energy.

@halvors can you post a list of your mods?

@unpairedbracket http://www.technicpack.net/modpack/zockercraft.609172/mods take a look at the list. Maybe you know what Mekanism recognizes as an acceptor.

**Comment by NitroxydeX** [comment] 2015-04-11 16:39
Replaced the Whole Network. And what happend? Once I connect something to it: Same Problem again. to clarify: I attached the Induction Matrix to the Cable - before I did it, all was fine with the cables: They stored the energy and didn't dumped it into nothing. After it, the Buffer of the Network got pumped into the induction matrix and then the energy that got into the network just got dumped!

**Comment by unpairedbracket** [comment] 2015-04-11 16:58
And that's with only Mekanism?

**Comment by NitroxydeX** [comment] 2015-04-11 17:14
No. Thats with the Modpack. But it's strange, that it's only happen when I connect Mekanism-Things to it. The Cables itselfs are working fine without acceptors.

**Comment by halvors** [comment] 2015-04-11 20:14
@unpairedbracket It just draned a 5 TJ induction matrix... It's kindof unplayable...

**Comment by halvors** [comment] 2015-04-11 20:15
@unpairedbracket Thus bug must have been introduced sometime after the first v8 release and somehow gotten into your energy network rewrite?

**Comment by halvors** [comment] 2015-04-11 20:17
@unpairedbracket On our production server we use Mekanism with Applied Energistics, is Mekanism integrating AE energy units or is Applied Energistics integrating Mekanism?

**Comment by NitroxydeX** [comment] 2015-04-11 20:26
Performed a WHOLE! modpack update. Nothing changed. Mekanism Network only have problems with the energy matrix.

**Comment by themechman** [comment] 2015-04-11 20:33
Ive reverted back to 8.0.2. No issues with that version.

**Comment by NitroxydeX** [comment] 2015-04-11 20:38
We had a servercrash now... lulz.
```
Encountered an unexpected exception
java.lang.NullPointerException
        at codechicken.multipart.TMultiPart.x(TMultiPart.scala:45) ~[TMultiPart.class:?]
        at mekanism.common.multipart.MultipartTransmitter.coord(MultipartTransmitter.java:40) ~[MultipartTransmitter.class:?]
        at mekanism.api.transmitters.DynamicNetwork.updateTransmitterOnSide(DynamicNetwork.java:104) ~[DynamicNetwork.class:?]
        at mekanism.api.transmitters.DynamicNetwork.commit(DynamicNetwork.java:93) ~[DynamicNetwork.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.commitChanges(TransmitterNetworkRegistry.java:180) ~[TransmitterNetworkRegistry.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.tickEnd(TransmitterNetworkRegistry.java:97) ~[TransmitterNetworkRegistry.class:?]
        at mekanism.api.transmitters.TransmitterNetworkRegistry.onTick(TransmitterNetworkRegistry.java:87) ~[TransmitterNetworkRegistry.class:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler_633_TransmitterNetworkRegistry_onTick_ServerTickEvent.invoke(.dynamic) ~[?:?]
        at cpw.mods.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:54) ~[ASMEventHandler.class:?]
        at cpw.mods.fml.common.eventhandler.EventBus.post(EventBus.java:138) ~[EventBus.class:?]
        at cpw.mods.fml.common.FMLCommonHandler.onPostServerTick(FMLCommonHandler.java:247) ~[FMLCommonHandler.class:?]
        at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:590) ~[MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:427) [MinecraftServer.class:?]
        at net.minecraft.server.MinecraftServer$2.run(MinecraftServer.java:685) [li.class:?]
```

**Comment by unpairedbracket** [comment] 2015-04-11 22:54
I've reproduced the issue. It was a RF interaction. I will now attempt to fix the issue.

**Comment by unpairedbracket** [comment] 2015-04-11 23:40
Try build 223, it should fix both the draining and that crash you just reported.

**Comment by halvors** [comment] 2015-04-11 23:52
@unpairedbracket You think this is why Applied Energistics was draining a lot of more power than before too? Couple of MJ's per second.

**Comment by unpairedbracket** [comment] 2015-04-11 23:54
Not sure on that one - I'm not entirely sure why it would be happening

**Comment by halvors** [comment] 2015-04-11 23:54
@unpairedbracket Also see you updated the Forge version required, any reason why? I pretty sure i'm unable to update to 223 now because of this fluid change, 1365 is not a recommended build as far as i know. Why did you choose to go for that?

**Comment by unpairedbracket** [comment] 2015-04-11 23:58
Oh, whoops. Hadn't taken into account it wouldn't work with earlier forge. I will revert that change when I gave the chance

**Comment by halvors** [comment] 2015-04-12 00:00
@unpairedbracket Think there will be a recommended release pretty soon that includes the new fluid system. Maybe just create a branch for that in the meanwhile so that you don't need to redo it later :+1:

**Comment by unpairedbracket** [comment] 2015-04-12 00:03
Yeah, that sounds like a good plan. Out of interest, are there still incompatibilities between other mods and 1365 that prevent you from updating, or do you just prefer to stick to recommended builds?

**Comment by halvors** [comment] 2015-04-12 00:04
It's a lot of other mods that does not have a build for 1355+. Probatly because that is not a recommended build.

**Comment by halvors** [comment] 2015-04-12 00:45
@unpairedbracket Will this be reverted soon so that could test the solved RF issues?

**Comment by unpairedbracket** [comment] 2015-04-12 01:13
Soon yes, but it's currently 2am and I'm packing to go back to university tomorrow so it may be a little while.

**Comment by OldEnt** [comment] 2015-04-12 01:19
Just wanted to say thank you for your hard work on this. Have a good night.

**Comment by NitroxydeX** [comment] 2015-04-12 01:48
Let me talk to you as a modpack creator and administrator. As of now all our 150+ mods are working with forge 1366.

Why I considered updating? 
We're running extra utilities and the latest update needs a higher version than the recommended build.
So I think there are just a hand full of mods that are not working with 1366. We're running all cool mods the people play. So if @unpairedbracket did something that's not in 1291 but solves the network issue we have to deal with it. But maybe it's just a little failure.

**Comment by unpairedbracket** [comment] 2015-04-12 02:53
There, back to 1291. Build 224 should work with Forge pre-fluid breakage.

And @NitroxydeX, I'm just moving back in tomorrow - lectures don't start for another 2 weeks but we are going to be tested before that...

**Comment by NitroxydeX** [comment] 2015-04-12 17:29
Can confirm: 223 and 224 cables working fine.

**Comment by halvors** [comment] 2015-04-12 17:50
Indeed it seems like that. Seems the RF bug was the issue that caused the AE2 controller to drain so much power as well.

**Comment by NitroxydeX** [comment] 2015-04-12 17:51
@halvors was not the controller that drained it. the cables just not delivered the power.

**Closed** 2015-04-12 21:09 UTC

**Comment by halvors** [comment] 2015-04-13 06:53
@NitroxydeX Are you sure? Oh due to the RF issue?

**Comment by NitroxydeX** [comment] 2015-04-13 08:22
@halvors yes.
