### ISSUE TITLE
Crash on Launch for 1.11.2-9.3.4-fix

### ISSUE THREAD

**Issue by WarKittens** [aidancbrady/Mekanism#4674] opened 2017-09-04 17:37 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Crash on launch, pastebin attached at bottom. I have an absolutely monstrous amount of mods installed, so it is possible that it isn't Mekanism's issue. The main meaty part seems to be: Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:log2, it is not an allowed value.

#### Steps to reproduce:
1. Drop mod in mod folder
2. Launch Minecraft
3. Crash

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-1.11.2-13.20.1.2454
**Mekanism:** Mekanism-1.11.2-9.3.4-fix
**Other relevant version:** Minecraft 1.11.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/W3MxFsty
[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-09-04 17:50
Duplicate of #4633 

Adding this for furture reference (makes search a lot easier)
```
Caused by: java.lang.IllegalArgumentException: Cannot set property PropertyEnum{name=variant, clazz=class net.minecraft.block.BlockPlanks$EnumType, values=[acacia, dark_oak]} to oak on block minecraft:log2, it is not an allowed value
    at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177226_a(BlockStateContainer.java:235)
    at net.minecraft.block.BlockNewLog.func_176203_a(SourceFile:56)
    at com.pengu.hcmb.recipe.RecipeCutMicroblock.func_77569_a(RecipeCutMicroblock.java:51)
```

**Closed by thommy101** 2017-09-04 17:50 UTC
