### ISSUE TITLE
Able to exceed Ultimate Cable limitations

### ISSUE THREAD

**Issue by themechman** [aidancbrady/Mekanism#3349] opened 2016-06-12 03:37 UTC
The default Ultimate cable limit is 128K RF/t. I am able to push upwards of 5M through a single cable, with only one transmitter and one receiver. Was this intended or cosmetic problem?

**Comment by aidancbrady** [comment] 2016-06-12 03:45
Are you sure it is a single cable, or are there multiple cable segments connected?

**Comment by themechman** [comment] 2016-06-12 06:28
For example, I have an induction matrix with an elite provider. 1.64M RF/t. Your fusion reactor set at a rate of 2, produces 200K RF/t respectively. This by all means should exceed even the ultimate cable.

The only connections is two parallel ultimate cables to the same induction matrix. At no point does either cable touch each other, but yet I am able to push 2M RF/t through one even after breaking the redundant.

![2016-06-12_02 27 10](https://cloud.githubusercontent.com/assets/2990361/15989464/2fee7050-3045-11e6-8c94-488f682b1b4c.png)

I am able to reproduce this in single creative as well. The cable appears to have no limit established.

**Comment by HadesDurin** [comment] 2016-06-12 06:42
well mekanism uses a diffrent way to transport energy around
if you use ender io only the cable rf flow rate will be transported i believe.
i cannot exactly explain why, but mekanism handles rf completly diffrent than other mods also using RF api

**Comment by VT-14** [comment] 2016-06-13 03:53
Ender IO and most RF transfer systems are per-connection systems.  Each connection can transfer a certain amount of power in or out of the system.

Mekanism determines how much power can be transferred through the cable network by summing each cables throughput.  If you only have 1 Ultimate Cable then you can transfer 128k RF/t.  If you have 3, then you can transfer 3x128k, or 384k RF/t.  This transfer rate a limit on the entire grid.

Real world relation? No, but nor does the "per connection" model.
Strange? Yes.
Necessary? ...Have you seen the power output on a reactor?

**Comment by HadesDurin** [comment] 2016-06-13 06:22
as i said mekanism handels that diffrently and that is also the explanation why mekansims->thermal expansin crossover does not work. it also a explanation why mekanism->draconic evolution tier 7 energy storage does not work after energy pylons are full of energy.
thanks for the insight into this

**Comment by themechman** [comment] 2016-06-13 14:24
VT-14. I just blew that two cable theory out of the water with a single cable.

![2016-06-13_10 13 10](https://cloud.githubusercontent.com/assets/2990361/16010590/ee850d48-314f-11e6-875a-3057cecc3422.png)
![2016-06-13_10 13 42](https://cloud.githubusercontent.com/assets/2990361/16010597/f400eff8-314f-11e6-9959-bbb02b6cb52d.png)
![2016-06-13_10 13 52](https://cloud.githubusercontent.com/assets/2990361/16010604/fad4b738-314f-11e6-9bd3-4d79230bba19.png)

Next, I set the fuel rate to 20. I couldnt sustain that because of the simple setup, but yes. It is clear I am able to exceed a single cable's spec. I am going to check lower tier cables next to make sure this is not cascading.

I know about the per-connection limiter on TE/TF but that doesnt explain this, unless it is because of the fact that these mods are loaded along with Mek and the api is being overridden by CoFH's copy. Also the fact that galacticraft is installed may also be throwing a wrench in the works.

I'm not a coder, so dont chew me up on this one. I've just seen this before when buildcraft was still a thing.

**Comment by themechman** [comment] 2016-06-13 14:28
Uh.... You guys may want to look at this. Reactor rate is 2, which outputs about 200k RF/t.

I swap in a piece of basic cable.
![2016-06-13_10 28 02](https://cloud.githubusercontent.com/assets/2990361/16010983/94bbfc0c-3151-11e6-83c9-e00430af6409.png)
![2016-06-13_10 28 13](https://cloud.githubusercontent.com/assets/2990361/16010985/9878ecba-3151-11e6-9b92-4422f77f49b9.png)

**Comment by themechman** [comment] 2016-06-13 14:30
Replaced whole cable with basic.

![2016-06-13_10 30 33](https://cloud.githubusercontent.com/assets/2990361/16011062/e6da2248-3151-11e6-974f-49b8e0d97260.png)

**Comment by themechman** [comment] 2016-06-13 15:13
After extensive testing, with a single connection between reactor and induction cell. These are my results. Values listed in RF.

Basic:
Limit is 1.28k
Actual limit: 11.52k

Advanced:
Limit is 5.12k
Actual limit: 46.08k

Elite
Limit is 25.6k
Actual limit: 230.39k

**Comment by VT-14** [comment] 2016-06-13 18:37
*Sigh. this is something that needs explaining with pictures.

Per connection model (Ender IO). Each connection can transfer 20,480 RF/t.  I think most people understand how this works.
![20160613142910_1](https://cloud.githubusercontent.com/assets/12564251/16018696/93f9703e-3173-11e6-818d-47c006779ea8.jpg)


Here is Mekanism's way of doing it.  Each cable increases the "grid" transfer capability by 128k RF/t.

1 cable in the grid. (1 x 128k RF/t)
![20160613142921_1](https://cloud.githubusercontent.com/assets/12564251/16018724/bbc96d94-3173-11e6-8ffe-60ef355b5125.jpg)

2 cables in the grid. (2 x 128k RF/t)
![20160613142931_1](https://cloud.githubusercontent.com/assets/12564251/16018731/c1f14c0a-3173-11e6-9e1d-de164973fc91.jpg)

3 cables in the grid. (3 x 128k RF/t)
![20160613142955_1](https://cloud.githubusercontent.com/assets/12564251/16018739/c98b864c-3173-11e6-831c-189b5d2dd500.jpg)

It appears that the 3rd set has some energy loss.  I'm not sure if this is an intended feature or a bug.

Do I need to go on?

**Comment by HadesDurin** [comment] 2016-06-13 18:42
well see it as intended usage of mekanism cables @aidancbrady designes them that way, to act diffrently as ender io and thermal expansion cables

**Comment by aidancbrady** [comment] 2016-06-13 18:43
Everything I've seen documented in this thread is intended. Throughput is per-cable, not per-connection or per-grid.

**Closed by aidancbrady** 2016-06-13 18:43 UTC

**Comment by themechman** [comment] 2016-06-14 03:04
Okay, Thank you for clarification. I am making sure I'm not breaking something inadvertently.
