### ISSUE TITLE
[Bug] Miner and robit disappearing when in unloaded chunks

### ISSUE THREAD

**Issue by MysticAura** [aidancbrady/Mekanism#4217] opened 2017-02-19 19:44 UTC
MC: 1.10.2
Forge: 2185
Mod Versions: Mekanism-1.10.2-9.2.1.298, MekanismGenerators-1.10.2-9.2.1.298, MekanismTools-1.10.2-9.2.1.298

Multiple recurrences of digital miners and robits vanishing into thin air. The chunk loading upgrade seems to solve the issue for the miner. No mention of it in logs when it happens. SMP

**Comment by JaSpr** [comment] 2017-02-20 00:28
I've lost a digital miner this way.  I wonder if it has to do with the miner being spanned across chunks?

**Comment by thommy101** [comment] 2017-03-31 18:39
Duplicate of #3718

**Closed** 2017-04-12 14:25 UTC
