### ISSUE TITLE
crash between tinkers and mekanism

### ISSUE THREAD

**Issue by scalda** [aidancbrady/Mekanism#3739] opened 2016-09-04 12:16 UTC
Hi i am haveing client crashes when crafting mekinisms items in tinkers crafting table. 

i have posted on there issues aswell

crash report http://paste.ee/p/7AsET

regards

scalda

**Comment by VT-14** [comment] 2016-09-04 19:16
Duplicate of #3713 and several others.  Next time, search to see if your issue was already reported.  Also include Minecraft, Forge, and related Mods versions (latest and most recent are not version numbers).  

Lastly, remove Optifine; most mods don't support it, and you have a rendering crash.

**Closed** 2016-09-04 20:05 UTC
