### ISSUE TITLE
I tried to add mek v8.1.2.229 to tolkien craft 2 v2.4.10 and it crashed... im totally lost on the cause

### ISSUE THREAD

**Issue by jimmon89** [aidancbrady/Mekanism#2602] opened 2015-04-28 19:46 UTC
crash log is http://pastebin.com/HXv6KcCe

**Comment by bochen415** [comment] 2015-04-28 22:28
Dupe of https://github.com/aidancbrady/Mekanism/issues/2603

**Closed** 2015-04-29 14:00 UTC
