### ISSUE TITLE
Digital Miner Ticking Block Entity 1.10

### ISSUE THREAD

**Issue by beilber** [aidancbrady/Mekanism#4660] opened 2017-08-30 20:41 UTC
#### Issue description:
To test out ore generation on my server I placed a Digital miner with an AE2 setup to get a "core sample".  The miner ran for a few minutes before the server crashed with the attached crash report.  Not sure from the log what the issue could be.  Didn't see any reported issues related to this specific class either.  My guess here is that the miner hit an inventory since MinerUtils.getDrops is at the top of the stack.  If I start the server I get another crash right away.  Let me know what I can test or what other information I can provide to help out.

#### Steps to reproduce:
Could be specific to my mod collection.  I am in the process of removing the world and retesting to see if it happens again but here is how I produced the issue
1. Place miner
2. Install a creative energy cell for power
3. Install max speed, energy and chunk loading upgrades.
4. Filtered dirt and stone with an inverted filter
5. After about 5 minutes crash occurs.

#### Version (make sure you are on the latest version before reporting):
**Forge: 12.18.3.2422** 
**Mekanism: 9.2.3** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[crash.txt](https://github.com/aidancbrady/Mekanism/files/1264988/crash.txt)

**Comment by thiakil** [comment] 2017-08-31 00:45
duplicate of #4637

This has been fixed in dev, yet to release

**Closed by thiakil** 2017-08-31 00:45 UTC
