### ISSUE TITLE
Crash While Leaving the Nether (Mechanical Pipe)

### ISSUE THREAD

**Issue by rannday** [aidancbrady/Mekanism#3701] opened 2016-08-27 05:58 UTC
[http://pastebin.com/raw/mHNcJah9](url)

**Comment by ShaCraft** [comment] 2016-08-27 13:33
That link is broke for me.  How did you come to the conclusion the issue is with Mechanical pipes? What steps did you take to test? Dose the crash occur with only Mekanism installed?

Might the issue be the same as #3626 ?

**Comment by aidancbrady** [comment] 2016-08-27 20:51
Fixed in dev.

**Closed by aidancbrady** 2016-08-27 20:51 UTC
