### ISSUE TITLE
[1.12] Digital Miner doesn't break Geolosys ores

### ISSUE THREAD

**Issue by Jomik** [aidancbrady/Mekanism#4841] opened 2017-12-01 12:34 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
In creative, putting in a geolosys ore in the digital miner simply makes the miner count the ores, before the saying there's 0 to mine after the first one.

#### Steps to reproduce:
1. Put down digital miner and give energy
2. Put any geolosys ore block in the ItemStack filter, making sure it's under the miner.
3. Press start, observe it count and then go to 0

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.12.2-forge1.12.2-14.23.1.2555
**Mekanism:** Mekanism-1.12.2-9.4.2.327
**Other relevant version:** Geolosys-1.12.x-1.8.3

**Comment by pflonk** [comment] 2017-12-01 17:23
Same issue, other Ore:
Cannot break LapisLazuli (neither with silktouch nor without). It's counting, wants to start, then jumps to 0 and idles.

Forge: 14.23.0.2486
Mekanism: 1.12.2-9.4.2.328

no other mods.

**Comment by thiakil** [comment] 2017-12-02 06:18
If it goes down to zero, you have some form of block protection active that prevents the FakePlayer from breaking blocks.

**Comment by Svenskunganka** [comment] 2017-12-02 08:08
@thiakil I've got the exact same issue as @pflonk, the miner does mine everything except for Lapis. It doesn't seem like the cause is block protection.

**Comment by Jomik** [comment] 2017-12-02 08:25
@thiakil
My pack is rather ripped, so I can't really imagine anything there preventing a FakePlayer breaking them. It also can break the quartz blocks from Geolosys, just not the others..

**Comment by thiakil** [comment] 2017-12-02 15:05
Try what I said in this comment, and you will find out if it is chunk protection of some kind.

https://github.com/aidancbrady/Mekanism/issues/4820#issuecomment-346231553

**Comment by Jomik** [comment] 2017-12-02 15:33
Where do I find this config option? I don't have it in my config.

**Comment by thiakil** [comment] 2017-12-02 15:35
You need to start the game with that special build, then it will be there.

**Comment by Svenskunganka** [comment] 2017-12-02 22:44
@thiakil Alright so I've ran the game with that build now, with the `logDigitalMinerBlockBreakDenied` config option set to `true`, however when looking at the log around the time I tested this I don't see anything being logged. I've attached the full log here: [latest.log](https://github.com/aidancbrady/Mekanism/files/1524320/latest.log)

I ran the Digital Miner near the bottom of the log file, between these two lines:
```
[23:35:49] [Server thread/INFO]: [Svenskunganka: Set own game mode to Creative Mode]
<--- Ran the miner here for Lapis only.
[23:36:32] [Server thread/INFO]: Saving and pausing game...
```

**Comment by thiakil** [comment] 2017-12-03 04:27
Thanks, I will take a more detailed look.

**Comment by thiakil** [comment] 2017-12-03 04:27
How exactly did you get an itemstack for the filter btw?

**Comment by Svenskunganka** [comment] 2017-12-03 04:47
Got myself into creative and got the lapis ore (not the single lapis item) and placed it into the itemstack filter. I've also tried with `oreLapis` to no avail. The miner does show a number to mine for a few seconds until it turns off.

**Comment by thiakil** [comment] 2017-12-03 04:51
ok, so the lapis thing is standard minecraft lapis?

**Comment by Svenskunganka** [comment] 2017-12-03 04:51
Yes, vanilla Lapis

**Comment by thiakil** [comment] 2017-12-03 05:11
Both issues fixed in dev now

**Comment by Svenskunganka** [comment] 2017-12-03 05:23
Nice! Thank you for taking time fixing this, @thiakil!

One last question, is there any way to get a build of the latest dev?

**Comment by thiakil** [comment] 2017-12-03 05:40
Yeah compiling from source is always an option ;)

**Comment by Svenskunganka** [comment] 2017-12-03 07:49
I've verified that the change you made @thiakil works now. Once again, thank you (and Aidan as well as all the other contributors) for all your work on this mod, it is one of my favorites!

Also, IC2's Maven was down over at maven.ic2.player.to so I had to change it to curseforge's Maven for it to build properly:

```diff
diff --git a/build.gradle b/build.gradle
index 7d10a01..b66e424 100644
--- a/build.gradle
+++ b/build.gradle
@@ -76,7 +76,7 @@ repositories {
     }
     maven {
         name 'ic2'
-        url 'http://maven.ic2.player.to'
+        url 'https://minecraft.curseforge.com/api/maven/'
     }
     maven {
         name 'BlameJared - Crafttweaker'
@@ -127,7 +127,8 @@ dependencies {
     compileOnly "com.mod-buildcraft:buildcraft-api:${config.buildcraft_version}"
     compileOnly "team.chisel.ctm:CTM:MC1.12-${config.ctm_version}:api"
     runtime "team.chisel.ctm:CTM:MC1.12-${config.ctm_version}"
-    compileOnly "net.industrial-craft:industrialcraft-2:${config.ic2_version}:api"
+    compileOnly "industrial-craft:industrialcraft-2:release:ex112"
+    //compileOnly "net.industrial-craft:industrialcraft-2:${config.ic2_version}:api"
     compileOnly ("CraftTweaker2:CraftTweaker2-API:${config.crafttweaker_version}") {
         exclude module: "asm-debug-all"
     }
@@ -328,4 +329,4 @@ if (System.getenv("CURSEFORGE_KEY") != null) {
             addGameVersion '1.12.2'
         }
     }
-}
\ No newline at end of file
+}

```

Added it in case anyone else comes by and runs into the same issue.

**Comment by RenaTheHyena** [comment] 2017-12-12 21:30
Any chance we can please get a version of the mod with this fixed early ? I really need my lapis n.n

**Comment by Svenskunganka** [comment] 2017-12-12 23:18
@RenaTheHyena I've attached my build of the dev version which you can use if you want. Worked without issue for me in the Direwolf 1.12 pack. Note that this build is strictly for 1.12 and not any other version of Minecraft.


[Mekanism.zip](https://github.com/aidancbrady/Mekanism/files/1553632/Mekanism.zip)

**Comment by thiakil** [comment] 2017-12-13 03:03
@Svenskunganka Please don't do that. As much as I like innocent until proven guilty, we cannot condone unofficial builds like that.

@RenaTheHyena you can use http://maven.thiakil.com/mekanism/Mekanism/1.12.2-9.4.3.329-thiakil/Mekanism-1.12.2-9.4.3.329-thiakil.jar

**Comment by Svenskunganka** [comment] 2017-12-13 19:38
Apologies, didn't know. Just wanted to be of help to the guy. Thanks for sharing your build, though!

**Closed** 2017-12-17 15:52 UTC
Labels: bug, Fixed in dev
