### ISSUE TITLE
Mekanism axes can't be enchanted with Sharpness

### ISSUE THREAD

**Issue by roboderpy** [aidancbrady/Mekanism#4122] opened 2017-01-04 06:06 UTC
![2017-01-04_13 04 49](https://cloud.githubusercontent.com/assets/6339511/21633086/a7df00da-d27e-11e6-97ea-73d0775b52a4.png)
![2017-01-04_13 04 54](https://cloud.githubusercontent.com/assets/6339511/21633085/a7dac312-d27e-11e6-9615-aa7492bff6f4.png)

**Comment by ThatGamerBlue** [comment] 2017-01-04 10:17
Working as intended. @aidancbrady /close

**Comment by roboderpy** [comment] 2017-01-04 12:34
@ThatGamerBlue What version do you use? I use latest version on 1.10.2

**Comment by thommy101** [comment] 2017-01-04 12:38
With working as intended he means that the item is non-enchantable.

**Comment by roboderpy** [comment] 2017-01-04 12:42
You can enchant vanilla axe with Sharpness, but you can't enchant Mekanism axe with Sharpness. For me this is unexpected behaviour

**Comment by VT-14** [comment] 2017-01-04 15:07
Are we sure they are supposed to be non-enchantable?  The config file has an "enchantability" setting that I think defaults to not 0. 

In Hermitpack, Obsidian is set to have an enchantability of 40 (which I assume is the default).  For comparison, gold tools have an enchantability of 22.

**Comment by MrPatience** [comment] 2017-01-04 15:13
As roboderpy said , you can enchant vanilla axes with sharpness enchant. I thought we could also do this in prior versions of mekanism.. Has it been removed ?

**Comment by thommy101** [comment] 2017-01-04 16:35
I stand corrected, Mekanism items are enchantable.

**Comment by roboderpy** [comment] 2017-01-04 16:39
No i meant that you *can't* combine Axe with Enchant Book that is enchanted
with Sharpness

04 Янв 2017 г. 23:35 пользователь "Tom E" <notifications@github.com>
написал:

**Comment by thommy101** [comment] 2017-01-04 16:54
I know that, I initially thought they where not enchantable at all. Currently the axes look like an ItemTool for Minecraft and thus only allows ItemTool enchantments. Somewhere in Minecraft/forge must be a check: if axe, allow sharpness. I'll take a look where it is and try to fix the axe :)

**Comment by thommy101** [comment] 2017-01-04 17:05
Took a look at how enchantments are dealt with in Forge/Minecraft. Looks like (in 1.10) it's hardcoded to instances of ItemAxe. I only can think of a dirty way to fix it, not a nice and clean one.

**Comment by thommy101** [comment] 2017-01-04 17:53
![](http://i.imgur.com/YenAQ8B.png)

This looks better right?

**Comment by roboderpy** [comment] 2017-01-04 22:10
yes

05 Янв 2017 г. 0:53 пользователь "Tom E" <notifications@github.com> написал:

**Comment by thommy101** [comment] 2017-04-28 12:00
Can be closed when the 1.10 branch is merged to 1.11.

**Closed** 2017-04-28 21:27 UTC
