### ISSUE TITLE
[1.11.2] Configurator on Wrench used on Bin with Potatoes makes Bin Disappear

### ISSUE THREAD

**Issue by Dragnier** [aidancbrady/Mekanism#4654] opened 2017-08-28 07:01 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
As the title says, Bin wrenched with configurator disappears completely including loss of contents.

#### Steps to reproduce:
1. Place Basic Bin.
2. Input potatoes (I had 51 in mine, doubt that matters.)
3. Set configurator to Wrench and shift + right click the Bin with the potatoes.
4. Bin and contents just disappear.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2 - 13.20.1.2454
**Mekanism:** 1.11.2 - 9.3.4-fix

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
No crash.

**Comment by gp009** [comment] 2017-09-21 00:19
Configurator on Wrench,  ANY mod wrench right-clicking on ANY tier mekanism bin with ANY item in them WILL cause them to dissapear.   ALSO happens  1.12.1

SAME steps as above to reproduce the bug,  takes multiple attempts as it doesnt always happen

Forge:  1.12.1 14.22.1.2481
Mekanism 1.12.1-9.4.1.326

NOTE: Mine-breaking them with a pickaxe or paxel seems to be best option to avoid the bug.

**Comment by thommy101** [comment] 2017-12-17 13:10
Just retested this, it is apparently fixed in 1.12.2 due to some other commit.

**Closed** 2018-01-01 13:53 UTC
Labels: bug, Not reproducible
