### ISSUE TITLE
[1.12.2] Crash with JAOPCA 

### ISSUE THREAD

**Issue by MokahTGS** [aidancbrady/Mekanism#4828] opened 2017-11-26 19:40 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Getting a crash with Mekanism v327 and JAOPCA

#### Steps to reproduce:
1. Update from v326 to v327
2.Load MC
3.Crash

#### Version (make sure you are on the latest version before reporting):
**Forge: 2554 
**Mekanism: 327
**Other relevant version: JAOPCA v2.5.63

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

https://pastebin.com/BcDH2xCA

**Comment by CerulanLumina** [comment] 2017-11-26 21:06
This is caused by JAOPCA using an outdated API call, see TheLMiffy1111/JAOPCA#38.

**Comment by thommy101** [comment] 2017-11-26 21:11
Thanks @CerulanLumina for pointing that out. I thought the change was backwards compatible.. We might take a look to make it compatible again so other mods which do not update as quick do not suffer from the same issue (with some compatability methods which will be deprecated).

**Comment by CerulanLumina** [comment] 2017-11-26 21:17
@thommy101 More accurately, JAOPCA was referencing a removed gas type ("liquidstone"), the result is the same, however.

**Comment by thommy101** [comment] 2017-11-26 21:28
Aah.. I see.. We do have compatability with older versions.. Only that way would break and is sadly not something we can fix (except adding the gas temporarily). I'll take a better look tomorrow, looking through code on mobile isn't the greatest.

Thank you for opening the PR to YAOPCA to fix it :)

**Comment by thiakil** [comment] 2017-12-04 03:04
JAOPCA issue has been closed as fixed

**Closed by thiakil** 2017-12-04 03:04 UTC
Labels: bug, interaction
