### ISSUE TITLE
TD Fluid Ducts issue

### ISSUE THREAD

**Issue by tgstyle** [aidancbrady/Mekanism#4661] opened 2017-08-31 03:38 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Fluid ducts are not reconnecting to multiblock machines after a server restart.

#### Steps to reproduce:
1. Build a multiblock machine on a server, connect a fluid duct
2. Restart the server and log back in
3. Fluid ducts are no longer connected

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.22.0.2465
**Mekanism:** 9.4.0.318
**Other relevant version:** ThermalDynamics 2.3.5.12

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

![2017-08-30_21 35 59](https://user-images.githubusercontent.com/5832709/29905353-7e41b020-8dcb-11e7-92cc-6ec9e47fe76e.png)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-10-08 09:16
Sorry for the late response, but do the pipes connect if you place a block next to the not connecting pipe?

**Comment by tgstyle** [comment] 2017-10-08 20:43
No, it still is disconnected on a server restart.

**Comment by tgstyle** [comment] 2017-10-27 05:06
Actually sorry yes, placing a block does force an update and makes it connect.

**Comment by thiakil** [comment] 2017-11-09 14:01
Closing as duplicate of #4717

**Closed by thiakil** 2017-11-09 14:01 UTC
Labels: bug
