### ISSUE TITLE
1.12.1 endless Hydrogen for jetpacks

### ISSUE THREAD

**Issue by Jay9519** [aidancbrady/Mekanism#4619] opened 2017-08-12 09:10 UTC
#### Issue description:

when using the Jetpack and the armored Jetpack if you hold spacebar for a length of time (to use Hydrogen)
then release the spacebar and press again, then the Hydrogen fills back up again
Endless hydrogen and never need to refill

#### Steps to reproduce:
1. Make a jetpack
2.use space bar to go up for a few seconds and watch your hydrogen levels
3.release space bar and press again and the hydrogen levels are back up to full

#### Version (make sure you are on the latest version before reporting):
forge-1.12.1-14.22.0.2446-universal
spongeforge-1.12.1-2444-7.0.0-BETA-2537.jar
Mekanism1.12.1-9.4.0.318

No errors show

**Comment by thommy101** [comment] 2017-08-12 09:11
Thanks for reporting, this is however a duplicate of #3805.

**Closed by thommy101** 2017-08-12 09:11 UTC
