### ISSUE TITLE
Crash on Load [1.11.2]

### ISSUE THREAD

**Issue by Dragnier** [aidancbrady/Mekanism#4431] opened 2017-06-03 14:38 UTC
Crash Log:

https://gist.github.com/Dragnier/9fd6c714a0368b8f6934f22353121280

**Comment by thommy101** [comment] 2017-06-03 14:44
Duplicate of #4414 
Fixed in #4415 which is already merged. Fix will be available in the next release.

**Closed** 2017-06-03 22:15 UTC
