### ISSUE TITLE
[1.10.2] Server crashes: net.minecraft.util.ReportedException: Ticking block entity

### ISSUE THREAD

**Issue by Camrais** [aidancbrady/Mekanism#4374] opened 2017-05-18 20:28 UTC
Hi,

i just recently had this problem with deep resonance. @McJty luckily had this already fixed and a new version uploaded. This error happens when we now try to join from aroma mining world to the overworld (we have it running on a server). The server crashes then but the clients dont. Idk if this is because i just recently placed some universal cables in the overworld. Before that the error didnt occure. 

Here an extract of the log:

Description: Ticking block entity

>java.lang.NullPointerException: Ticking block entity
>	at mcmultipart.network.MessageMultipartChange.toBytes(MessageMultipartChange.java:51)
>	at mcmultipart.network.MessageSplit.split(MessageSplit.java:94)
>	at mcmultipart.network.MessageMultipartChange.send(MessageMultipartChange.java:142)
>	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:340)
>	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:330)
>	at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:193)
>	at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
>	at mekanism.common.multipart.PartUniversalCable.func_73660_a(PartUniversalCable.java:144)
>	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
>	at net.minecraft.world.World.func_72939_s(World.java:1804)
>	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
>	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
>	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:387)
>	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
>	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
>	at java.lang.Thread.run(Thread.java:745)

and the full crash log:
[crash-2017-05-18_22.01.28-server.txt](https://github.com/aidancbrady/Mekanism/files/1012351/crash-2017-05-18_22.01.28-server.txt)

Greetz,
Camrais

**Comment by thiakil** [comment] 2017-05-19 03:02
This is a MCMultipart issue, the MultiPart container is not returning the ID properly.

Dupe of https://github.com/amadornes/MCMultiPart/issues/71

**Closed** 2017-05-23 22:35 UTC
