### ISSUE TITLE
[1.12.2] Crash on startup

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4864] opened 2017-12-15 12:22 UTC
Literally just started the game and then this:

[LOG](https://pastebin.com/UF8ZRU61)

All information about versions and whatnot are in the CrashLog.

Interesting part i found was "java.lang.IllegalStateException: Gasses must be registered before postInit."

**Comment by thommy101** [comment] 2017-12-15 14:24
Please use search, duplicate of #4827

**Closed by thommy101** 2017-12-15 14:24 UTC
