### ISSUE TITLE
Turbines are now really laggy and opaque

### ISSUE THREAD

**Issue by josephcsible** [aidancbrady/Mekanism#4829] opened 2017-11-26 19:54 UTC
Our turbines now cause extreme lag, and are opaque due to steam instead of being translucent. This started happening in the new version of Mekanism. I tracked it down to commit 1e046a3 (pinging @thiakil).

Here's what it looks like without that commit (correct):
![2017-11-26_14 52 13](https://user-images.githubusercontent.com/16061266/33243723-6e16641a-d2b9-11e7-8c05-a183b4d0d164.png)

And here's what it looks like with that commit (buggy):
![2017-11-26_14 49 46](https://user-images.githubusercontent.com/16061266/33243724-6f798cf6-d2b9-11e7-8d1d-d9a99e48ffd2.png)

Versions:
Minecraft 1.12.2
Forge 14.23.1.2554
Mekanism (and MekanismGenerators) 9.4.2

**Comment by thommy101** [comment] 2017-11-26 21:15
Are both issues not present in the version before that commit or only he lag issue? The transparency is probably caused by 532744f5988c844005f71f1c33c0c5c4da897cb5

**Comment by josephcsible** [comment] 2017-11-26 21:18
Both issues are present with that commit and absent without it.

**Comment by thiakil** [comment] 2017-11-26 21:52
It's probably the commit after that which deals with mostly gui rendering of gasses. The kinked commit should only affect tube rendering

**Comment by josephcsible** [comment] 2017-11-26 21:53
I did a build of the latest HEAD, which had the problem. Then I reverted 1e046a3 alone, leaving the commits after it, and didn't have the problem.

**Comment by thiakil** [comment] 2017-11-26 21:59
Didn't gave which problem? (there's no way that could affect rendering)

**Comment by josephcsible** [comment] 2017-11-26 22:07
I know it seems unlikely, but I've tested and re-tested, in the dev environment and in a regular game environment, and both problems are linked to that commit and that commit alone.

**Comment by josephcsible** [comment] 2017-11-26 22:18
Can one of you try exactly what I did on your computer, just to see if it's reproducible?
1. Check out latest git
2. Open this world with it: https://drive.google.com/file/d/1DV-WgqdMW9ZlfoHWdGCb8Q3SxadkF5Lv/view?usp=sharing (it will be laggy and opaque)
3. Revert 1e046a3, with `git revert 1e046a3` or `git show 1e046a3 | patch -p1 -R` or something
4. Open the world again (it will be fast and correct)

**Comment by thiakil** [comment] 2017-11-26 22:24
I have seen the opaqueness in my test world, but not the lag. Either way it's a symptom, not so much a cause as there shouldn't be block updates bouncing around like that

**Comment by thiakil** [comment] 2017-12-03 11:09
Fixed in dev

**Comment by josephcsible** [comment] 2017-12-03 18:36
Thanks. I can confirm that the latest dev build fixes both problems for me.

**Closed** 2017-12-09 21:57 UTC
Labels: bug, Fixed in dev

**Comment by Xiaminou** [comment] 2017-12-13 00:54
Is it supposed to be fixed in [this build](http://maven.thiakil.com/mekanism/Mekanism/1.12.2-9.4.3.329-thiakil/)? Because I have an FPS issue with max size turbine. It drops my FPS from 200 to 20.

**Comment by thiakil** [comment] 2017-12-13 01:00
It should be fixed there, yes

**Comment by Xiaminou** [comment] 2017-12-13 01:04
Well then I suppose I should open a different issue.
