### ISSUE TITLE
Jetpack falldamage bug

### ISSUE THREAD

**Issue by Greg9711** [aidancbrady/Mekanism#3996] opened 2016-11-21 19:26 UTC
When i fly in the air with the regular mode, then fall down and slow myself down before i hit the ground so i fly a bit (1block) up again so my falldamage should be nothing, but when i hit the ground i take 5 to 7 hearts of damage.

**Comment by HyperBlueCore** [comment] 2016-11-22 16:02
that's not a bug its from the minecraft files its because you keep getting up then down because its in regular mode so it counts every up and down so if you kept going up and down for 100 times you would get 100 hp of damage
But that's fixed in 1.10.2 for me

**Comment by Greg9711** [comment] 2016-11-24 15:41
Ok that explains why i´m taking so much damage but isn´t it still a bug that the jetpack doesn´t reset the falldamage, or maybe its a problem with another mod if it doesnt happen to you.

**Comment by PJB3005** [comment] 2016-11-25 15:09
I think I experienced some issues with high damage amounts from jetpacks in 1.10.2 too, but strangely enough I think that was when going upwards to land on something? I might be misremembering as I haven't reproduced it since.

**Comment by Greg9711** [comment] 2016-11-25 16:18
Going up and landing on something hurts me as well

**Comment by HyperBlueCore** [comment] 2016-11-29 20:31
just use the free runners it will stop fall damage

**Comment by Greg9711** [comment] 2016-11-29 21:00
True but its still a bug

**Comment by HyperBlueCore** [comment] 2016-11-29 23:57
did you update to 9.2.1

**Comment by Greg9711** [comment] 2016-11-30 00:43
Not yet, i´ll do that and check if it still happen when i´m playing next time

**Comment by th4umiel** [comment] 2017-03-04 18:23
Running Mekanism-1.10.2-9.2.1.298 and this issue is still here. I think this should be adressed as soon as possible. The free runners work but this is still quite a bug o.O

**Closed** 2017-04-05 00:54 UTC
