### ISSUE TITLE
[1.10.2] Error while encoding packet data + tps lag

### ISSUE THREAD

**Issue by ZerrayX** [aidancbrady/Mekanism#4685] opened 2017-09-12 16:28 UTC
#### Issue description:
My Server Console is spamming this message, sometimes the server lag pretty hard or crash on chunkload.. the multiblocks are allways in one chunk. The block which cause the crash is most of the time a universal cable or mechanical pipe, sometimes in the middle of a chunk.
The Un-encodable data point on a turbine casing

#### Steps to reproduce:
I dont really know how to reproduce I add a crash log and a screenshot of the console output

#### Version (make sure you are on the latest version before reporting):
**Forge: 12.18.3.2422
**Mekanism: 1.10.2-9.2.4.103.jar
**Other relevant version: see Crash Log

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
http://imgur.com/a/KEGq9
https://pastebin.com/xdFPK6Zm

**Comment by thiakil** [comment] 2017-09-13 01:34
Crashlog posted is a MCMultipart issue and has been reported multiple times. Nothing we can do about it.

I don't know that you mean by this: 

>The Un-encodable data point on a turbine casing

**Comment by ZerrayX** [comment] 2017-09-13 14:56
check the imgur screenshot, the block reported by Un-encodable data 2161, 67, 4697 is turbin casing block

**Comment by thommy101** [comment] 2017-09-14 05:31
The un-encodable data is already reported at #4484. The log of the issue is gone, but I'm certain this is the same issue and has been fixed in at least 1.11 and up.

**Comment by thiakil** [comment] 2017-09-14 05:33
I checked, and the username lookup thing was backported to 1.10 so should be in the version shown in the mcmultipart crashlog here :/

**Comment by thiakil** [comment] 2017-10-03 11:22
@ZerrayX could you please test with this build? http://maven.thiakil.com/mekanism/MekanismAll-1.10.2-9.2.4.103+6f129e14-debug-3.jar

It will either solve your issue or tell us where it needs to be fixed

**Closed** 2019-03-20 07:42 UTC
Labels: Waiting Feedback
