### ISSUE TITLE
1.10.2 Crash with Treecapitator

### ISSUE THREAD

**Issue by Liiw** [aidancbrady/Mekanism#4329] opened 2017-04-19 10:38 UTC
Hello!

I am using Mekanism on  a 1.10.2 SpongeForge server. This mod is excellent, however there seems to be a bit of an incompatibility with the Treecapitator mod. The problem is that whenever someone tries to hit a placed Mekanism cable. their client crashes. The cables can only be removed in creative mode. I am attaching a crash log I got from testing: 

[crash-2017-04-19_03.54.44-client.txt](https://github.com/aidancbrady/Mekanism/files/933499/crash-2017-04-19_03.54.44-client.txt)

I tried to post an issue on the Treecapitator github site, but the author has disabled this feature. This is the github site: https://github.com/jco2641/Treecapitator 

I understand that the version of Treecapitator is not official release and I actually got it by following instructions on the site there. What could be done to remedy this issue?

**Comment by thommy101** [comment] 2017-04-19 11:23
Duplicate of #4194 
The GitHub page you're mentioning still accepts issue reports, please report over there.

**Closed** 2017-04-19 14:04 UTC

**Comment by Liiw** [comment] 2017-04-19 20:00
Thank you for your reply! 

Although I searched for "treecapitator" from the issues section, I seem to have missed the one you referenced. I will try to contact the current maintainer of the mod.

**Comment by Liiw** [comment] 2017-04-19 20:11
Oh dear, I do not feel very smart right now :D

For two times I tried to unsuccesfully post an issue on the Treecapitator site before posting this here. I tried once again, and I was succesful. Note to anyone having issues with the "submit" button greyed out: yer missing a title! :P
