### ISSUE TITLE
Formulaic Assemblicator can't autocraft some recipes

### ISSUE THREAD

**Issue by mal** [aidancbrady/Mekanism#4650] opened 2017-08-27 02:29 UTC
#### Issue description:

Formulaic Assemblicator can't auto-craft Firework Rockets [Flight Duration: 3] (1 paper, 3 gunpowder). The Crafting Formula can be encoded fine and the paper stock is managed successfully but the machine acts as if there is no gunpowder available.

#### Steps to reproduce:
1. Place and power a Formulaic Assemblicator
2. Install a Crafting Formula
3. Add one paper and three separate gunpowder to the crafting area
4. Encode the Crafting Formula
5. Turn on auto mode (see two Firework Rocket [Flight Duration: 3] created)
6. Fill machine stock area with stacks of paper and gunpowder
7. See gunpowder in crafting area marked as red and no auto crafting taking place

#### Version:
**Forge:** 13.20.1.2393
**Mekanism:** 9.3.2
**Other relevant version:** Minecraft 1.11.2

**Comment by thommy101** [comment] 2017-08-27 07:04
Thanks for reporting! 

Possible duplicate of #4621

This issue is already fixed, but isn't available yet, but will be in the next release ;)

**Closed by thommy101** 2017-08-27 07:04 UTC
