### ISSUE TITLE
digital miner keeps on despawning

### ISSUE THREAD

**Issue by rivercobber** [aidancbrady/Mekanism#4003] opened 2016-11-22 23:53 UTC
hey im having a problem with the digital miner it keeps on de-spawning i have gone thought 4 of them at first it was just when i logged off but now its happening when im there please help

**Comment by VT-14** [comment] 2016-11-23 04:39
I didn't have that issue while using a chunk loading upgrade in the DM.  Otherwise, I lost two a while ago.

**Comment by MoonCutter2B** [comment] 2016-12-04 10:43
has happened to me too once, was logged off

**Comment by thommy101** [comment] 2017-03-31 18:39
Duplicate of #3718

**Closed** 2017-04-12 14:24 UTC
