### ISSUE TITLE
Possibly wrong texture resolution

### ISSUE THREAD

**Issue by phyyyl** [aidancbrady/Mekanism#5077] opened 2018-06-08 21:10 UTC
#### Issue description:
Possibly wrong texture resolution.

#### Steps to reproduce:
Install Mekanism with MultiMC and start with Forge...

#### Versions:
**Forge:** 14.23.4.2707
**Mekanism:** Mekanism-1.12.2-9.4.10.345
**MultiMC 5:** 0.6.2-1222

#### Log:
[Full log](https://gist.github.com/phyyyl/7ba7a1911a49002394595440d89ed414)
**Obviously relevant part:**
```
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/universalcableverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalelite.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/universalcableverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/pressurizedtubeverticaladvanced.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/opaque/thermodynamicconductorverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/pressurizedtubeverticalultimate.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/universalcableverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
...
[nomatterwhattime] [main/WARN] [net.minecraft.client.renderer.texture.TextureMap]: Texture mekanism:textures/blocks/models/multipart/thermodynamicconductorverticalbasic.png with size 12x12 will have visual artifacts at mip level 4, it can only support level 2. Please report to the mod author that the texture should be some multiple of 16x16.
```

**Comment by thiakil** [comment] 2018-06-09 14:38
duplicate of #4920

**Closed by thiakil** 2018-06-09 14:38 UTC
