### ISSUE TITLE
[1.10.2] Minecraft Crash caused by Mekanism after adding ExtraCells2

### ISSUE THREAD

**Issue by k3kz0r** [aidancbrady/Mekanism#4879] opened 2017-12-24 14:33 UTC
#### Issue description:
Mekanism makes Minecraft crash while starting after adding ExtraCells2 to the modpack.

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from Mekanism (Mekanism)

#### Steps to reproduce:
1. Install FTB Minecraft Beyond Modpack for MC1.10
2. Update Forge to the newest Version (12.18.3.2511)
2. add Mekanism and start the game (game will run normally)
3. add Extra Cells 2 and try to start the Game

**Forge: forge-12.18.3.2511** 
**Mekanism: Mekanism-1.10.2-9.2.4.103**
**MekanismGenerators-1.10.2-9.2.4.103**
**MekanismTools-1.10.2-9.2.4.103**
**ExtraCells2: ExtraCells-1.10.2-2.4.4a15** 

Crash-Report:
https://pastebin.com/i9RrTQgU

**Comment by thommy101** [comment] 2017-12-24 14:39
Duplicate of #4854. Please update wireless crafting terminal.
Not an Mekanism issue.

**Closed by thommy101** 2017-12-24 14:39 UTC
