### ISSUE TITLE
Most machines appearing as enrichment chamber in Waila.

### ISSUE THREAD

**Issue by dragonpc75** [aidancbrady/Mekanism#4153] opened 2017-01-23 04:41 UTC
mekanism version [MC 1.10.2]  9.2.1.298 (generators and tools installed all the same version)
Most machines, Enrichment Chamber, Metallurgic Infuser, Purification Chamber, to name a few are all appearing as Enrichment chambers, (those are just the ones i have built so far, others like the Electrolytic Separator, and  Chemical Infuser, are showing as Rotary Condensentrator. (i havn't even built that machine yet lol)

**Comment by thommy101** [comment] 2017-01-23 08:05
Duplicate of #4073

**Comment by roboderpy** [comment] 2017-01-24 23:31
Use HWYLA
![2017-01-25_06 30 12](https://cloud.githubusercontent.com/assets/6339511/22271586/d96ea958-e2c7-11e6-9e30-18a44116a28e.png)
![2017-01-25_06 30 15](https://cloud.githubusercontent.com/assets/6339511/22271588/d9a942fc-e2c7-11e6-8971-38822cd33b1c.png)

**Comment by JaSpr** [comment] 2017-01-31 04:29
Also correct in "The One Probe".  WAILA has issued a note on how to resolve this by the Mekanism maintainer: https://bitbucket.org/ProfMobius/waila/issues/273/194-showing-incorrect-block-type-mekanism

**Comment by JaSpr** [comment] 2017-02-01 10:22
I researched the suggested resolution, and found that it was not even applicable to our case.  It turns out that the WAILA code for getting the targeted block was incorrect. 

I have submitted a pull request to WAILA with the resolution.

https://bitbucket.org/ProfMobius/waila/pull-requests/47

THIS ticket can be closed.

**Comment by JaSpr** [comment] 2017-02-01 10:28
Also, this ticket duplicates #3983

**Closed** 2017-02-12 19:38 UTC
