### ISSUE TITLE
[1.12.2] Log spam when adding recipes to the crusher with CraftTweaker

### ISSUE THREAD

**Issue by NickelHub** [aidancbrady/Mekanism#5249] opened 2019-01-11 11:06 UTC
#### Issue description:
I try to add new bio fuel recipes for Mekanism because of the lot of stuff added by many mods. There is a lot of spawn and warning although the overwriting is intended.  

#### Steps to reproduce:
1. Use this script: https://pastebin.com/7FmhCtPf
2. Lauch the game
3. Warning appears

Note that the sawmill recipes are actually doing the same without any warning. 
#### Version (make sure you are on the latest version before reporting):
**Forge:**2796
**Mekanism:** 9.4.13.349
**CraftTweaker:** 4.13

CTLog:  [crafttweaker.log](https://github.com/aidancbrady/Mekanism/files/2749358/crafttweaker.log) starting at line 2882 (was to large for paste.bin etc.)

**Comment by idnthvn** [comment] 2019-01-11 13:12
Also have this issue. Except mine is the precision sawmill. Seem to wonder if its anything that already exists with mekanism and we want to override tmwhat mekanism has default

**Comment by pupnewfster** [comment] 2019-03-06 18:42
Looking at the script the reason the bio fuel is throwing a fit is if you look at like 38-39
```
for item in lilypad.items{
for item in fruit.items{
```
the first for loop doesn't get closed until line 65
``
mods.mekanism.crusher.addRecipe(item, <mekanism:biofuel>);
    }
```
so it is adding the same recipes over and over again for every loop that is in the middle of it.

**Comment by thiakil** [comment] 2019-03-10 05:46
warning should be fixed by newer version of MTlib, not sure about the 0 recipes thing. If you can reproduce in a small CT script I can look into it

**Comment by pupnewfster** [comment] 2019-03-10 11:54
The issue with the 0 recipe thing is that `describe()` is called before `apply()` is called. So it "appears" to get spammed, as it shows up when there is no recipe matched to remove, or when a recipe is actually removed it hasn't been added to the list to be removed yet so it has a count of 0 in the logged message.

It can be fixed by overriding describe with an empty string (to make it so it doesn't print the normal describe method). You then need to manually call `super.describe();` manually after adding it to the list of recipes to remove.

For the adding messages if you move your call to `addRecipes()` to the constructor from overriding `apply()` that should fix it for saying "added 0 recipes".

**Comment by thiakil** [comment] 2019-03-10 12:08
Thanks for the explanation, though this part doesnt quite make sense, as `describe` is a getter lol

> It can be fixed by overriding describe with an empty string (to make it so it doesn't print the normal describe method). You then need to manually call super.describe(); manually after adding it to the list of recipes to remove.

**Comment by pupnewfster** [comment] 2019-03-10 12:52
Hard to format on the phone but https://github.com/CraftTweaker/CraftTweaker/blob/1.12/CraftTweaker2-API/src/main/java/crafttweaker/runtime/CrTTweaker.java#L54 is where describe gets called automatically

**Closed** 2019-03-11 19:42 UTC
