### ISSUE TITLE
[1.11.2] Crash on launch

### ISSUE THREAD

**Issue by Tencao** [aidancbrady/Mekanism#4439] opened 2017-06-05 13:58 UTC
Crashlog - https://paste.ee/r/Z92wG
Forge version - 13.20.0.2310
Mekanism version - 9.3.1

**Comment by thommy101** [comment] 2017-06-05 14:03
Duplicate of #4414 
It's fixed and will be available in the next release

**Closed** 2017-06-10 17:56 UTC
