### ISSUE TITLE
mechanical pipe

### ISSUE THREAD

**Issue by Midnighthd** [aidancbrady/Mekanism#4717] opened 2017-09-25 20:53 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Steps to reproduce:
1.
2.
3.

#### Version (make sure you are on the latest version before reporting):
**Forge:  13.20.1.2476
**Mekanism: 9.3.4
**Other relevant version: 

Hello, 
![2017-09-25_22 32 29](https://user-images.githubusercontent.com/32279428/30830439-5f928cc0-a244-11e7-9ec9-a801f90a83fd.png)
I have a issue with the Thermal Evaporation Block, the mechanical pipe won't connect to the Thermal Evaporation Valve. I tried with the configurator, same issue.

[gist/pastebin/etc link here]

**Comment by thiakil** [comment] 2017-09-26 00:40
Please fill out the reproduction steps in the template.

Is your evaporation plant fully formed? Was the pipe placed before or after the plant was formed? Is it something that happens after server/game restart?

**Comment by Midnighthd** [comment] 2017-09-26 10:52
yes it is completely form the pipe was placed after the plantation and cella does not come from the server

**Comment by thommy101** [comment] 2017-10-07 17:30
Can confirm this happening in certain situations.

Steps to reproduce:
- Place the tubes next to an invalid structure, like in above picture.
- Complete the structure
- See pipe not connect
- Break pipe & place it again OR place a block next to the misbehaving pipe
- See pipe connect

Tech guess:
Pipe isn't allowed to connect if the structure is invalid, if the structure is made valid, with a block which doesn't cause a direct block update it doesn't update the connection status of the pipe.

This is probably also the cause of some other random pipe not connecting issues. Pipe gets loaded, may not connect, structure is loaded (and validated), pipe may connect but isn't aware of this.
Even bigger guess for a solution: Once a structure is validated (and maybe even invalidated) let all things that interact with the "outside world" (valves & blocks) execute a block update letting blocks next to it know its state has changed.

**Comment by thiakil** [comment] 2017-11-19 09:40
This is fixed in 1.12

**Closed** 2017-11-27 01:04 UTC
Labels: bug, confirm, Fixed in dev
