### ISSUE TITLE
Tinkers Construct Crash 

### ISSUE THREAD

**Issue by yepidoodles** [aidancbrady/Mekanism#4212] opened 2017-02-18 23:15 UTC
https://github.com/SlimeKnights/TinkersConstruct/issues/2776

**Comment by Utildayael** [comment] 2017-02-19 19:36
Ya this has been a bug for a long time. The workaround is to turn off the item rendering in Tinkers but that sucks. Something Mek is doing really pisses it off and makes you crash to desktop repeatedly while crafting *some* stuff in there. Haven't found a trend as it seems to be random but I know I was making a jetpack once on a crafting table and it did that.

**Comment by yepidoodles** [comment] 2017-02-19 19:52
As far as I can tell it's due to the excessive amount Mekanism uses NBT data.

**Comment by Utildayael** [comment] 2017-02-20 00:38
Gotta be honest, this bug has been around for at least 6+ months, possibly entire life of 1.10.x Mek. I think I have an open bug on it too...

**Comment by aidancbrady** [comment] 2017-03-08 23:45
I've tried every logical and hacky fix to get the TC rendering working but I just can't seem to figure it out.  Closing, but I'll still try and find a fix when I have a chance.

**Closed by aidancbrady** 2017-03-08 23:45 UTC

**Comment by Utildayael** [comment] 2017-03-09 00:54
Thanks Aidan. This thing has been hell since it's a full client crash.

**Comment by Bluexin** [comment] 2017-03-11 02:02
What I've done on my end (band-aid solution) was just a try-catch to ignore the error. Renders still fine in the world etc and just doesn't render as a model on top of the Tinker's Crafting Station.

**Comment by OrdinatorStouff** [comment] 2017-11-06 18:44
Per https://github.com/aidancbrady/Mekanism/issues/4798 @Alphanos discovered a link to `alwaysSetupTerrainOffThread` Forge config as having an impact on whether this crash happens or not. Perhaps this is new clues to tracking down what could be causing these Tinker's render issues?

**Comment by thiakil** [comment] 2017-11-07 01:14
@OrdinatorStouff we fixed this in Mekanism a while ago by checking for an OpenGL context before doing the hacky stuff. Any relation to it happening in the recent issue with Mekanism items is likely coincidence.

We check for device capabilities which will throw the no context exception (which we catch). I'm not sure how that would cause issues with the thread that actually has the context.

**Comment by Alphanos** [comment] 2017-11-07 02:03
If the current crash involves Mekanism items only by coincidence, does that mean that I should be reporting the current issue to Forge?  I don't have much experience knowing whether Forge issues are typically reported by end users or by mod developers.  Thanks!

**Comment by thiakil** [comment] 2017-11-07 02:07
If it's crashing in a Tinkers table, likely no.

Can it be reproduced with just Mek & Tinkers & `alwaysSetupTerrainOffThread`?

**Comment by Alphanos** [comment] 2017-11-07 03:30
> Can it be reproduced with just Mek & Tinkers & alwaysSetupTerrainOffThread?

Yes.  When alwaysSetupTerrainOffThread is enabled, the crash can be reproduced with only Mekanism and Tinker's Construct.

**Comment by thiakil** [comment] 2017-11-07 07:10
:thinking:
