### ISSUE TITLE
Server crashes with Mekanism Generators

### ISSUE THREAD

**Issue by Kohtachan** [aidancbrady/Mekanism#4837] opened 2017-11-29 18:57 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:

Hi!
If i use the Mekanism Generator Mod, my server crashes. 
Hope you can fix the Problem. 

Thx

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

---- Minecraft Crash Report ----

WARNING: coremods are present:
  Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
Contact their authors BEFORE contacting forge

// Would you like a cupcake?

Time: 29.11.17 19:48
Description: Exception in server tick loop

net.minecraftforge.fml.common.LoaderExceptionModCrash: Caught exception from MekanismGenerators (mekanismgenerators)
Caused by: java.lang.IllegalStateException: Gasses must be registered before postInit.
	at com.google.common.base.Preconditions.checkState(Preconditions.java:444)
	at mekanism.api.gas.GasRegistry.checkPhase(GasRegistry.java:120)
	at mekanism.api.gas.GasRegistry.register(GasRegistry.java:22)
	at mekanism.generators.common.MekanismGenerators.postInit(MekanismGenerators.java:121)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at net.minecraftforge.fml.common.FMLModContainer.handleModStateEvent(FMLModContainer.java:606)
	at sun.reflect.GeneratedMethodAccessor10.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:253)
	at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:231)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.google.common.eventbus.Subscriber.invokeSubscriberMethod(Subscriber.java:91)
	at com.google.common.eventbus.Subscriber$SynchronizedSubscriber.invokeSubscriberMethod(Subscriber.java:150)
	at com.google.common.eventbus.Subscriber$1.run(Subscriber.java:76)
	at com.google.common.util.concurrent.MoreExecutors$DirectExecutor.execute(MoreExecutors.java:399)
	at com.google.common.eventbus.Subscriber.dispatchEvent(Subscriber.java:71)
	at com.google.common.eventbus.Dispatcher$PerThreadQueuedDispatcher.dispatch(Dispatcher.java:116)
	at com.google.common.eventbus.EventBus.post(EventBus.java:217)
	at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:148)
	at net.minecraftforge.fml.common.Loader.initializeMods(Loader.java:724)
	at net.minecraftforge.fml.server.FMLServerHandler.finishServerLoading(FMLServerHandler.java:107)
	at net.minecraftforge.fml.common.FMLCommonHandler.onServerStarted(FMLCommonHandler.java:336)
	at net.minecraft.server.dedicated.DedicatedServer.func_71197_b(DedicatedServer.java:219)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:484)
	at java.lang.Thread.run(Unknown Source)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_131, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 546287072 bytes (520 MB) / 1681391616 bytes (1603 MB) up to 1901592576 bytes (1813 MB)
	JVM Flags: 0 total; 
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.1.2555 43 mods loaded, 43 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State | ID                  | Version                  | Source                                           | Signature                                |
	|:----- |:------------------- |:------------------------ |:------------------------------------------------ |:---------------------------------------- |
	| UCHIJ | minecraft           | 1.12.2                   | minecraft.jar                                    | None                                     |
	| UCHIJ | mcp                 | 9.42                     | minecraft.jar                                    | None                                     |
	| UCHIJ | FML                 | 8.0.99.99                | minecraft_server.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | forge               | 14.23.1.2555             | minecraft_server.jar                             | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| UCHIJ | opencomputers|core  | 1.7.0.20                 | minecraft.jar                                    | None                                     |
	| UCHIJ | securitycraft       | v1.8.2.4                 | [1.12+] SecurityCraft v1.8.2.4.jar               | None                                     |
	| UCHIJ | appliedenergistics2 | rv5-stable-3             | appliedenergistics2-rv5-stable-3.jar             | None                                     |
	| UCHIJ | baubles             | 1.5.1                    | Baubles-1.12-1.5.1.jar                           | None                                     |
	| UCHIJ | bibliocraft         | 2.4.3                    | BiblioCraft[v2.4.3][MC1.12.0].jar                | None                                     |
	| UCHIJ | botania             | r1.10-350                | Botania r1.10-350.jar                            | None                                     |
	| UCHIJ | buildcraftlib       | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftcore      | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftbuilders  | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftenergy    | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftfactory   | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftrobotics  | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcraftsilicon   | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | buildcrafttransport | 7.99.12                  | buildcraft-7.99.12.jar                           | None                                     |
	| UCHIJ | codechickenlib      | 3.1.3.313                | CodeChickenLib-1.12-3.1.3.313-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | ic2                 | 2.8.16-ex112             | industrialcraft-2-2.8.16-ex112.jar               | de041f9f6187debbc77034a344134053277aa3b0 |
	| UCHIJ | compactsolars       | 1.12.2-5.0.17.340        | CompactSolars-1.12.2-5.0.17.340-universal.jar    | None                                     |
	| UCHIJ | computercraft       | 1.80pr1                  | ComputerCraft1.80pr1.jar                         | None                                     |
	| UCHIJ | ptrmodellib         | 1.0.0                    | Decocraft-2.5.2_1.12.2.jar                       | None                                     |
	| UCHIJ | props               | 2.5.2                    | Decocraft-2.5.2_1.12.2.jar                       | None                                     |
	| UCHIJ | enderstorage        | 2.4.0.122                | EnderStorage-1.12-2.4.0.122-universal.jar        | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | jei                 | 4.8.4.130                | jei_1.12.2-4.8.4.130.jar                         | None                                     |
	| UCHIJ | forestry            | 5.7.0.213                | forestry_1.12.2-5.7.0.213.jar                    | None                                     |
	| UCHIJ | waila               | 1.8.22                   | Hwyla-1.8.22-B37_1.12.jar                        | None                                     |
	| UCHIJ | igwmod              | 1.4.3-14                 | IGW-Mod-1.12.2-1.4.3-14-universal.jar            | None                                     |
	| UCHIJ | inventorytweaks     | 1.63+release.109.220f184 | InventoryTweaks-1.63.jar                         | 55d2cd4f5f0961410bf7b91ef6c6bf00a766dcbe |
	| UCHIJ | journeymap          | 1.12.2-5.5.2             | journeymap-1.12.2-5.5.2.jar                      | None                                     |
	| UCHIJ | mantle              | 1.12-1.3.1.21            | Mantle-1.12-1.3.1.21.jar                         | None                                     |
	| UCHIJ | mekanism            | 9.4.2                    | Mekanism-1.12.2-9.4.2.327.jar                    | None                                     |
	| UCHIE | mekanismgenerators  | 9.4.2                    | MekanismGenerators-1.12.2-9.4.2.327.jar          | None                                     |
	| UCHIJ | mekanismtools       | 9.4.2                    | MekanismTools-1.12.2-9.4.2.327.jar               | None                                     |
	| UCHIJ | morpheus            | 1.12-3.3.2               | Morpheus-1.12-3.3.2.jar                          | None                                     |
	| UCHIJ | nei                 | ${mod_version}           | NotEnoughItems-1.12-2.4.0.231-universal.jar      | f1850c39b2516232a2108a7bd84d1cb5df93b261 |
	| UCHIJ | opencomputers       | 1.7.0.20                 | OpenComputers-MC1.12.1-1.7.0.20.jar              | None                                     |
	| UCHIJ | pneumaticcraft      | 1.12.2-0.1.0-47          | pneumaticcraft-repressurized-1.12.2-0.1.0-47.jar | None                                     |
	| UCHIJ | tconstruct          | 1.12-2.7.4.34            | TConstruct-1.12-2.7.4.34.jar                     | None                                     |
	| UCHIJ | trashslot           | 8.4.6                    | TrashSlot_1.12.1-8.4.6.jar                       | None                                     |
	| UCHIJ | bspkrscore          | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                   | None                                     |
	| UCHIJ | treecapitator       | at_0.9                   | Treecapitator-1.12-at_0.9a.jar                   | None                                     |

	Loaded coremods (and transformers): 
Inventory Tweaks Coremod (InventoryTweaks-1.63.jar)
  invtweaks.forge.asm.ContainerTransformer
TransformerLoader (OpenComputers-MC1.12.1-1.7.0.20.jar)
  li.cil.oc.common.asm.ClassTransformer
	AE2 Version: stable rv5-stable-3 for Forge 14.23.1.2554
	Pulsar/tconstruct loaded Pulses: 
		- TinkerCommons (Enabled/Forced)
		- TinkerWorld (Enabled/Not Forced)
		- TinkerTools (Enabled/Not Forced)
		- TinkerHarvestTools (Enabled/Forced)
		- TinkerMeleeWeapons (Enabled/Forced)
		- TinkerRangedWeapons (Enabled/Forced)
		- TinkerModifiers (Enabled/Forced)
		- TinkerSmeltery (Enabled/Not Forced)
		- TinkerGadgets (Enabled/Not Forced)
		- TinkerOredict (Enabled/Forced)
		- TinkerIntegration (Enabled/Forced)
		- TinkerFluids (Enabled/Forced)
		- TinkerMaterials (Enabled/Forced)
		- TinkerModelRegister (Enabled/Forced)
		- wailaIntegration (Enabled/Not Forced)

	AE2 Integration: IC2:ON, RC:OFF, MFR:OFF, Waila:ON, Mekanism:ON, OpenComputers:ON, THE_ONE_PROBE:OFF, TESLA:OFF, CRAFTTWEAKER:OFF
	Profiler Position: N/A (disabled)
	Is Modded: Definitely; Server brand changed to 'fml,forge'
	Type: Dedicated Server (map_server.txt)

**Comment by MasterGeneral156** [comment] 2017-11-29 20:27
Can confirm this is happening to me as well.

**Comment by thommy101** [comment] 2017-11-29 21:19
Hi, thanks for reporting. This is however a duplicate of #4827.

**Closed by thommy101** 2017-11-29 21:19 UTC
