### ISSUE TITLE
dynamic tank mysteriously empty

### ISSUE THREAD

**Issue by kotoroshinoto** [aidancbrady/Mekanism#4206] opened 2017-02-15 23:02 UTC
on MC version 1.10.2, tossed mekanism into the direwolf20 pack
using forge 12.18.3.2185

a tank that had been filled mostly with creosote oil is now empty. 

I have no idea what might have led to that (i've restarted the server twice since I looked at it last)

**Comment by thommy101** [comment] 2017-02-16 13:19
Duplicate of #3715 (atleast)

**Closed** 2017-04-26 05:56 UTC
