### ISSUE TITLE
freezes(lagg) logs spammed with errors.

### ISSUE THREAD

**Issue by jules103** [aidancbrady/Mekanism#2059] opened 2014-12-26 15:11 UTC
I got some wierd problems and i think its mekanism related and maybe something with Cofh since i see the ASM event handler inthere, It occurs every 6 to 12hours and it makes the server unplayable.

were running modsauce 1.0.1.0 and the problems were there in 1.0.0.6 too.

Here are the versions that i use.

1.0.1.0 - Mekanism-1.7.10-7.1.1.127
1.0.1.0 - CoFHCore-[1.7.10]3.0.0B8-36
1.0.1.0 - CoFHLib-[1.7.10]1.0.0B6-26
1.0.0.6 - Mekanism-1.7.10-7.1.1.127
1.0.0.6 - CoFHCore-[1.7.10]3.0.0B6-32
1.0.0.6 - CoFHLib-[1.7.10]1.0.0B6-26

the error itself, came back every 6 to 12 hours after a restart and ocurred every 10 - 20 secconds:
http://pastebin.com/7S4L7J3B

I hope some1 can help me with this would be nice! Thanks in advance!

**Comment by vavraCZe** [comment] 2015-01-01 23:15
It's horrible spam. Mekanism 7.1.1

hastebin.com/ajifoxeraf.avrasm
hastebin.com/qeyuqokeho.avrasm

server have 20TPS with this spam, but players have lot of lags and kick with reason "time out"...


I tried MekanismDebug and it is little different, but same spam.

hastebin.com/qojolowuto.avrasm

It´s mekanism only or something else?

**Comment by jules103** [comment] 2015-01-02 16:31
Do i need to give more info or are we waiting for the mekanism dev to reply here?
My forum with some screens from what is happening the profile images are not verry accurate i can provide more specific profiler images:
http://zenixgo.enjin.com/forum/m/27460712/viewthread/17999365-modsauce-freeze-aka-lagg-spike-problem

I had some people complaining about lagg and dcs when using/setting up the digiminer.
and in the error i wonder what this means:
net.minecraft.block.BlockStaticLiquid.func_149674_a(BlockStaticLiquid.java:95)

Could it be something with un chunkloaded mekanism machines?

**Comment by jules103** [comment] 2015-01-02 16:32
Thanks for thinking with me by the way! really appreciated!

**Comment by jules103** [comment] 2015-01-02 16:33
for now we've written an auto restart script so my players can play without lagg however the log is still almost unreadable.

**Comment by unpairedbracket** [comment] 2015-01-02 16:50
Well, it looks like what I was trying to do there didn't work at all. I'm going to try something that should stop the ConcurrentModificationExceptions but I worry that it'll just cause a deadlock. Weird stuff like this tends to be caused by chunk-thrashing so if you could try chunkloading the networks that are causing the issue and see if it goes away, that could be helpful. I'll see if I can get another debug build out and see how that works as well.

**Comment by unpairedbracket** [comment] 2015-01-02 16:54
A full log with the last debug build could also be helpful, if you're able to send one.

**Comment by jules103** [comment] 2015-01-02 17:00
booting up with the debug atm!

**Comment by jules103** [comment] 2015-01-02 17:24
ive put the debug in and the server crashed as soon as some1 logged in, ive tested  it 3times and its caused by the debug version, somehow its a ticking entity (buildcraft laser), then ive put the original mekanism in i can enter that area without crashing the server then ive put the debug in cant enter that area insta crash.
Heres the error:
Time: 1/2/15 6:01 PM
Description: Ticking entity

java.lang.NoSuchMethodError: buildcraft.api.core.Position.writeData(Lio/netty/buffer/ByteBuf;)V
	at buildcraft.core.LaserData.writeData(LaserData.java:88)
	at buildcraft.silicon.TileLaser.writeData(TileLaser.java:280)
	at buildcraft.core.network.PacketUpdate.writeData(PacketUpdate.java:54)
	at buildcraft.core.utils.Utils.toPacket(Utils.java:538)
	at buildcraft.core.TileBuildCraft.func_145844_m(TileBuildCraft.java:111)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)
-- Head --
Stacktrace:
	at buildcraft.core.LaserData.writeData(LaserData.java:88)
	at buildcraft.silicon.TileLaser.writeData(TileLaser.java:280)
	at buildcraft.core.network.PacketUpdate.writeData(PacketUpdate.java:54)
	at buildcraft.core.utils.Utils.toPacket(Utils.java:538)
	at buildcraft.core.TileBuildCraft.func_145844_m(TileBuildCraft.java:111)
	at net.minecraft.entity.player.EntityPlayerMP.func_147097_b(EntityPlayerMP.java:699)
	at net.minecraft.entity.player.EntityPlayerMP.func_70071_h_(EntityPlayerMP.java:374)
	at net.minecraft.world.World.func_72866_a(World.java:2647)
	at net.minecraft.world.WorldServer.func_72866_a(WorldServer.java:838)
	at net.minecraft.world.World.func_72870_g(World.java:2600)

-- Entity being ticked --
Details:
	Entity Type: null (micdoodle8.mods.galacticraft.core.entities.player.GCEntityPlayerMP)
	Entity ID: 2267
	Entity Name: Pils78
	Entity's Exact location: 32.04, 71.00, 1915.68
	Entity's Block location: World: (32,71,1915), Chunk: (at 0,4,11 in 2,119; contains blocks 32,0,1904 to 47,255,1919), Region: (0,3; contains chunks 0,96 to 31,127, blocks 0,0,1536 to 511,255,2047)
	Entity's Momentum: 0.00, -0.08, 0.00
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:2412)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:669)

-- Affected level --
Details:
	Level name: world
	All players: 2 total; [GCEntityPlayerMP['Hawaiian_Slime'/1269, l='world', x=-1028.71, y=65.00, z=1595.60](Hawaiian_Slime at -1028.7054698995832,65.0,1595.5966599613612), GCEntityPlayerMP['Pils78'/2267, l='world', x=32.04, y=71.00, z=1915.68](Pils78 at 32.03681661383794,71.0,1915.6791250158994)]
	Chunk stats: ServerChunkCache: 2187 Drop: 0
	Level seed: 1099286778931053256
	Level generator: ID 04 - BIOMESOP, ver 0. Features enabled: true
	Level generator options: 
	Level spawn location: World: (-97,75,1481), Chunk: (at 15,4,9 in -7,92; contains blocks -112,0,1472 to -97,255,1487), Region: (-1,2; contains chunks -32,64 to -1,95, blocks -512,0,1024 to -1,255,1535)
	Level time: 38204832 game time, 40525856 day time
	Level dimension: 0
	Level storage version: 0x04ABD - Anvil
	Level weather: Rain time: 182581 (now: false), thunder time: 81002 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
Stacktrace:
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:943)
	at net.minecraft.server.dedicated.DedicatedServer.func_71190_q(DedicatedServer.java:423)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:798)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:658)
	at java.lang.Thread.run(Thread.java:745)

-- System Details --
Details:
	Minecraft Version: 1.7.10
	Operating System: Linux (amd64) version 3.2.0-4-amd64
	Java Version: 1.7.0_65, Oracle Corporation
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 4688041952 bytes (4470 MB) / 6407585792 bytes (6110 MB) up to 6407585792 bytes (6110 MB)
	JVM Flags: 8 total; -Xms6G -Xmx6G -XX:PermSize=512M -XX:+UseParNewGC -XX:+UseConcMarkSweepGC -XX:ParallelGCThreads=4 -XX:+CMSIncrementalPacing -XX:+AggressiveOpts

**Comment by unpairedbracket** [comment] 2015-01-02 17:35
I forgot that my IDE's build system confuses gradle... Redownloading it should fix that issue.

**Comment by jules103** [comment] 2015-01-02 18:05
nobody can connect with the new version: error occured connection terminated

**Comment by unpairedbracket** [comment] 2015-01-02 18:38
I've uploaded a new Debug version that attempts to fix the issue. If you get issues with nobody being able to connect again, pastebin a log and I'll see if I can work out what the problem is.

**Comment by jules103** [comment] 2015-01-08 17:37
got the debug working now waiting for the error to appear!

**Comment by jules103** [comment] 2015-01-08 18:03
when i fly in specific areas i get : a fatal error has ocurred connection terminated.
When i relog i immeaditly get that message. No spammed log with that error yet.

**Comment by jules103** [comment] 2015-01-08 18:23
no i can log on but it seems that the debug gives no errors

**Comment by unpairedbracket** [comment] 2015-01-08 18:28
I guess it's fixed the CME then. I'll close this for now - if you have more issues with connection being terminated, open another issue for that, I think it's unrelated. Build server is down at the moment but these changes will be in the next build, whenever that's able to happen.

**Closed by unpairedbracket** 2015-01-08 18:28 UTC

**Comment by jules103** [comment] 2015-01-08 21:17
without the debug version u made the errors show again.
Ty anyways for the help
