### ISSUE TITLE
solar evaporation plant controller crash

### ISSUE THREAD

**Issue by minecraftmodding1224** [aidancbrady/Mekanism#2931] opened 2015-08-25 09:16 UTC
when i right click on the controller with nothing in my hand,it crashes,and i need it to produce brine...can anyone help or also have this issue?if you need logs,you can go to the minecraft forums,page 100 or you can download it  at your nearest computer convienience store located here:
https://www.dropbox.com/s/olotozvd4acy8dm/crash-2015-08-25_09.51.03-client.txt?dl=1

**Comment by minecraftmodding1224** [comment] 2015-08-25 09:22
if you need logs,you can go to the minecraft forums,page 100 or you can download it  at your nearest computer convienience store located here:
https://www.dropbox.com/s/olotozvd4acy8dm/crash-2015-08-25_09.51.03-client.txt?dl=1

**Comment by ruifung** [comment] 2015-08-27 07:00
LOL? "Download it at your nearest computer convenience store located here"
I feel the taint of a translation program here. Or auto correct, Or just someone with a (interesting) sense of humor.

**Comment by notcake** [comment] 2015-08-27 16:52
This is a duplicate of https://github.com/aidancbrady/Mekanism/issues/2931.
Make sure your solar evaporation plant structure is complete before right clicking the controller.

I can reproduce this crash with Mekanism 8.1.5.240 by constructing a complete solar evaporation plant, breaking a solar evaporation block off it and right clicking the controller. I don't know if this is fixed in the latest version of Mekanism.

**Comment by hugebones** [comment] 2015-08-31 08:15
For me, this only occurs when you extend the plant below the bottom layer...
I was trying to extend it from 10 layers to 18 but not stop it functioning.
However, I right click the controller and it crashes my game. But, I think I screwed it up because the new layers are touching the bottom of the plant.

Anyway, it is quite an annoying bug, especially for large modpacks that take ages to load.

**Closed** 2015-11-20 15:49 UTC
