### ISSUE TITLE
Mek Generators + BC = Crash

### ISSUE THREAD

**Issue by ProxyPlayerHD** [aidancbrady/Mekanism#4533] opened 2017-07-16 14:56 UTC
newest Forge Version (13.20.1.2414)
newest Mek. Versions (9.3.2.307)
newest BC Verison (7.99.6)
[REPORT](https://pastebin.com/5eHkwqjp)

**Comment by thommy101** [comment] 2017-07-16 15:05
Please use the search functionality. 
Duplicate of #4513

**Comment by ProxyPlayerHD** [comment] 2017-07-16 15:14
oops, sorry.

**Comment by thiakil** [comment] 2017-07-17 12:37
@ProxyPlayerHD you are able to close your own issue btw

**Closed** 2017-07-17 15:54 UTC

**Comment by ProxyPlayerHD** [comment] 2017-07-20 14:01
oh i didn't knew that.
