### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by MrHelp** [aidancbrady/Mekanism#2480] opened 2015-04-06 15:53 UTC
Oh god. You don't know what you doing with Apllied Energistics 2? Really? When i update mekanism. I don't see craft on too much thing in AE2 mode. Okay(i think) i will turned back. And what i see? oh shit! I see crafts in AE2 again! So. Yesterday i try update mekanism too. What i see? AGAIN THIS BUG!

**Comment by aidancbrady** [comment] 2015-04-06 15:59
Please everyone stop with these troll issue reports. The issue is fixed on AE2's end, they just haven't pushed the release yet.

**Closed by aidancbrady** 2015-04-06 15:59 UTC
