### ISSUE TITLE
Ticking block entity Crash on 8.1.6.249

### ISSUE THREAD

**Issue by AltonV** [aidancbrady/Mekanism#2858] opened 2015-07-26 09:55 UTC
After upgrading to version 8.1.6.249 I got this crash when loading a world
http://pastebin.com/CujMzBZC

I went back to 8.1.5.246 and it loaded fine.

**Comment by ruifung** [comment] 2015-07-26 13:33
Duplicate of #2844 
I uploaded a fixed build there.

**Closed** 2015-07-26 18:23 UTC
