### ISSUE TITLE
[1.10.2] Tubes/universal cables disappearing

### ISSUE THREAD

**Issue by bernds** [aidancbrady/Mekanism#4405] opened 2017-05-30 19:23 UTC
The following happens when using Mechanism in the All the Mods pack. The version seems to be 9.2.2.301.

I've built up a small machine park using Mekanism, but I can't use universal cables or the pressurized tubes: they disappear whenever I return from the Nether. The following appears to be a relevant section from the log file. Please let me know if you require any other information.

Description: Ticking block entity

java.lang.NullPointerException: Ticking block entity
	at mcmultipart.network.MessageMultipartChange.toBytes(MessageMultipartChange.java:51)
	at mcmultipart.network.MessageSplit.split(MessageSplit.java:94)
	at mcmultipart.network.MessageMultipartChange.send(MessageMultipartChange.java:142)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:340)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:330)
	at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:193)
	at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
	at mekanism.common.multipart.PartPressurizedTube.func_73660_a(PartPressurizedTube.java:78)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at mcmultipart.network.MessageMultipartChange.toBytes(MessageMultipartChange.java:51)
	at mcmultipart.network.MessageSplit.split(MessageSplit.java:94)
	at mcmultipart.network.MessageMultipartChange.send(MessageMultipartChange.java:142)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:340)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:330)
	at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:193)
	at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
	at mekanism.common.multipart.PartPressurizedTube.func_73660_a(PartPressurizedTube.java:78)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)

-- Block entity being ticked --
Details:
	Name: mcmultipart:multipart.ticking // mcmultipart.block.TileMultipartContainer.Ticking
	Block type: ID #1695 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (13,68,695), Chunk: (at 13,4,7 in 0,43; contains blocks 0,0,688 to 15,255,703), Region: (0,1; contains chunks 0,32 to 31,63, blocks 0,0,512 to 511,255,1023)
	Actual block type: ID #1695 (tile.null // mcmultipart.block.BlockMultipartContainer)
	Actual block data value: 0 / 0x0 / 0b0000
Stacktrace:
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:748)

**Comment by thommy101** [comment] 2017-05-30 19:49
Please use the search functionality, this is reported multiple times. 
Duplicate of #4374

**Closed** 2017-05-30 19:51 UTC
