### ISSUE TITLE
mekanism crush

### ISSUE THREAD

**Issue by Elf1966** [aidancbrady/Mekanism#4454] opened 2017-06-08 16:19 UTC
when you try to put in the precision sawmill fence is crash the server/client. only on version 1.11.2

**Comment by ktole1999** [comment] 2017-06-08 16:25
please post crash log

**Comment by Elf1966** [comment] 2017-06-08 16:29
---- Minecraft Crash Report ----

WARNING: coremods are present:
  IC2core (industrialcraft-2-2.7.59-ex111.jar)
  Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  BetterFontsCore (TTFR-1.11.2-1.7.3.jar)
  NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  CoreLoader (RemoteIO-0.0.5-universal (1).jar)
  AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.0f.jar)
  CorePlugin (FluxedRedstone-2.6.1.59.jar)
  RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
  LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  AstralCore (astralsorcery-1.4.1.jar)
  MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
Contact their authors BEFORE contacting forge

// I let you down. Sorry :(

Time: 6/7/17 7:20 PM
Description: Updating screen events

java.lang.NullPointerException: Updating screen events
	at mekanism.common.util.StackUtils.copy(StackUtils.java:156)
	at mekanism.common.recipe.outputs.ChanceOutput.copy(ChanceOutput.java:112)
	at mekanism.common.recipe.machines.SawmillRecipe.copy(SawmillRecipe.java:27)
	at mekanism.common.recipe.machines.SawmillRecipe.copy(SawmillRecipe.java:7)
	at mekanism.common.recipe.RecipeHandler.getChanceRecipe(RecipeHandler.java:398)
	at mekanism.common.inventory.container.ContainerChanceMachine.func_82846_b(ContainerChanceMachine.java:96)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at mekanism.client.gui.GuiMekanism.func_73864_a(GuiMekanism.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at mekanism.client.gui.GuiMekanism.func_146274_d(GuiMekanism.java:265)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1695)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1056)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:372)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at mekanism.common.util.StackUtils.copy(StackUtils.java:156)
	at mekanism.common.recipe.outputs.ChanceOutput.copy(ChanceOutput.java:112)
	at mekanism.common.recipe.machines.SawmillRecipe.copy(SawmillRecipe.java:27)
	at mekanism.common.recipe.machines.SawmillRecipe.copy(SawmillRecipe.java:7)
	at mekanism.common.recipe.RecipeHandler.getChanceRecipe(RecipeHandler.java:398)
	at mekanism.common.inventory.container.ContainerChanceMachine.func_82846_b(ContainerChanceMachine.java:96)
	at net.minecraft.inventory.Container.func_184996_a(Container.java:237)
	at net.minecraft.client.multiplayer.PlayerControllerMP.func_187098_a(PlayerControllerMP.java:551)
	at net.minecraft.client.gui.inventory.GuiContainer.func_184098_a(GuiContainer.java:632)
	at net.minecraft.client.gui.inventory.GuiContainer.func_73864_a(GuiContainer.java:391)
	at mekanism.client.gui.GuiMekanism.func_73864_a(GuiMekanism.java:191)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:544)
	at mekanism.client.gui.GuiMekanism.func_146274_d(GuiMekanism.java:265)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:512)

-- Affected screen --
Details:
	Screen name: mekanism.client.gui.GuiPrecisionSawmill

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Elf1966'/253, l='MpServer', x=468.49, y=67.00, z=-279.30]]
	Chunk stats: MultiplayerChunkCache: 272, 272
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-57,75,-97), Chunk: (at 7,4,15 in -4,-7; contains blocks -64,0,-112 to -49,255,-97), Region: (-1,-1; contains chunks -32,-32 to -1,-1, blocks -512,0,-512 to -1,255,-1)
	Level time: 17261059 game time, 5790225 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 40 total; [EntityPlayerSP['Elf1966'/253, l='MpServer', x=468.49, y=67.00, z=-279.30], EntityFrogs['Frog'/393, l='MpServer', x=528.27, y=66.00, z=-267.65], EntityFrogs['Frog'/408, l='MpServer', x=505.31, y=68.00, z=-243.52], EntityFrogs['Frog'/410, l='MpServer', x=522.49, y=66.00, z=-267.16], EntityFrogs['Frog'/412, l='MpServer', x=532.42, y=64.00, z=-280.18], EntityFrogs['Frog'/413, l='MpServer', x=528.22, y=67.00, z=-286.35], EntityFrogs['Frog'/420, l='MpServer', x=464.74, y=62.94, z=-218.46], EntityFrogs['Frog'/426, l='MpServer', x=505.34, y=67.00, z=-262.69], EntityFrogs['Frog'/427, l='MpServer', x=517.52, y=66.00, z=-280.81], EntityXPOrb['Сфера опыта'/299, l='MpServer', x=371.25, y=62.00, z=-173.75], EntityFrogs['Frog'/428, l='MpServer', x=519.34, y=66.00, z=-278.15], EntityXPOrb['Сфера опыта'/300, l='MpServer', x=371.25, y=62.00, z=-173.75], EntityFrogs['Frog'/429, l='MpServer', x=511.95, y=66.00, z=-273.33], EntityFrogs['Frog'/430, l='MpServer', x=510.44, y=67.00, z=-279.49], EntityFrogs['Frog'/433, l='MpServer', x=527.50, y=63.00, z=-295.16], EntityFrogs['Frog'/434, l='MpServer', x=520.53, y=63.00, z=-292.20], EntityMountableObject['entity.MountableObject.name'/311, l='MpServer', x=479.50, y=67.44, z=-281.50], EntitySkeleton['Скелет'/439, l='MpServer', x=493.73, y=68.00, z=-315.51], EntityMountableObject['entity.MountableObject.name'/312, l='MpServer', x=479.50, y=67.44, z=-279.50], EntityMountableObject['entity.MountableObject.name'/313, l='MpServer', x=479.50, y=67.44, z=-281.50], EntityChickLeghorn['Леггорн Цыплёнок'/441, l='MpServer', x=466.47, y=11.00, z=-264.27], EntityCowLonghorn['Лонгхорн Корова'/315, l='MpServer', x=443.22, y=62.32, z=-337.24], EntityCowLonghorn['Лонгхорн Корова'/316, l='MpServer', x=442.24, y=62.58, z=-341.21], EntityBullLonghorn['Лонгхорн Бык'/317, l='MpServer', x=445.61, y=62.30, z=-339.16], EntitySheep['Овца'/320, l='MpServer', x=397.77, y=64.00, z=-358.63], EntityFrogs['Frog'/453, l='MpServer', x=499.62, y=65.00, z=-337.23], EntitySheep['Овца'/456, l='MpServer', x=458.91, y=63.00, z=-300.15], EntitySheep['Овца'/457, l='MpServer', x=445.79, y=63.00, z=-306.39], EntityCowLonghorn['Лонгхорн Корова'/460, l='MpServer', x=458.75, y=61.74, z=-316.20], EntitySheep['Овца'/461, l='MpServer', x=459.47, y=63.00, z=-306.21], EntityFrogs['Frog'/334, l='MpServer', x=448.88, y=65.00, z=-232.40], EntityFrogs['Frog'/337, l='MpServer', x=425.39, y=66.00, z=-234.34], EntityFrogs['Frog'/338, l='MpServer', x=427.13, y=63.00, z=-286.62], EntityAncientGolem['Ancient Golem'/339, l='MpServer', x=436.26, y=13.00, z=-298.54], EntitySheep['Овца'/340, l='MpServer', x=459.92, y=63.00, z=-301.25], EntityHenLeghorn['Леггорн Курица'/341, l='MpServer', x=434.13, y=60.00, z=-315.56], EntityFrogs['Frog'/342, l='MpServer', x=444.63, y=63.00, z=-318.18], EntityXPOrb['Сфера опыта'/344, l='MpServer', x=573.79, y=66.00, z=-170.14], EntityCreeper['Крипер'/1369, l='MpServer', x=496.50, y=16.00, z=-322.50], EntityZombie['Зомби'/1242, l='MpServer', x=498.52, y=53.00, z=-278.27]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Non-integrated multiplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2655)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:393)
	at net.minecraft.client.main.Main.main(SourceFile:124)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.11.2
	Operating System: Windows 7 (amd64) version 6.1
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 684417080 bytes (652 MB) / 2845310976 bytes (2713 MB) up to 3817865216 bytes (3641 MB)
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx4096m -Xms256m -XX:PermSize=256m
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.38 Powered by Forge 13.20.0.2304 71 mods loaded, 71 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJA	minecraft{1.11.2} [Minecraft] (minecraft.jar) 
	UCHIJA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJA	forge{13.20.0.2304} [Minecraft Forge] (forge-1.11.2-13.20.0.2304.jar) 
	UCHIJA	advancedrocketrycore{1} [Advanced Rocketry Core] (minecraft.jar) 
	UCHIJA	betterfonts{1.7.3} [BetterFonts] (minecraft.jar) 
	UCHIJA	ccl-entityhook{1.0} [ccl-entityhook] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJA	libvulpes{0.2.3b.} [Vulpes library] (LibVulpes-1.11.2-0.2.3b-universal.jar) 
	UCHIJA	advancedrocketry{1.2.0f} [Advanced Rocketry] (AdvancedRocketry-1.11.2-1.2.0f.jar) 
	UCHIJA	animania{1.1.2} [Animania] (animania-1.11.2-1.1.2.jar) 
	UCHIJA	astralsorcery{1.4.1} [Astral Sorcery] (astralsorcery-1.4.1.jar) 
	UCHIJA	baubles{1.4.5} [Baubles] (Baubles-1.11-1.4.5.jar) 
	UCHIJA	bibliocraft{2.3.1} [BiblioCraft] (BiblioCraft[v2.3.1][MC1.11.2].jar) 
	UCHIJA	chameleon{1.11.2-3.1.0} [Chameleon] (Chameleon-1.11.2-3.1.0.jar) 
	UCHIJA	codechickenlib{2.6.0.254} [CodeChicken Lib] (CodeChickenLib-1.11.2-2.6.0.254-universal.jar) 
	UCHIJA	chickenchunks{2.3.0.63} [ChickenChunks] (ChickenChunks-1.11.2-2.3.0.63-universal.jar) 
	UCHIJA	chiselsandbits{13.10} [Chisels & Bits] (chiselsandbits-13.10.jar) 
	UCHIJA	ic2{2.7.59-ex111} [IndustrialCraft 2] (industrialcraft-2-2.7.59-ex111.jar) 
	UCHIJA	compactsolars{1.11.2-5.0.12.333} [Compact Solar Arrays] (CompactSolars-1.11.2-5.0.12.333-universal.jar) 
	UCHIJA	compactstorage{2.2} [CompactStorage] (CompactStorage-2.2.jar) 
	UCHIJA	crafttweakerjei{1.0.1} [CraftTweaker JEI Support] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJA	jei{4.4.1.285} [Just Enough Items] (jei_1.11.2-4.4.1.285.jar) 
	UCHIJA	crafttweaker{3.0.25} [Crafttweaker] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJA	ctgui{1.0.0} [CT-GUI] (CraftTweaker-1.11.2-3.0.25.jar) 
	UCHIJA	cyclicmagic{1.5.1} [Cyclic] (Cyclic-1.11.2-1.5.1.jar) 
	UCHIJA	cyclopscore{0.10.4} [Cyclops Core] (CyclopsCore-1.11.2-0.10.4.jar) 
	UCHIJA	elevatorid{1.3.2} [Elevator Mod] (ElevatorMod-1.11.2-1.3.2.jar) 
	UCHIJA	embers{0.214} [Embers] (embers-0.214.jar) 
	UCHIJA	enderstorage{1.0} [EnderStorage] (EnderStorage-1.11.2-2.3.0.112-universal.jar) 
	UCHIJA	energyconverters{1.0} [Energy Converters] (energyconverters_1.11.2-0.6.0.13.jar) 
	UCHIJA	evilcraft{0.10.26} [EvilCraft] (EvilCraft-1.11.2-0.10.26.jar) 
	UCHIJA	fastleafdecay{v12} [Fast Leaf Decay] (FastLeafDecay-v12.jar) 
	UCHIJA	finite-water-control{1.0} [finite-water-control] (finite-water-control-1.11.2-1.0.jar) 
	UCHIJA	flinttools{1.1.8} [Flint Tools] (Flint Tools 1.1.8.jar) 
	UCHIJA	reborncore{2.16.1.115} [Reborn Core] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCHIJA	reborncore-mcmultipart{2.16.1.115} [reborncore-MCMultiPart] (RebornCore-1.11.2-2.16.1.115-universal.jar) 
	UCHIJA	fluxedredstone{@MODVERSION@} [FluxedRedstone] (FluxedRedstone-2.6.1.59.jar) 
	UCHIJA	funkylocomotion{1.0} [Funky Locomotion] (funky-locomotion-1.11.2-alpha-0.0.1.jar) 
	UCHIJA	gravestone{1.7.2} [Gravestone] (GraveStone Mod 1.7.2.jar) 
	UCHIJA	hopperducts{1.4.9} [Hopper Ducts] (hopperducts-mc1.11.2-1.4.9.jar) 
	UCHIJA	icb{1.11.2-0.1.2} [Industrial-Conveyor-Belts] (icb-0.1.2.jar) 
	UCHIJA	inventorytweaks{1.62+beta.89.be6ffe4} [Inventory Tweaks] (InventoryTweaks-1.62+beta.89.jar) 
	UCHIJA	journeymap{1.11.2-5.4.6} [JourneyMap] (journeymap-1.11.2-5.4.6.jar) 
	UCHIJA	malisiscore{1.11.2-5.1.1} [MalisisCore] (malisiscore-1.11.2-5.1.1.jar) 
	UCHIJA	malisisdoors{1.11.2-6.1.0} [MalisisDoors] (malisisdoors-1.11.2-6.1.0.jar) 
	UCHIJA	mekanism{9.3.1} [Mekanism] (Mekanism-1.11.2-9.3.1.305.jar) 
	UCHIJA	mekanismgenerators{9.3.1} [MekanismGenerators] (MekanismGenerators-1.11.2-9.3.1.305.jar) 
	UCHIJA	mekanismtools{9.3.1} [MekanismTools] (MekanismTools-1.11.2-9.3.1.305.jar) 
	UCHIJA	mtrm{1.2.1.23} [MineTweakerRecipeMaker] (MineTweakerRecipeMaker-1.11.2-1.2.1.23.jar) 
	UCHIJA	missing_pieces{4.2.1} [Missing Pieces] (missing_pieces-1.11.2-4.2.1.jar) 
	UCHIJA	mob_grinding_utils{0.2.0} [mob_grinding_utils] (MobGrindingUtils-0.2.0.jar) 
	UCHIJA	modnametooltip{1.7.1} [Mod Name Tooltip] (modnametooltip_1.11-1.7.1.jar) 
	UCHIJA	moreoverlays{1.11} [MoreOverlays] (moreoverlays-1.11-mc1.11.2.jar) 
	UCHIJA	mousetweaks{2.8} [Mouse Tweaks] (MouseTweaks-2.8-mc1.11.2.jar) 
	UCHIJA	recipehandler{0.8} [NoMoreRecipeConflict] (NoMoreRecipeConflict-0.8(1.11).jar) 
	UCHIJA	nuclearcraft{2.2d} [NuclearCraft] (NuclearCraft-2.2d--1.11.2.jar) 
	UCHIJA	randomthings{3.8.1} [Random Things] (RandomThings-MC1.11.2-3.8.1.jar) 
	UCHIJA	redstonepaste{1.7.4} [Redstone Paste] (redstonepaste-mc1.11.2-1.7.4.jar) 
	UCHIJA	refinedstorage{1.4.10} [Refined Storage] (refinedstorage-1.4.10.jar) 
	UCHIJA	remoteio{0.0.5} [RemoteIO] (RemoteIO-0.0.5-universal (1).jar) 
	UCHIJA	rftools{6.01} [RFTools] (rftools-1.1x-6.01.jar) 
	UCHIJA	rftoolscontrol{1.6.8} [RFTools Control] (rftoolsctrl-1.1x-1.6.8.jar) 
	UCHIJA	roots{0.018} [Roots 2] (roots-2-0.018.jar) 
	UCHIJA	stevescarts{2.3.0.22} [Steve's Carts 2] (StevesCarts-1.11.2-2.3.0.22.jar) 
	UCHIJA	storagedrawers{1.11.2-4.2.7} [Storage Drawers] (StorageDrawers-1.11.2-4.2.7.jar) 
	UCHIJA	theoneprobe{1.4.7} [The One Probe] (theoneprobe-1.1x-1.4.7.jar) 
	UCHIJA	toolbelt{1.6.1} [Tool Belt] (ToolBelt-1.11.2-1.6.1.jar) 
	UCHIJA	va{1.11.2-1.0} [Vanilla Automation] (va-1.11.2-1.0.jar) 
	UCHIJA	vanillatools{1.0.5} [Vanilla Tools] (vanillatools-1.1x-1.0.6.jar) 
	UCHIJA	waterworks{1.11.2-1.0.1} [Waterworks] (Waterworks-1.11.2-1.0.1.jar) 
	UCHIJA	xnet{1.3.2} [XNet] (xnet-1.3.2.jar) 
	Loaded coremods (and transformers): 
IC2core (industrialcraft-2-2.7.59-ex111.jar)
  
Inventory Tweaks Coremod (InventoryTweaks-1.62+beta.89.jar)
  invtweaks.forge.asm.ContainerTransformer
BetterFontsCore (TTFR-1.11.2-1.7.3.jar)
  cubex2.ttfr.BFClassTransformer
NWRTweak (redstonepaste-mc1.11.2-1.7.4.jar)
  net.fybertech.nwr.NWRTransformer
CCLCorePlugin (CodeChickenLib-1.11.2-2.6.0.254-universal.jar)
  codechicken.lib.asm.ClassHierarchyManager
  codechicken.lib.asm.CCL_ASMTransformer
CoreLoader (RemoteIO-0.0.5-universal (1).jar)
  me.dmillerw.remoteio.asm.transformer.CoreTransformer
AdvancedRocketryPlugin (AdvancedRocketry-1.11.2-1.2.0f.jar)
  zmaster587.advancedRocketry.asm.ClassTransformer
CorePlugin (FluxedRedstone-2.6.1.59.jar)
  
RebornCoreASM (RebornCore-1.11.2-2.16.1.115-universal.jar)
  reborncore.mixin.transformer.MixinTransformer
LoadingPlugin (RandomThings-MC1.11.2-3.8.1.jar)
  lumien.randomthings.asm.ClassTransformer
AstralCore (astralsorcery-1.4.1.jar)
  
MalisisCorePlugin (malisiscore-1.11.2-5.1.1.jar)
  net.malisis.core.util.chunkcollision.ChunkCollisionTransformer
  net.malisis.core.util.chunkblock.ChunkBlockTransformer
  net.malisis.core.renderer.transformer.MalisisRendererTransformer
  net.malisis.core.renderer.icon.asm.TextureMapTransformer
  net.malisis.core.util.clientnotif.ClientNotifTransformer
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 378.66' Renderer: 'GeForce GTX 650/PCIe/SSE2'
	chickenchunks Invalid Fingerprint Reports: - No invalid fingerprints.: 
	enderstorage Invalid Fingerprint Reports: - No invalid fingerprints.: 
	RebornCore: 
		Plugin Engine: 0
		RebornCore Version: 2.16.1.115
		Mixin Status: 1
		Runtime Debofucsation 1
		RenderEngine: 0
	Launched Version: forge-13.20.0.2304
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 650/PCIe/SSE2 GL version 4.5.0 NVIDIA 378.66, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: Русский (Россия)
	Profiler Position: N/A (disabled)
	CPU: 4x AMD FX(tm)-4100 Quad-Core Processor

**Comment by thommy101** [comment] 2017-06-08 17:01
Please use the search functionality as this has been reported and is just the 4th issue from the top.
Duplicate of #4447

**Closed** 2017-06-10 17:49 UTC

**Comment by PapiDimmi** [comment] 2017-11-24 18:35
I, too, have a crush on Mekanism.
