### ISSUE TITLE
[Crash] Resistive Heater

### ISSUE THREAD

**Issue by SPK44** [aidancbrady/Mekanism#4137] opened 2017-01-09 04:25 UTC
This crash comes from the resistive heater being attached to two Thermal Evaporation Towers at once. It does not immediately crash the game. But when moving far enough away from the setup, then coming back, the game lags significantly, messes up rendering, and crashes with the attached crash log. A temporary solution seems to be connecting the heater to a thermal pipe, then connecting to the towers.

Side Note: Resistive Heaters do not rotate with rotate mode on the configurator, they only rotate using the wrench mode. 

Crash running Infinity Lite 1.5.1, newest version of Mekanism (to date)
Configs are default, except machine effects are turned off.

[crash-2017-01-08_21.34.59-client.txt](https://github.com/aidancbrady/Mekanism/files/692690/crash-2017-01-08_21.34.59-client.txt)

Screen shot of setup before rerender:
![2017-01-08_23 15 22](https://cloud.githubusercontent.com/assets/10950495/21757182/f3f17fe8-d5f8-11e6-873d-2ec354eee4b3.png)

Screen shot of setup after rerender:
![2017-01-08_23 15 59](https://cloud.githubusercontent.com/assets/10950495/21757193/059c6780-d5f9-11e6-81c4-b76ec69978c8.png)

Interestingly enough. When I only did it once to reproduce it, the game did not crash, but did create the render glitches. In both EnderIO and Mekanism pipes.

When there where 7 heaters, the game crashed, and lagged more.

**Comment by thommy101** [comment] 2017-01-09 07:35
Duplicate of issue #4066

**Closed** 2017-04-13 20:55 UTC
