### ISSUE TITLE
Crash when coming back from the nether (loading server?)

### ISSUE THREAD

**Issue by siccaxe** [aidancbrady/Mekanism#4385] opened 2017-05-25 06:36 UTC
The only recent addition to my base was 30 blocks of ultimate mechanical pipe from SEP to ES. Perhaps the issue was due to them being in the middle of filling their buffer?

at mcmultipart.network.MessageMultipartChange.toBytes(MessageMultipartChange.java:51)
	at mcmultipart.network.MessageSplit.split(MessageSplit.java:94)
	at mcmultipart.network.MessageMultipartChange.send(MessageMultipartChange.java:142)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:340)
	at mcmultipart.multipart.Multipart.sendUpdatePacket(Multipart.java:330)
	at mekanism.common.multipart.PartSidedPipe.func_73660_a(PartSidedPipe.java:193)
	at mekanism.common.multipart.PartTransmitter.func_73660_a(PartTransmitter.java:59)
	at mekanism.common.multipart.PartMechanicalPipe.func_73660_a(PartMechanicalPipe.java:73)
	at mcmultipart.block.TileMultipartContainer$Ticking.func_73660_a(TileMultipartContainer.java:328)
	at net.minecraft.world.World.func_72939_s(World.java:1804)
	at net.minecraft.world.WorldServer.func_72939_s(WorldServer.java:620)
	at net.minecraft.server.MinecraftServer.func_71190_q(MinecraftServer.java:709)
	at net.minecraft.server.MinecraftServer.func_71217_p(MinecraftServer.java:613)
	at net.minecraft.server.integrated.IntegratedServer.func_71217_p(IntegratedServer.java:240)
	at net.minecraft.server.MinecraftServer.run(MinecraftServer.java:471)
	at java.lang.Thread.run(Thread.java:745)

details if you want/need them. Thanks!

Mekanism-1.10.2-9.2.2.301

**Comment by thommy101** [comment] 2017-05-25 07:25
Duplicate of #4374

**Closed** 2017-05-25 15:03 UTC
