### ISSUE TITLE
[Suggestion] Solar Evaporation Plant Computer port/lua support

### ISSUE THREAD

**Issue by MJRLegends** [aidancbrady/Mekanism#3143] opened 2016-03-21 15:49 UTC
I think it would be cool to have a computer port for the Solar Evaporation Plant so you can monitor the towers,

Added these methods:
getInputFluidName() - To get the name of the fluid being piped in, so Water or Brine
getOutputFluidName() - To get the name of the fluid being piped in, so Lithium or Brine
getInputFluidAmount() - To get amount of liquid stored in the input tank (mb)
getOutputFluidAmount() - To get amount of liquid stored in the output tank (mb)
getHeight() - To get the tower height
isFormed() - Check its formed (maybe this one wouldnt work because the tower would have to be formed to use the port in the first place?)
getMultiplier() - Check the multiplier for the biome its in
getPowerStored() - To see how much power is stored in it

Extra possible features:
setActive(boolean) - To turn the tower on and off, maybe it could be added to the GUI and LUA support?

**Comment by Landrash** [comment] 2016-03-22 07:27
Duplicate of #3116

**Comment by MJRLegends** [comment] 2016-03-22 07:29
This is not a duplicate of my other issue post as this one is do with something else compared to that one

**Comment by Landrash** [comment] 2016-03-22 07:51
Oh, I'm sorry. I read the other one as a generalized request to extend the lua support of mekanism blocks and machines.

**Comment by aidancbrady** [comment] 2016-03-22 21:18
New method list:
- "getTemperature"
- "getHeight"
- "isFormed" 
- "getInput" (fluid amount)
- "getOutput" (fluid amount)

Hope that helps :)

**Closed by aidancbrady** 2016-03-22 21:18 UTC

**Comment by MJRLegends** [comment] 2016-03-22 21:19
Sweet thanks

**Comment by MJRLegends** [comment] 2016-05-27 00:05
@aidancbrady any chance we could get a get getMaxInput and getMaxOutput and getEnergyStored and getProductionTick too?
