### ISSUE TITLE
Using the Configurator disconnects you from the server. 

### ISSUE THREAD

**Issue by InflamedSebi** [aidancbrady/Mekanism#4865] opened 2017-12-15 12:58 UTC
#### Issue description:
Using the Configurator disconnects you from the server. Only occurs in SMP, not SSP.
https://minecraft.curseforge.com/projects/modern-skyblock-2/issues/489

#### Steps to reproduce:
1. Just change some pipes to push/pull

**Forge:** Forge 14.23.1.2562 
**Mekanism:** Mekanism-1.12.2-9.4.2.327
**Modpack version:** Modern Skyblock-2.7.3.1 (also happened in previous versions)

no crashlog, since it is not a crash.
but here is the forge log of the disconnect: https://pastebin.com/9vbKFkBY

**Comment by thommy101** [comment] 2017-12-15 14:24
Please use search, duplicate of #4835

**Closed by thommy101** 2017-12-15 14:24 UTC
