### ISSUE TITLE
[1.7.10] [Cardboard Box] changing item ID after unboxing

### ISSUE THREAD

**Issue by flaviocysne** [aidancbrady/Mekanism#4397] opened 2017-05-29 14:44 UTC
Environment
==========

Modpack: Project Ozone 2 - 2.2.7 EFU4
Minecraft version: 1.7.10

Issue
====

- How to reproduce the issue?
Place a Filing Cabinet, from Extra Utilities, then box it with a Cardboard Box.
After this unbox it.

- What was expected to happen and what did really happen?
Expected: Filing Cabinet placed back in the world.
Happened: An Advanced Filing Cabinet is placed instead.

**Comment by thommy101** [comment] 2017-05-29 18:06
1.7.10 isn't supported anymore. Focus has shifted towards 1.11.2.
Also sounds like a duplicate of issue #3930

**Closed** 2017-05-29 19:49 UTC
