### ISSUE TITLE
Dupe with Fluid Tanks [1.7.10]

### ISSUE THREAD

**Issue by LorenzoDCC** [aidancbrady/Mekanism#3964] opened 2016-11-11 03:11 UTC
https://www.youtube.com/watch?v=f1FXvH6g7NE&feature=youtu.be

Running Meka 9.1 and Forge 10.13.4.1614

**Comment by Eufranio** [comment] 2016-11-11 03:15
Confirm it's duping.

**Comment by evernife** [comment] 2017-01-14 03:17
any progress?

**Comment by Eufranio** [comment] 2017-01-14 03:18
Looks like 1.7.10 is getting no updated anymore: https://github.com/aidancbrady/Mekanism/commits/1.7.10

**Comment by evernife** [comment] 2017-01-14 03:20
Not asking for a big update, this seems to be easily fixable ....
Like blocking shift click in the gui '-'

If i could do i would, but i dont know how :V

**Comment by ThatGamerBlue** [comment] 2017-01-14 08:00
1.7.10 isn't supported. Sorry.

**Comment by thommy101** [comment] 2017-01-14 18:10
Can't reproduce on 1.10. Seems to be fixed in one of the many commits between 1.7.10 and 1.10 or upstream (Forge).

**Closed** 2017-03-29 03:04 UTC
