### ISSUE TITLE
[1.12] Electrolytic Separator + Energy Upgrades = Hydrogen Power

### ISSUE THREAD

**Issue by VT-14** [aidancbrady/Mekanism#4852] opened 2017-12-07 20:02 UTC
#### Issue description:
The Electrolytic Separator accepts Energy Upgrades.  In the past, this only increased the energy capacity.  The Electrolytic Separator was the only machine to not receive a boost in efficiency in order to prevent an infinite energy loop using Hydrogen Gas.

The Electrolytic Separator currently does get the energy boost and can produce an infinite energy loop using Hydrogen Gas.

#### Steps to reproduce:
1. Stick a full set of Energy Upgrades in the Electrolytic Separator.
2. Supply Water
3. Burn Hydrogen in a Gas-Burning Generator for 10x the power you put in.  A full set of Speed Upgrades will net you nearly 18k J/t.

#### Version (make sure you are on the latest version before reporting):
**Forge: 14.23.1.2561**
**Mekanism: 9.4.2.327**

Test pack included Mek Generators and Tools, and JEI 4.8.5.134.  No other mods.

**Comment by Lukas45** [comment] 2017-12-08 15:48
Did a bit of testing. A single, fully upgraded Electrolytic Separator can generate 40.96k rf/t, given you have 6+ Gas-Burning Generators to burn the Hydrogen.
Tested with 5, 6, 10, 15, 30, 45 and 60 Gas-Burning Generators on a single Separator. All gave the same result (due to burn rate)

**Comment by thommy101** [comment] 2017-12-16 12:37
Confirmed. Exactly the point @VT-14 described.. Electrolytic separator should not be more efficient when it has energy upgrades, it should only be able to store more energy.

**Comment by thommy101** [comment] 2017-12-16 15:17
Made a PR which fixes this issue.

**Comment by aidancbrady** [comment] 2017-12-22 18:43
Merging PR, will be fixed

**Closed by aidancbrady** 2017-12-22 18:43 UTC
Labels: bug, confirm, Has PR

**Comment by taj1994** [comment] 2017-12-22 18:49
Personally, I think if this is changed, it should be a config option that is enabled by default. That way, if people want to make it easier on themselves, they can go change it, but anybody that either a.) doesn't care, b.) wants to keep it a bit more difficult, or c.) doesn't know how to modify config files can leave it and get the "standard" Mekanism experience

**Comment by VT-14** [comment] 2017-12-22 18:55
@taj1994 you might as well give the Creative Energy Cell a crafting recipe with a recipe changer mod if you want to make it easier on yourself.

Seriously, the Thermal Expansion Creative Energy Cell transfers 25,000 RF/t from each side.  This generates over 36,000 RF/t per generator and is trivial to set up.

**Comment by thommy101** [comment] 2017-12-22 23:07
It's now not possible to make a positive outcome on the mentioned setup, you'll make a net loss. It's not configurable to make either more efficient.
If you (or a modpack creator) want to make it easier, best thing you can do is what @VT-14 said
