### ISSUE TITLE
Bug in all tanks

### ISSUE THREAD

**Issue by HeberonYT** [aidancbrady/Mekanism#4182] opened 2017-02-04 19:55 UTC
In the 4 tanks (basic, advanced, elite, ultimate) objects are duplicated very simply.
See the video for more information.

**`https://youtu.be/XPp6wN9AZLE`**

**Comment by ThatGamerBlue** [comment] 2017-02-05 08:32
Minecraft version? Mekanism version? Does it work in singleplayer?

**Comment by Ricket** [comment] 2017-02-05 18:49
In addition, can you try to eat or use the apples and show that they are real? It might be simply a client-side UI bug.

**Comment by HeberonYT** [comment] 2017-02-05 19:01
@ThatGamerBlue Obviously I use one of the most recent versions, but that's your job, so start investigating, or do you also want me to tell you which line of code you should change? ...

**Comment by Ricket** [comment] 2017-02-05 20:40
Well yes, if you aren't going to provide the necessary information then it does sound like you need to tell us what line of code to change.

Also this is actually nobody's job, and your demands will fall on deaf ears.

**Comment by VT-14** [comment] 2017-02-05 21:16
Unable to reproduce with only Mekanism 1.10.2-9.2.1.289 and Forge 12.18.3.2221.  I took another look at the video and saw that it was in Minecraft 1.7.10 (I hope).  Again, unable to reproduce with Mek 1.7.10-9.1.0.281 and Forge 10.13.4.1614.  Most likely a mod interaction or outdated Mekanism.  No way to really test without poking at random which no one is willing to do; especially after how idiotic the "that's your job" statement was.

Unless @HeberonYT wants to contribute to a community that only exists because of people freely contributing their spare time, this topic isn't going anywhere.

**Comment by bookerthegeek** [comment] 2017-02-10 21:44
@VT-14 , Yes this is for 1.7.10 and I know that it is EOL. Knowing that I would still love a fix it is at all possible.

Versions:
- Minecraft 1.7.10
- Mekanism-1.7.10-9.1.0.281
- MekanismGenerators-1.7.10-9.1.0.281
- MekanismTools-1.7.10-9.1.0.281
- forge-10.13.4.1614

How to reproduce:

1. Place tank in world
2. Empty Inventory
3. Place any item in the Top/Right spot of your inventory. It will work in other spots, but it is random if it works
4. Shift Right Click on the item
5. Profit

Also, Duplicate of https://github.com/aidancbrady/Mekanism/issues/3964

**Closed** 2017-03-29 03:04 UTC
