### ISSUE TITLE
Crash when loading world

### ISSUE THREAD

**Issue by PapiDimmi** [aidancbrady/Mekanism#4825] opened 2017-11-24 18:01 UTC
I installed some new mods, and now, I crash upon loading the world.

**Crash report**: https://pastebin.com/raw/cbNMdCci

Right before I crashed, I could look around for a few seconds, but everything was white. Here’s a screenshot:

![mekanism visual glitch](https://user-images.githubusercontent.com/25916106/33220558-9294b75e-d149-11e7-8bcb-8033f7b61613.png)

This was on a LAN server. The _host_ of the LAN server did not crash or experience any glitches, but I did.

I did install a few new mods, but I have no idea what could possibly cause this.

****

**Minecraft version**: 1.12.2
**Forge version**: 14.23.0.2552
**Mekanism version**: 9.4.1.326

**Comment by PapiDimmi** [comment] 2017-11-24 20:08
Actually, it affects the host too.

The server host did not experience the visual glitch where everything turns white, but he did crash.

**Crash report**: https://pastebin.com/raw/ZTdsMTNq

It seems to be an issue with Tinkers’ Construct, maybe. I’m not sure.

This never happened before I installed some new mods.
Here’s a list of the new mods that I added to my modpack:

* EnergeticSheep
* Blur
* Simply Tea
* Personal Cars
* Morph
* MagicBooks2
* DecoCraft2
* NetherPortalFix
* Wither Skeleton Tweaks
* Hats
* Assisted Progression
* Nucleus (dependency for Assisted Progression)
* SlimyBoyos
* GLASS
* Better Foliage
* Hat Stand
* Mob Dismemberment
* Shatter
* Back Tools
* Block Drops (JEI Addon)
* Combustive Fishing
* Gravity Gun
* Torched
* Bee Barker
* Chunk Animator
* Durability Show
* Better Advancements
* Mob Amputation
* Primitive Mobs
* Reborn Storage
* BuildCraft
* NoNausea
* MalisisDoors
* MalisisCore (dependency for MalisisDoors)
* Deep Resonance
* ElecCore (dependency for DeepResonance)
* BetterFps
* MeeCreeps
* TorchMaster
* Duck Craft
* Simple Corn
* Redstone Remote
* IC2Magma
* SecretRoomsMod
* Immersive HempCraft
* ChocoCraft
* Defiled Lands
* Food Expansion
* SaltyMod
* VanillaFoodPantry
* Trail Mix
* Tinker I/O
* Reinforced Pumpkin
* Immersive Tech
* Proxy
* Anima Mundi
* Soot
* “To the Bat Poles!”
* Colytra
* Bedrock Ores
* Skye’s Donuts
* Giacomo’s Bookshelf
* NetherEx
* NoFov

What mod do you think could have caused this?

**Comment by PapiDimmi** [comment] 2017-11-24 20:12
Looks like this is a duplicate of #4487, #4700, and #4822, but this issue hasn’t been fixed yet.

**Comment by thommy101** [comment] 2017-11-24 20:17
The second one is indeed a duplicate of those. Which is fixed, but not yet released.
The first one is another crash though. Something with fluids which cannot be rendered.

**Comment by PapiDimmi** [comment] 2017-11-24 20:23
@thommy101 Regarding the first issue, why have I never experienced it until now? Since it never happened before I installed a bunch of new mods, it must be a conflict with one of the new mods, right?

Regarding the second issue, I’m using the newest version of Mekanism on CurseForge, and it still occurs. Do I have to download [these](http://maven.thiakil.com/Mekanism/1.12.1-9.4.1.8bbef954/)—and if so, do I need all of them, only MekanismAll, or all of them **but** MekanismAll?

**Comment by PapiDimmi** [comment] 2017-11-24 20:40
I replaced Mekanism, MekanismTools, and MekanismGenerators with [these ones](http://maven.thiakil.com/Mekanism/1.12.1-9.4.1.8bbef954/), but I crashed on startup again.

**Crash report**: https://pastebin.com/raw/CP59EAff

I can’t load my world at all. Is there a version that fixes the second crash related to Tinkers’ Construct, and is the first crash related to fluids going to be checked out?

**Comment by PapiDimmi** [comment] 2017-11-24 20:46
I replaced Mekanism, MekanismTools, and MekanismGenerators with [these ones](http://maven.thiakil.com/Mekanism/1.12.1-9.4.1.8bbef954/), but I crashed on startup again.

**Crash report**: https://pastebin.com/raw/CP59EAff

I can’t load my world at all. Is there a version that fixes the second crash related to Tinkers’ Construct, and is the first crash related to fluids going to be checked out? Or perhaps someone could help me figure out what mod is causing the first crash so that I can remove it.

**Comment by PapiDimmi** [comment] 2017-11-24 21:21
The Tinkers’ Construct-related crash doesn’t seem to happen anymore, but the fluid-related crash does.

I reinstalled my modpack but to no avail. Any help would be greatly appreciated.

**Comment by thiakil** [comment] 2017-11-25 04:58
That latest one is in another mod; `jaopca`

The Fluid one seems to be a mod that possibly registered its fluid after the texture stitch event, where the code seems to cache fluid textures. The crashing part of it we can fix.

**Comment by PapiDimmi** [comment] 2017-11-25 04:59
Do you know what causes the fluid issue? Is it one of the mods I installed?

**Comment by thiakil** [comment] 2017-11-25 05:02
actually, looking further into it, I'm not sure how there could be null there, since the keys are based on an enum with 2 values... So either another mod is screwing with it, or something went seriously wrong

**Comment by PapiDimmi** [comment] 2017-11-25 05:14
😕

**Comment by thiakil** [comment] 2017-11-25 05:37
you can try this build: http://maven.thiakil.com/Mekanism/1.12.2-9.4.2.indev-5d8b5c8/

NB: the one at the bottom (without a specifier) is the all-in-one, otherwise you can grab core/tools/generators as desired.

**Comment by PapiDimmi** [comment] 2017-11-25 05:45
Which one do you mean? The one at the bottom is a “sha1” file, whatever that is. Shouldn’t it be a JAR file?

Also, is MekanismGenerators and MekanismTools included in it?

**Comment by thiakil** [comment] 2017-11-25 05:49
Well, the jar file at the bottom. Yes thats what I mean by all-in-one

**Comment by PapiDimmi** [comment] 2017-11-25 05:50
You mean `Mekanism-1.12.2-9.4.2.indev-5d8b5c8.jar`?

**Comment by thiakil** [comment] 2017-11-25 05:51
yes.

**Comment by PapiDimmi** [comment] 2017-11-25 05:52
Okay. I will try it. Thank you.

**Closed** 2017-12-03 06:38 UTC
Labels: Waiting Feedback
