### ISSUE TITLE
Crash with Logistical Sorter

### ISSUE THREAD

**Issue by Staegrin** [aidancbrady/Mekanism#2865] opened 2015-07-27 21:44 UTC
I was using a logistical sorter to pull items from an inventory and transferring them into an ultimate logistics cable.

Then I added the filter with Material cobblestone and clicked save.
The game crashed to desktop. Logging into the world crashes it again to desktop.
crashlog:
https://gist.github.com/Staegrin/8d8feabbd409d70e0c0f

full log file:
https://gist.github.com/Staegrin/aef6e317a66c9e2857dc

**Comment by harley9699699** [comment] 2015-07-28 01:58
Mine's not crashing, but my logistical sorter's not painting ingots any more.

**Comment by ruifung** [comment] 2015-07-28 02:30
See #2864 Fix is there.

**Comment by ruifung** [comment] 2015-07-28 02:41
@harley9699699 What do you mean not painting ingots?

**Comment by harley9699699** [comment] 2015-07-28 03:06
When the ingots leave the sorter, they're not 'painted'/colorized to go into the color-coded sorting system.

**Comment by ruifung** [comment] 2015-07-28 04:22
That's just you though, it doesn't happen to me?

**Comment by harley9699699** [comment] 2015-07-28 04:39
Grrrrr. Worked until the update. Even replaced that particular sorter. grrrrr

**Comment by ruifung** [comment] 2015-07-28 04:48
Mind posting some screenshots of your setup?

**Comment by harley9699699** [comment] 2015-07-28 11:14
![2015-07-28_06 07 27](https://cloud.githubusercontent.com/assets/2501047/8929987/58dd8714-34ef-11e5-83f2-7734d2c2aa79.png)
![2015-07-28_06 06 08](https://cloud.githubusercontent.com/assets/2501047/8929988/58e66c26-34ef-11e5-80e9-d038b0b3c448.png)
![2015-07-28_06 06 17](https://cloud.githubusercontent.com/assets/2501047/8929989/58f1afc8-34ef-11e5-9af9-72d604f50b79.png)
![2015-07-28_06 06 26](https://cloud.githubusercontent.com/assets/2501047/8929990/58fb80c0-34ef-11e5-9d58-9054da76629e.png)
![2015-07-28_06 06 36](https://cloud.githubusercontent.com/assets/2501047/8929991/59093e4a-34ef-11e5-8276-1c952f5f995e.png)
![2015-07-28_06 06 45](https://cloud.githubusercontent.com/assets/2501047/8929992/5914337c-34ef-11e5-938f-d5b8c83d3480.png)
![2015-07-28_06 07 00](https://cloud.githubusercontent.com/assets/2501047/8929993/59247f5c-34ef-11e5-9fd6-59ffcbfe9f47.png)
![2015-07-28_06 07 03](https://cloud.githubusercontent.com/assets/2501047/8929994/592ddcb4-34ef-11e5-9865-610ad7fde99d.png)

The last one shows the only way, right now, that the iron works---by leaving it unmarked and open.
Notice the iron ingots running through the system aren't marked/colored.

**Comment by ruifung** [comment] 2015-07-28 11:22
Does it happen all the time? Or only on that particular setup - I still can't reproduce it using a small 1 source / 2 destination setup?

**Comment by harley9699699** [comment] 2015-07-28 11:24
All the time. Worked fine/perfect  before.

**Comment by ruifung** [comment] 2015-07-28 11:34
Still can't seem to reproduce... 
My test setup:
https://imgur.com/a/Gkmg4

**Comment by harley9699699** [comment] 2015-07-28 11:39
That's SO strange. I'll tear it apart later and get back here. I just.don't.understand.

**Comment by harley9699699** [comment] 2015-07-28 12:15
Very quickly switched dusts---didn't mark Any of the ingots on the way out. :(

**Comment by ruifung** [comment] 2015-07-28 12:18
?

**Comment by harley9699699** [comment] 2015-07-28 15:02
Meant, I had only been trying iron, then switched to copper, tin, etc. None of them were marked for sorting.

**Comment by ruifung** [comment] 2015-07-28 15:06
lol.

**Comment by harley9699699** [comment] 2015-07-28 15:11
May be funny to you, but I'm pulling out (what's left of) my hair here. :) Just don't understand how it could work, then not. EVEN thinking about going back to 815. :/

**Comment by harley9699699** [comment] 2015-07-28 16:06
So, I set up a little test one and it doesn't work:
![2015-07-28_11 02 33](https://cloud.githubusercontent.com/assets/2501047/8936550/92fde136-3518-11e5-89a2-0c410ca0d071.png)

**Comment by ruifung** [comment] 2015-07-28 16:29
Right, I see now. It only happens when you are trying to pull directly from a mekanism machine.
I'll make a new issue with that in more detail, but a easy workaround for now is to put a chest as a buffer between your machine and the sorter.

**Comment by harley9699699** [comment] 2015-07-28 16:36
THAT was it!!!!!! Wow, glad you thought of it because I never would have. Geez, that was rough enough. Chest buffer fixed it. Thanks!

**Comment by unpairedbracket** [comment] 2015-07-28 18:19
Try out the new 8.1.7 build, this should be fixed

**Closed** 2015-07-28 20:00 UTC

**Comment by harley9699699** [comment] 2015-07-28 21:45
Regular 817 or with an added part that you've had to fix?
