### ISSUE TITLE
Power loss through infrastructure.

### ISSUE THREAD

**Issue by InfiniteMaximum** [aidancbrady/Mekanism#4686] opened 2017-09-12 19:06 UTC
Relevant info: https://onedrive.live.com/view.aspx?resid=BCAA72FF672DB3E3!17524&ithint=onenote%2c&app=OneNote&authkey=!AA2pwONbJp_7AMA. 

Formatted to instructions minus any required  logs that I may need to present.

**Comment by thiakil** [comment] 2017-09-13 01:44
A) Don't post information like that. Put it in the text of the GH issue and attach the images on github.
B) Did you search at all? Duplicate of #4676

**Closed by thiakil** 2017-09-13 01:44 UTC

**Comment by InfiniteMaximum** [comment] 2017-09-13 02:02
That was the result of an out of date version. I am using an up to date version of mek. I will repost according your guidelines.
