### ISSUE TITLE
Elite Crushing Factory Will Not Process Iron Ore Vanilla.

### ISSUE THREAD

**Issue by GldnSabre74** [aidancbrady/Mekanism#4099] opened 2016-12-28 22:15 UTC
When I place an Vanilla Iron Ore Block into the Elite Factory Crusher it does nothing. Is this intended or a bug. Nothing happens no crash just wont process.

**Comment by jburrows82** [comment] 2016-12-29 00:23
[Crusher](http://wiki.aidancbrady.com/wiki/Crusher) doesn't accept iron ore? Good, that means it's working as intended. I would suspect [the machine](http://wiki.aidancbrady.com/wiki/Enrichment_Chamber) that accepts ores is also working as intended.

Issue is PEBKAC, not mod related. Please close the issue.

**Comment by GldnSabre74** [comment] 2016-12-29 00:47
Just curious why it processes other ores just not iron?

**Comment by tukib** [comment] 2016-12-29 20:09
You use the enrichment chamber to turn ores into dust. The crusher is used for ingots.

**Comment by VT-14** [comment] 2016-12-30 05:06
What ores can be processed in a crusher in your modpack?  Either some other mod is adding recipes to the wrong machine, or the pack has messed up custom recipes.

I think Mekanism only covers Iron, Gold, Copper, Tin, Lead, Silver, and maybe one or two other very common materials.  Everything else comes from other mods or custom recipes.

**Closed** 2017-04-12 14:16 UTC
