### ISSUE TITLE
[1.10.2] Client Crash after teleporting

### ISSUE THREAD

**Issue by UnPure** [aidancbrady/Mekanism#3694] opened 2016-08-25 14:01 UTC
Hey guys.
I'm currently having some issue with the latest version of mekanism.
When i teleport back to my base (doesnt matter which teleport method i'm using) my client is crashing.
The problem is not on my end because its also crashing for everyone else on the server when they teleport to the base.

Crashlog: http://pastebin.com/NfYyx7Xs
If you need any other informations, just tell me what you need.

Mekanism: 9.1.1.290
Forge: 12.18.1.2073

**Comment by Utildayael** [comment] 2016-08-27 02:46
Same issue as #3626 

Aidan said it is fixed but haven't seen the release come out yet with said fix

It's a problem with mechanical pipe rendering, again.

**Comment by ShaCraft** [comment] 2016-08-27 13:29
Are you sure it is Mekanism? I am the one that was testing for #3626. ElecCore seemed to be the issue. On my test server if you removed ElecCore (and anything dependent on it) the crashes stopped. On my test server there are not mechanical pipes in the world. Just wondering what steps you took to come to the conclusion that it was mechanical pipe? or is that just speculation? 

UnPure is that just from using portals? Do teleport pads from RF tools crash the server? As a work around you could use those or DraconicEvolution's Charm of Dislocation till the issue is fixed. 

RG_Sha

**Comment by Utildayael** [comment] 2016-08-27 14:20
Ya. Read the error. Specifically says that. Aidan already confirmed that was the issue and has committed a fix for it. He just hasn't pushed the build out that has said fix. 

I don't use Elecore.

**Comment by UnPure** [comment] 2016-08-27 14:56
@ShaCraft 
I'm using ElecCore but i currently cant test if the issue is fixed when removing it.
Once the committed fix is released i will try to test it if the issue remains.

The bug seems to happen on any teleport back to our base. Doesnt matter if we move through the nether portal or while using the Charged Porter/Matter Receiver from RFtools. I havent tested it with the Charm of Dislocation but i'm pretty sure it will have the same effect.

**Comment by Utildayael** [comment] 2016-08-27 14:58
Fwiw we're using MyCommands and all my crashes were using /home to teleport back to base so it's functionally the same thing. :)

**Closed** 2016-08-27 22:13 UTC

**Comment by Lukas45** [comment] 2016-08-27 23:25
I just had the crash, without a teleport. It was hooked to an ExtraUtils2 lava drum, into a seared tank.
The pipe disconnects for a second, before crashing the client

**Comment by Lukas45** [comment] 2016-08-28 18:35
Got some observation on the crashes
For me, it happens specificly when the Mechanical pipes are connected to a Seared Tank on a Tinkers Construct Smeltery or Seared Furnace.
I had a setup of a ExtraUtils2 drum with Lava, and then connected to 2 Seared Tanks, each in their own structure (Pipe set to PULL on the drum). With that setup, the client would crash every minute or so (enough time for me to remove the pipes). Right before the crash, all the pipes would stop connecting (like when you apply redstone to them).
On an older setup I had 2 Drums (both on PULL) connected to a single Seared Tank, and that was when I experienced what OP has described (crash on loading)

I know it has been said that Aidan already has committed a fix for it, but more info can never hurt?
