### ISSUE TITLE
Gas loadup issue

### ISSUE THREAD

**Issue by NicosaurusRex99** [aidancbrady/Mekanism#4834] opened 2017-11-28 10:41 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
When loading up Mekanism the game crashes because of the gasses

#### Steps to reproduce:
1. Install Mekanism
2. Hit Play
3. Result

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2556
**Mekanism:** 1.12.2.-9.4.2.327
**Other relevant version:** 1.12.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://paste.ee/p/XWjU8

**Comment by Davinjapan** [comment] 2017-11-28 10:59
I am having the same exact problem, I even downloaded the 328 from the website and still have the same problem!
[crash-2017-11-28_19.53.40-client.txt](https://github.com/aidancbrady/Mekanism/files/1509550/crash-2017-11-28_19.53.40-client.txt)

**Comment by wamc2017** [comment] 2017-11-28 11:41
The problem is known: https://github.com/aidancbrady/Mekanism/issues/4827

It's an incompatibility with Buildcraft and already fixed in dev: https://github.com/aidancbrady/Mekanism/commit/17ce49434fc1ed8eb245a596568e2d2af1e8d556

Self compiling is the best bet if you currently want to play with both mods, or wait for the next version. ;)

**Comment by thommy101** [comment] 2017-11-28 11:54
As @wamc2017 said, duplicate of #4827

**Closed by thommy101** 2017-11-28 11:54 UTC
