### ISSUE TITLE
Dynamical Tank flush fluids on Worldload

### ISSUE THREAD

**Issue by cyberpunkbln** [aidancbrady/Mekanism#3715] opened 2016-08-29 04:41 UTC
Hello,

when i leave minecraft and load the world again, the Dynamic Tank flush all liquids (water for me), show the red sparkles for ready and the Pump pump again water in. I have leave my World with a direct view on the Dynamic Tank and with 100% water in it.

thx

Minecraft: 1.10.2
Mekanism: 1.10.2-9.1.1.290

**Comment by rdunham3** [comment] 2016-08-29 18:34
I've found that various Mekanism components seem sensitive to lag from chunks loading and/or unloading. Try putting a chunkloader (from another mod) in the chunk that has the dynamic tank. See if that keeps the tank from emptying.

**Comment by cyberpunkbln** [comment] 2016-08-30 00:28
thx, i will try it :)

**Comment by drstasis** [comment] 2016-12-10 21:22
Some info on this since it appears the issue is still open:
I have a 5x5x3 dynamic tank (showing volume 75) I am using to hold Immersive Engineering biodiesel. It has emptied itself several times. It seems to happen when I connect to the server, but I have not tested this extensively. The last time it did, it showed 528000mB of fluid. I turned to harvest a couple nearby ender lilies. When I turned back, the tank had no fluid in it, though there was still some fluid rendered. I am running Mekanism 9.2.0 on Forge 12.18.2.2124 for Minecraft 1.10.2. The server is on a separate machine from the one I use to play Minecraft.

**Comment by drstasis** [comment] 2016-12-11 22:12
I've done some additional testing, and it looks like I can repeat the problem by placing or removing any block directly adjacent to the tank multiblock. Updating a block in this way resets the fluid in the tank.

**Comment by drstasis** [comment] 2016-12-11 22:29
I've done some more testing and found a way to replicate the issue. Any change to a block adjacent to the tank multiblock (place / break blocks, crops growing, EnderIO pipe changing shape, etc) causes the tank to reset the fluid level to zero.

**Comment by OniKudaki** [comment] 2017-02-11 20:15
This issue still persists. I have a 3x3x10 Dynamic tank for liquid ethylene that loses it's multiblock status and re-forms itself every time I load the save, which causes the loss of all the liquid.

**Comment by kotoroshinoto** [comment] 2017-02-16 14:51
Perhaps the data could be offloaded somewhere until all blocks participating in the structure are removed, resulting in a function similar to how tinker's construct smelteries can retain their fluid when broken and rebuilt. that way, losing and rebuilding its multiblock on load wouldn't cause flushing

**Comment by kotoroshinoto** [comment] 2017-02-16 15:44
Though that would probably require having a block akin to the smeltery controller, which when removed would delete the stored data, unless you wanted to fire an event to check if the structure  was completely removed every time one of the dynamic blocks is broken.

**Comment by aidancbrady** [comment] 2017-04-27 20:43
This should be fixed in 1.11 builds. Not sure why it was an issue in 1.10.

**Closed by aidancbrady** 2017-04-27 20:43 UTC
