### ISSUE TITLE
OreDict config option still broken

### ISSUE THREAD

**Issue by thundR** [aidancbrady/Mekanism#4595] opened 2017-08-05 03:13 UTC
#### Issue description:

#1765 is still a problem. The config option is still there, and it still forces the wrong oredict recipes if set to false. I don't know why the issue was closed in the first place. 

This was 3 years ago, and the latest 1.12 version still has this problem. 
Expected functionality: 
when B:ControlCircuitOreDict=false, mekanism machines can only be crafted with mek circuits.
Actual:
mekanism machines can only be crafted with ic2 circuits.

**Forge:** 14.21.1.2428
**Mekanism:** MekanismAll-1.12-9.3.3.homebaked

**Comment by thommy101** [comment] 2017-08-05 10:51
Can confirm for 1.11 and 1.12.

The config currently only changes whether the control circuits should be oredicted to circuit<tier>. All recipes do not follow this setting and all require the oredicted variant of the circuits. Causing all recipes to be invalid when the setting is disabled and no other mods add circuits.

**Comment by thundR** [comment] 2017-08-05 11:42
I assume this is as simple as changing the recipe jsons to use the actual circuit instead of the oredict entry.

**Comment by thommy101** [comment] 2017-08-05 13:56
That would fix it, but prevents other circuits from being used which is the intention of oredict.

**Comment by thundR** [comment] 2017-08-05 23:19
Right, though I have to say, I can't imagine this being the intended use of oredict when it was created. I've always considered it only for base materials, ingots, stone, glass, wood, etc. 

I'm not sure it's necessary to have complex, multi-machine, multi-step items be defined as functionally equivalent, especially since the only time I've seen this entry used is between IC2 and mek, which completely breaks IC2 progression. My thoughts would be just delete the oredict entry and look into adding a proper config to activate it which would be off by default.

**Comment by thiakil** [comment] 2017-08-06 01:37
@thundR what? the config works fine, it's that the mek recipes depend on it being enabled at current.

**Comment by thundR** [comment] 2017-08-06 01:40
Well yes technically the config does what it's supposed to, but having a config that breaks the mod's recipes if changed is something I would call not intended behavior. If you guys don't agree with this issue, feel free to close it. I can just clone and build with non-oredict recipes, but I would say that this thread is pretty cut and dry in terms of what should be done moving forward.

**Comment by thiakil** [comment] 2017-08-06 02:00
No, I can see there's an issue, my comment was referring to this:

> My thoughts would be just delete the oredict entry and look into adding a proper config to activate it which would be off by default.

This issue is with *Mekanism's recipes*, not the circuits being oredicted themselves.

**Comment by thundR** [comment] 2017-08-06 02:02
Sure, I think we're saying the same thing. I was just thinking out loud, wondering whether or not the circuits should be oredicted at all. A bit of a different issue, but if they weren't, it would make fixing this trivial.

**Comment by thiakil** [comment] 2017-08-06 02:03
> wondering whether or not the circuits should be oredicted at all.

*that's literally what the config option sets*

**Comment by thundR** [comment] 2017-08-06 02:13
I know that, but that's not what the config should toggle. 

Effectively, this is the current setup: Config is true, game works, but IC2 circuits are rendered pointless. Config is false, mek machines only use IC2 circuits and breaks the mods progression. 

It should be something like this: config is true, same thing. config is false, mek circuits are the only usable circuits for mek recipes. 

Maybe I should open a different issue for the third possibility, but it's this: config is deleted from the mod, circuits are not oredicted, mek machines only made with mek circuits. 

I think we've said all that can be said for this issue. I'm not up to date on 1.12 modding, but if it's as simple as replacing all the json's "circuitBasic" entries to mekanism:controlcircuit, I'd be happy to pull req.

**Comment by thiakil** [comment] 2017-08-06 02:26
> It should be something like this: config is true, same thing. config is false, mek circuits are the only usable circuits for mek recipes.

The config controls whether the circuits are registered in the OreDictionary. That part is a non-issue. The issue is that there is no Mekanism recipe for the plain item, so if the oredict reg is not there, the Mekanism recipes won't use Mekanism circuits.

The solution is to **a)** add Mekanism recipes that do not depend on the OreDict, and optionally **b)** add a config to disable the Mekanism recipes that allows oredicted circuits (e.g. Mek circuits are registered and usable by other mods' recipes (controlled by the other config), but mek recipes only work with mek circuits)

**Comment by thundR** [comment] 2017-08-06 02:28
Yep.

**Comment by thommy101** [comment] 2017-08-06 09:24
Fixed in 6bdd00ac49a766900d6a40d6c39426f3d00b212c for 1.12.
It isn't an issue in 1.11

**Closed by thommy101** 2017-08-06 09:24 UTC
Labels: bug, confirm
