### ISSUE TITLE
Movement of teleporter by frame causes render crash on client.

### ISSUE THREAD

**Issue by Deckee** [aidancbrady/Mekanism#2818] opened 2015-07-14 11:54 UTC
crash report
http://paste.ee/p/kcUE0
 
Trying to kill all bugs :)

**Comment by RAWRwins254** [comment] 2015-07-14 22:09
@Deckee this appears to have happened because you were using ProjectRed's implementation of frames PLUS mekanism teleporters (afaik) were never meant to be moved in such a method. Did this ever work in prior versions?

**Comment by Deckee** [comment] 2015-07-15 03:12
I using @rwtema 's FunkyLocomotion not @MrTJP Frames.
The movement of the teleporters Worked in Mek 7 but were not with out there problems.

**Comment by Deckee** [comment] 2015-07-15 03:19
Heres a pic of the set up. 
![2015-07-14_22 16 14](https://cloud.githubusercontent.com/assets/8199121/8690139/0cf45c8e-2a76-11e5-8388-82751e188552.png)
The crash only happens when a player is rendering the teleporter and the frame moves.

**Comment by unpairedbracket** [comment] 2015-07-19 00:36
Well, it's MrTJP's ASM hacks that are causing the crash (or at least that appear in the crashlog). I'll investigate further but you might want to try without that installed.

**Comment by unpairedbracket** [comment] 2015-07-19 00:55
I can confirm this works fine with just Mekanism and Funky Relocation present.

**Comment by MrTJP** [comment] 2015-07-19 00:56
Will take a look...

**Comment by unpairedbracket** [comment] 2015-07-19 00:58
We appear to be being passed a world with a null ChunkProvider?

**Comment by Deckee** [comment] 2015-07-19 01:22
Did some testing  using {mcp, FML, Forge, <CoFH ASM>, CoFHCore, ExtraUtilities, funkylocomotion, Mekanism, MekanismGenerators, MekanismTools, ThermalDynamics, ThermalExpansion, ThermalFoundation, Baubles, ForgeMicroblock, ForgeMultipart, McMultipart, MCFrames, ForgeRelocation, RelocationFMP, MrTJPCoreMod} as my mod list, moved the teleporter with no problems.

**Comment by Deckee** [comment] 2015-07-19 01:38
When anisotropicFiltering is off every block has black lines around it and the teleporter is invisible.

**Comment by unpairedbracket** [comment] 2015-07-19 12:20
Hmm, looks like this may not be your problem after all @MrTJP - I'm getting a similar exception, but for me it's handled by FL so I don't crash, it just doesn't render the teleporter TESR when moving.

**Comment by aidancbrady** [comment] 2015-07-19 19:30
Fixed in 2c88357.

**Closed by aidancbrady** 2015-07-19 19:30 UTC
