### ISSUE TITLE
Transport Cease to Function After a While

### ISSUE THREAD

**Issue by MarshTheBacca** [aidancbrady/Mekanism#5087] opened 2018-06-15 13:50 UTC
### Issue description:

Here's my setup:
I have an ore processing unit that uses digital miners with entangloporters to transfer electricity and the ores between them. I have 5 elite factories for each stage in the or processing flowchart up to the chemical injection chamber which involves the production of hydrogen chloride. I also have 6 thermal towers in a distant desert that also has 36 pumps pumping water into the towers. Another entangloporter transfers electricity to the thermal area and brine back to the ore processing area. It also has an anchor upgrade on it too. At the ore processing area, I have 20 electrolytic separators separating water into H2 and O2. I have another 10 electrolytic separators separating brine into Cl2 and Na, and then 10 chemical infusers fusing together the Cl2 and H2 to make HCl, which feeds into the chemical injection elite factories. The O2 produced at the water area goes into the purification elite factories.
All transport pipes (cables, logistical transporters, mechanical transporters, pressurised pipes) are their ultimate version. All machines involved are all fully upgraded with 8 speed and 8 efficiency.
Currently, there is an energy problem so some of the machines run very slowly, also there is a slight shortage in brine.

The Problem:
When leaving my setup to run while I do other things like manage my AE system and energy sources, I come back to the plant and notice there is no power, some of the gas pipes are filled with gas, but then stop half way down the pipe for no apparent reason, and the input and output logistical transporters are no longer transporting items, and they just remain in the chest buffers, and the brine or water isn't being transported in the mechanical tubes at the ore place nor the thermal place in the desert. My power sources are fine because the machines aren't running because the power cables aren't functioning either because similar to the gas stopping halfway down the pipe, the green texture stops halfway down the cable for no reason. When disconnecting the power cable, I find that some of the machines are still running somehow even when there wasn't power in the first place. Reconnecting the cable gives no green texture to the power network, it's hit and miss to see what cable I need to break and place to get the power working again.
I find the only way to solve these issues is to break every single transporter along it's path, and then replace them and it starts working again, but then i come back 5 minutes later and it's stopped working again. I haven't had this issue when i was first starting my survival and I believe it has something to do with the amount of action going on.
It's really frustrating as this mod is well known for automated machines but I have to keep coming back to my factory more and more frequently to spend ages breaking and replacing pipes.

I have a feeling it's either because I don't have enough RAM, I have 4GB however it never shows 100% usage in F3 UI. I started using 6GB RAM to see if there's a difference and I'll let you know.
Another theory, is that the issue lies with the mekanism portal I use to get to and from the thermal area to sort the broken pipes out. When i jump out of each portal, I see the world around me render by chunk, which is weird because I have anchor upgrades in at least 3 of my machines in both areas, so shouldn't the chunks already be rendered? I think that because the chunks reload, it messes up whatever was in the transport pipes at the time and causes random stops in the pipes.

#### Steps to reproduce:
I'm not really sure how to replicate this, I recommend you just download my save along with my modpack on the Technic Platform, MarshTheModpack.
My save: https://www.dropbox.com/s/jdg5wxfknil6m1e/Survival.zip?dl=1

If I had to guess what causes this:

1. Create an ore processing 'factory' that has starts at the chemical injection chamber with elite machines and full upgrades on all machines. The factory involves all electrolytic separators and a brine production area in a very far away area in a desert that's using entangloporters to transfer electricity and brine between the two 'factories'. Have a portal between the ore place and the thermal place.
2. Have a shortage in electricity and a mild brine shortage
3. Leave the ore processing factory to run for a while and go about your ways and through the portals a few times until you notice the issue.

Pics:
![2018-06-15_13 31 27](https://user-images.githubusercontent.com/34864792/41470998-4869c196-70aa-11e8-86e1-b04f5d1748dd.png)
![2018-06-15_13 31 58](https://user-images.githubusercontent.com/34864792/41470999-488bc7a0-70aa-11e8-99e3-e48fb277a64e.png)
![2018-06-15_13 34 12](https://user-images.githubusercontent.com/34864792/41471000-48a8c990-70aa-11e8-9f30-be8f54da2f15.png)
![2018-06-15_13 34 48](https://user-images.githubusercontent.com/34864792/41471004-48cad990-70aa-11e8-8437-50fb9a359c01.png)
![2018-06-15_13 28 31](https://user-images.githubusercontent.com/34864792/41471005-48fd92b8-70aa-11e8-97a9-edeae561d45f.png)
![2018-06-15_13 29 21](https://user-images.githubusercontent.com/34864792/41471008-495fde78-70aa-11e8-8100-77c54bbaa4d5.png)
![2018-06-15_13 31 02](https://user-images.githubusercontent.com/34864792/41471009-49876f38-70aa-11e8-8925-83971cb3522d.png)
![capture](https://user-images.githubusercontent.com/34864792/41471330-3dd4be4c-70ab-11e8-9b39-c20971aa123d.gif)

#### Version (make sure you are on the latest version before reporting):
Forge: forge-1.12.2-14.23.4.2705-universal
Mekanism: Mekanism-1.12.2-9.4.11.346, MekanismGenerators-1.12.2-9.4.11.346, MekanismTools-1.12.2-9.4.11.346
Minecraft: 1.12.2

Sorry if my description isn't specific enough I don't know how else to describe it.
Thanks for your help :)

**Comment by thommy101** [comment] 2018-06-15 14:01
Thanks for the detailed report, but it seems like this is a duplicate of #4676.

**Comment by thiakil** [comment] 2018-06-15 14:22
sure is

**Closed by thiakil** 2018-06-15 14:22 UTC
