### ISSUE TITLE
Digital Miner not mining [Multiplayer]

### ISSUE THREAD

**Issue by pchard** [aidancbrady/Mekanism#3404] opened 2016-06-24 19:44 UTC
Hello.

Using Mekanism-1.7.10-9.0.2.271.

In this version, after updating, it does not seem like the digital miner wants to mine any blocks at all.
It consumes power like it normally would, it counts the blocks, but it doesn't mine anything.
This seems to be a issue ONLY on multiplayer since singleplayer works fine.

I could use some assistance.

**Comment by ruyanve** [comment] 2016-06-25 08:09
Duplicate of #3401

**Comment by aidancbrady** [comment] 2016-06-26 19:50
I'm afraid I can't reproduce this.  There's a chance that a mod is utilizing Forge's permissions system to prevent the blocks from breaking, as the Digital Miner now ties into this.  I have a feeling that a vanilla installation of Forge on a server with Mekanism would not result in this issue.

**Closed by aidancbrady** 2016-06-26 19:50 UTC

**Comment by pchard** [comment] 2016-06-26 20:15
Could you perhaps elaborate? I don't really understand your answer @aidancbrady

**Comment by aidancbrady** [comment] 2016-06-26 20:23
The Digital Miner first does a check that the world allows a block to be broken before it actually removes the block from the world.  This check can be utilized by other mods to prevent blocks from being broken, such as permissions systems (which are prevalent on modded servers).  There's a good chance that one of those mods is tying into the check which is preventing the miner from taking the block.

**Comment by pchard** [comment] 2016-06-26 20:28
And there's no way to like, give that permission to the Digital Miner @aidancbrady ?

**Comment by pchard** [comment] 2016-06-28 07:57
Update btw: EssentialsAntibuild plugin interfeared.
