### ISSUE TITLE
Chemical Dissolution Chamber

### ISSUE THREAD

**Issue by hisorange** [aidancbrady/Mekanism#2531] opened 2015-04-14 11:21 UTC
Aye, the chemical dissolution chamber can run without the acid and process ores into slurry.
Also you can even upgrade the chamber with gas / energy upgrade without breaking the bug, but when you put in an energy upgrade the acid becomes required.

(also the machine seems to belive he is a xmas light cuz flashing light kinda randomly without doing anything :)

v8.1.1.225

**Comment by aidancbrady** [comment] 2015-04-28 05:15
Just did some testing and couldn't reproduce - there's a good chance this was already fixed in development.  Once v8.1.2 is released (should be within the next few days) you can let me know if its still occurring on your end :)

**Closed by aidancbrady** 2015-04-28 05:15 UTC
