### ISSUE TITLE
Crash on startup

### ISSUE THREAD

**Issue by TimGoll** [aidancbrady/Mekanism#4836] opened 2017-11-29 09:20 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
game crashes on startup

#### Steps to reproduce:
1. start game with mods

#### Version (make sure you are on the latest version before reporting):
**Forge:** forge-14.23.1.2556 (newest)
**Mekanism:** newest (*327)
**Other relevant version:** 

[crash report](https://gist.github.com/TimGoll/50b602c8ce70afbd2fa7b6558824453f)

**Comment by thommy101** [comment] 2017-11-29 10:02
Duplicate of #4827

**Closed by thommy101** 2017-11-29 10:02 UTC
