### ISSUE TITLE
Electrolytic Separator

### ISSUE THREAD

**Issue by zzApotheosis** [aidancbrady/Mekanism#2509] opened 2015-04-12 07:40 UTC
The electrolytic separator functions properly on the recommended forge version, which is 10.13.2.1291, but does not function on the (current) latest forge version 10.13.3.1370.

Using build 224.

**Comment by unpairedbracket** [comment] 2015-04-12 08:56
Try build 223 (not 224, I reverted the change because people complained)

**Comment by ate0ate** [comment] 2015-04-12 10:38
You do plan on reverting the revert eventually and updating to newer versions of forge for 1.7.10 though, correct? Many mods have made the necessary changes to the fluid registration and require the newer forge versions to function.

**Comment by grimallq** [comment] 2015-04-12 10:42
@ate0ate That goes without saying. Just quite a lot of mods haven't updated Forge yet. Including some popular stuff like Thermal Dynamics and TiCon.

**Comment by NitroxydeX** [comment] 2015-04-12 17:26
Running into the same Problem with Forge 1370 and Mekanism 223. Electrolytic Seperator are not working and also Solar Plants are NOT working. They heat up but aren't producing anything.

**Comment by ate0ate** [comment] 2015-04-12 17:29
The cofh mods are updated to the new forge system (1355+) but yeah, TiCon is not. Its no problem though. I don't mind waiting patiently for mek to update again. Build 223 works fine for me so far. I was just concerned that mek may be sticking with forge 1291 and moving on to minecraft 1.8.

**Comment by NitroxydeX** [comment] 2015-04-12 17:43
@ate0ate which forge version you running at? And can you take a look at the Electrlytic Seperators if they are working in your environment?

**Comment by ate0ate** [comment] 2015-04-12 23:05
Yup, I can confirm after lots of experimenting that the electrolytic seperator and evaporation plant in build 223 definitely does not work even when using forge 1370:(

Hopefully this gets fixed soon. TiCon just updated to the new forge fluid system too. Reverting back to forge 1291 is even less feasible now that most mod updates rely on the new fluid system.

**Comment by aidancbrady** [comment] 2015-04-13 12:21
Closing - I'm thinking I'll update next week.

**Closed by aidancbrady** 2015-04-13 12:21 UTC
