### ISSUE TITLE
Cable behaviour

### ISSUE THREAD

**Issue by HadesDurin** [aidancbrady/Mekanism#3302] opened 2016-05-30 07:30 UTC
As a result of a discussion in draconic evolution, i want to bring this up to your attention.

Link to original issue report: https://github.com/brandon3055/Draconic-Evolution/issues/323

As you see when i use mekanism cable it stops filling the energy core, when the energy pylon buffer runs full at 2,147B RF. 

As @brandon3055 points out, that your cable stop transfering energy after filling the energy pylon.

Question is is it intended that way?

**Comment by brandon3055** [comment] 2016-05-30 07:40
First of all i would just like to point out that this isnt really anyone's fault. Mekanism's implementation of the RF API is perfectly valid. 

The issue is because the RF API uses ints everything is limited max int. To get around this i store the actual energy value as a long and just return max int if the value is higher than max int. most mods that implement RF when transferring energy dont actually check if the block receiving has room for energy. They just attempt to make the transfer and let the block receiving figure out how much it can accept. But is seems Mekanism is checking how much the receiver can accept before attempting to send energy. I suspect that implementation would not be any more efficient  that just letting the receiver figure it out for itself unless Mekanism is doing something custom so its not attempting to send every tick when the receiver is full.

**Comment by aidancbrady** [comment] 2016-06-16 00:27
Should no longer be an issue with the latest Mekanism build.

**Closed by aidancbrady** 2016-06-16 00:27 UTC
