### ISSUE TITLE
[1.10] Mechanical Pipes stop working after server restart

### ISSUE THREAD

**Issue by Ramireztime** [aidancbrady/Mekanism#3460] opened 2016-07-10 01:32 UTC
_Using 9.1.0 build in MC 1.10 (Forge 12.18.0.2000)_
It appears that mechanical pipes fail to function after a server restart. I've tested this with all tiers and also just unloading chunks, but like I said above, it's only after a server restart. It doesn't appear to happen in a single player world though. They do work after you break and replace them.

![2016-07-09_18 15 07](https://cloud.githubusercontent.com/assets/1784580/16711187/b43d020e-4602-11e6-9d37-33eb17c0c4e1.png)
![2016-07-09_18 28 34](https://cloud.githubusercontent.com/assets/1784580/16711197/02f91a18-4603-11e6-8ec0-103fbbd19d0a.png)
If it matters at all: this pump does not  have any upgrades in it and it connects to a farm valve from Forestry.

**Comment by aidancbrady** [comment] 2016-07-10 15:39
Can't reproduce this, tested in both singleplayer and multiplayer.  Closing for now as 1.10 is not supported yet by me, I'll take a look later.

**Closed by aidancbrady** 2016-07-10 15:39 UTC

**Comment by Archadia** [comment] 2016-08-20 22:26
This error has occurred again under user EzR3aL for 1.10.2 forge 2065. This includes for all pipe types.

**Comment by Avamander** [comment] 2017-06-17 23:41
I can confirm this issue, happens when chunk is unloaded/reloaded. 
Using:
Minecraft 1.11.2
Forge-1.11.2-13.20.0.2315-universal
Mekanism-1.11.2-9.3.2.307.jar
MekanismGenerators-1.11.2-9.3.2.307
MekanismTools-1.11.2-9.3.2.307
omlib-1.11.2-3.0.0-100
openmodularturrets-1.10.2-3.0.0-158
dynmap-2.4-3 and dynmap-core-2.4-2082
worldedit-6.1.8
chunk-pregenerator-1.2

**Comment by Avamander** [comment] 2017-06-18 10:44
http://imgur.com/a/YtCko

**Comment by Avamander** [comment] 2017-06-18 11:10
This also happens with energy conductors, they do not belong in a network but conduct, replacing one will break the conductivity. The new conductor thinks it's in a one-block network.

**Comment by KittenKoder** [comment] 2017-11-26 06:36
It effects all pipes and cables in Mekanism, especially on multiplayer servers. The code for the transmission of stuff is hard to find but I'm trying to spot the problem.

**Comment by ryaniskira** [comment] 2018-02-28 04:29
I can confirm I am having this issue as well.
