### ISSUE TITLE
Game crashed then kept crashing when loading saved world.

### ISSUE THREAD

**Issue by LordHellscream** [aidancbrady/Mekanism#4700] opened 2017-09-19 06:27 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
Game crashed then kept crashing when loading the saved world.
Crash log : https://pastebin.com/fExBhj9N

#### Steps to reproduce:
1. Happened suddenly.

#### Version (make sure you are on the latest version before reporting):
**Forge:** 1.11.2-13.20.1.2454
**Mekanism:** 1.11.2 - 9.3.4
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)
https://pastebin.com/fExBhj9N

**Comment by LordHellscream** [comment] 2017-09-19 06:28
also, tried the latest version 9.3.5 it didn't fix the problem

**Comment by thiakil** [comment] 2017-09-19 07:41
Duplicate of #4487 and a few others. This should  be fixed in the next release

**Comment by thommy101** [comment] 2017-09-24 11:09
Closed by accident, will close after version is released

**Closed** 2017-11-27 01:05 UTC
Labels: Fixed in dev
