### ISSUE TITLE
Crash With New Forge: Gasses must be registered before postInit

### ISSUE THREAD

**Issue by kenijey** [aidancbrady/Mekanism#4840] opened 2017-12-01 11:16 UTC
[crash-2017-12-01_14.15.13-client.txt](https://github.com/aidancbrady/Mekanism/files/1521360/crash-2017-12-01_14.15.13-client.txt)

crash report says everythin

**Comment by thommy101** [comment] 2017-12-01 12:17
Duplicate of #4827

**Closed by thommy101** 2017-12-01 12:17 UTC
