### ISSUE TITLE
Modpack on 1.7.10 crashes

### ISSUE THREAD

**Issue by Spirouxi** [aidancbrady/Mekanism#5270] opened 2019-02-02 11:58 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I wanted to add Mekanism to the 1.7.10 modpack "Realm of Mianite", so I did and when I launch my client, forges loads since like 24% and then the client crashes. In the logs, it says that the SolarEvaporationController.class is not found...
I really need to add mekanism on the 1.7.10 version and I can't...

**Forge: ForgeMultipart-1.7.10-1.2.0.345-universal.jar** 
**Mekanism: Mekanism-1.7.10-9.1.1.1031** 

#### Crash-Report:

https://pastebin.com/Le7bEbex

**Comment by Spirouxi** [comment] 2019-02-05 08:45
up ?

**Comment by Tahakk** [comment] 2019-02-05 12:59
1.7.10 is no longer supported, move to newer version.

**Comment by Spirouxi** [comment] 2019-02-06 08:23
> 1.7.10 is no longer supported, move to newer version.

Ofc and that may be the reason why i can run the regular MC with the same version of mekanism, I'm asking help to fix my issue, I'm not asking some guys who say "give up"...
Thank you anyway for your answer but that's not this kind of answer that I want...

**Comment by Tahakk** [comment] 2019-02-06 14:56
Fine, since Mekanism as is working fine, you will have to figured out on yourself the problem, start taking mods out and see when it stops. Or try to replicate the pack on yourselft, then you can copy configs or custom scripts if there are any

**Comment by Spirouxi** [comment] 2019-02-07 09:24
> Fine, since Mekanism as is working fine, you will have to figured out on yourself the problem, start taking mods out and see when it stops. Or try to replicate the pack on yourselft, then you can copy configs or custom scripts if there are any

Thanks a lot, i'll try it and tell you if it worked ^^

**Comment by Jaari** [comment] 2019-02-14 13:09
Duplicate of [#3483](https://github.com/aidancbrady/Mekanism/issues/3483#issue-165696071)

**Closed** 2019-02-14 13:59 UTC
