### ISSUE TITLE
[Server]Client chrash on using configurator

### ISSUE THREAD

**Issue by Hero9909** [aidancbrady/Mekanism#4851] opened 2017-12-07 13:57 UTC
client chrash if changing pipe mode with configurator

#### Steps to reproduce:
1.get a mechenical pipe connectet to anything
2.try to change mode ( Push / Pull / NONE)
3.ERR (see pastbin)

#### Version (make sure you are on the latest version before reporting):
**Forge:** 14.23.1.2559
**Mekanism:** 9.4.2

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[https://pastebin.com/fUpq1peF](url)

**Comment by thommy101** [comment] 2017-12-07 15:30
Duplicate of #4835.

**Closed by thommy101** 2017-12-07 15:30 UTC
