### ISSUE TITLE
MCmultipart link 404

### ISSUE THREAD

**Issue by Y0ungSandwich** [aidancbrady/Mekanism#4119] opened 2017-01-03 17:21 UTC
http://maven.amadornes.com/MCMultiPart/MCMultiPart-experimental/2.0.0_88//MCMultiPart-experimental-2.0.0_88-universal.jar

**Comment by Anteater46** [comment] 2017-01-03 17:27
Yeah, there aren't any versions after 1.3.0_87. I can't find a way to stop it attempting to replace the version I'm giving it.

**Comment by oryfoxer7410** [comment] 2017-01-03 18:18
Here's the original file, http://bit.ly/2iLIRZC

**Comment by ktole1999** [comment] 2017-01-03 18:23
use the version that mek is auto downloading till he can remove the dependancy. otherwise you will always have duplicates if you add the mcmultipart mod to your pack. Especially if this is a curse/ftb pack.

**Comment by Cuppycake** [comment] 2017-01-03 18:35
This is exactly what Mekanism is calling for on download.  I've found a work around on ATL.

**Comment by thommy101** [comment] 2017-01-03 19:38
This issue has been fixed (it stops auto downloading the wrong file) in the 1.10 branch, sadly the 1.10 file found on the site is made of the master branch. There is an issue open with the request to merge the 1.10 in master (or build 1.10 from the 1.10 branch).

**Comment by oryfoxer7410** [comment] 2017-01-03 19:42
@thommy101 Are there any functionality differences in 1.3.0 and the experimental that is being called for my deploader? 

On our pack, we just removed the dependency and installed 1.3.0? 

Should we expect anything to break that you are aware of?

**Comment by thommy101** [comment] 2017-01-03 19:51
1.3 is fully supported, I don't even know where I have to look for any 2.x version.
My fix for it (I'm just a helpfull minecraft player/programmer) was to depend on mcmultipart and remove deploader. I'm running a server with mcmultipart 1.3.0 without problems.

**Comment by ate0ate** [comment] 2017-01-03 23:48
The 1.3.0 build of MCMultipart is a lot older than the 2.0.0 build. Using the old version causes a crash every single time you try to remove Mek cabling using a Pickaxe and some other tools. Sucks. What I did was just download the "All the Mods" Pack on curse and take the copy of MCMultipart 2.0.0 out of the mods folder there and throw it in my instance. Works like a charm. No messy deleteing dependencies that way and no overwriting from other mods since 2.0.0 is the "latest" version.

**Comment by oryfoxer7410** [comment] 2017-01-04 05:03
@ate0ate I was unable to reproduce that specific issue with 1.3.0.

I posted this earlier, but here is the link again to the 2.0 version (not in bitylink) so you don't have to go download a large pack just to get it. 

I will continue to use 1.3.0 until my next pack update which then I will patch with the 2.0. We just needed a quick fix this morning and removal of dependency was the quickest option at that time.  

http://www.infernoworldorder.com/uploads/2/7/2/3/27230849/mcmultipart-experimental-2.0.0_88-universal.jar

**Comment by thommy101** [comment] 2017-01-04 08:28
@ate0ate what you're describing is not a mcmultipart issue, but an old Mekanism issue that's fixed in the latest release. It would also crash with V2.0.0 of mums if I remember correctly

**Comment by Tntdruid** [comment] 2017-01-04 09:44
@oryfoxer7410 Mekanism delete it when i load the mod

**Comment by thommy101** [comment] 2017-01-04 14:28
Another way of solving it is building the latest version from the 1.10 branch.
1.10 branch contains a couple fixes, one of them the removal of deploader.

Here's a build of my own branch, build of 1.10 including all fixes of my which are still open pull requests.
[MekanismAll-1.10.2-9.2.1.thommy101_dev.040117.zip](https://github.com/aidancbrady/Mekanism/files/684869/MekanismAll-1.10.2-9.2.1.thommy101_dev.040117.zip)

**Comment by Cuppycake** [comment] 2017-01-04 14:33
Thanks I'll check this out.

**Comment by Tntdruid** [comment] 2017-01-04 16:06
@thommy101 Works perfect, thanks for making it :)

**Comment by ktole1999** [comment] 2017-01-17 18:27
so how does this work around help a pack that is hosted on curse?

**Comment by thommy101** [comment] 2017-01-17 19:38
You can put your own jar file in a modpack, mekanism isn't hosted on curse.

**Comment by NitroxydeX** [comment] 2017-01-20 15:25
Amadornes added the needed version back in that people can run Mekanism.

**Closed** 2017-03-09 00:08 UTC
