### ISSUE TITLE
1.10.2 Digital Miner Rotating

### ISSUE THREAD

**Issue by Sora-Canstavia** [aidancbrady/Mekanism#4521] opened 2017-07-09 23:00 UTC
*Please use the search functionality before reporting an issue. Also take a look at the closed issues!*

#### Issue description:
I Know its been mentioned before, and that you said that you would fix it for the 1.11 version, I Primarily wanted to ask if it could also be fixed for the 1.10 version as it is causing issues wherein we're trying to use the machine but when it rotates its GUI resets and we have to close the GUI and re-open it to get it to reappear again, then it rotates again after a few seconds. I Would really appreciate any help with this as we currently can't update our server to 1.11 due to other mods not being updated as well as likely having to reset the world file.

#### Steps to reproduce:
1.Place down Digital Miner
2.Wait for a while
3.Watch it rotate and be unbreakable

#### Version (make sure you are on the latest version before reporting):
**Forge:** 12.18.3.2272
**Mekanism:** 1.10.2-9.2.2.301
**Other relevant version:** 

#### If a (crash)log is relevant for this issue, link it here: (_It's almost always relevant_)

[gist/pastebin/etc link here]

**Comment by thommy101** [comment] 2017-07-10 12:12
Duplicate of #3977.

Regarding a 1.10 fix, check out #4504.

**Closed** 2017-07-11 21:19 UTC
